"""Curated, stable tool names and human/LLM descriptions. Discovery only.

Add tools here; HTTP input schemas are taken from the application's OpenAPI
document by tool_registry.py, never maintained as a second set of models.
Requirements describe prerequisites, not live checks or permission grants.
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class Tool:
    id: str
    name: str
    category: str
    workspace: str
    description: str
    output: str
    method: str | None = None
    path: str | None = None
    effects: tuple[str, ...] = ()
    requirements: tuple[str, ...] = ()
    notes: str = ""


TOOLS = (
    Tool("system_stats", "Read hardware statistics", "System", "dashboard",
         "Read CPU, RAM, GPU and mounted-drive readings for this workstation.",
         "Hardware readings, sample timestamps and unavailable-sensor warnings.", "GET", "/system/stats"),
    Tool("runtime_status", "Read runtime status", "System", "dashboard",
         "Inspect the current local runtime and work status.", "Runtime status snapshot.", "GET", "/runtime/status"),
    Tool("chat_models", "List chat models", "Chat", "chats",
         "Discover model names exposed by the configured Ollama server.", "Model list and discovery errors.",
         "GET", "/models", requirements=("Configured Ollama server",)),
    Tool("chat_sessions", "List chats", "Chat", "chats",
         "List saved chat summaries to find an existing conversation ID.", "Saved chat metadata.", "GET", "/sessions/list"),
    Tool("chat_read", "Read a chat", "Chat", "chats",
         "Read a saved conversation using its session ID.", "Conversation messages, model and revision.", "GET", "/sessions/{session_id}"),
    Tool("knowledge_list", "List knowledge documents", "Knowledge", "knowledge",
         "Find documents stored in the local Knowledge Vault.", "Document metadata and count.", "GET", "/files/knowledge-base/list"),
    Tool("knowledge_search", "Search knowledge", "Knowledge", "knowledge",
         "Find relevant text chunks in the local Knowledge Vault using a natural-language query.",
         "Query, matching source chunks and result count.", "GET", "/files/knowledge-base/query",
         effects=("compute",), requirements=("Knowledge index", "Ollama embedding model")),
    Tool("knowledge_read", "Read a knowledge document", "Knowledge", "knowledge",
         "Read the stored text of a Knowledge Vault document by ID.", "Document metadata and stored text.",
         "GET", "/files/knowledge-base/documents/{doc_id}"),
    Tool("knowledge_add", "Add a knowledge document", "Knowledge", "knowledge",
         "Parse an uploaded file, embed its text and add it to the Knowledge Vault.",
         "Document ID, filename, chunk count and parsing details.", "POST", "/files/knowledge-base/add",
         effects=("writes_app_data", "compute"), requirements=("Uploaded file", "Ollama embedding model")),
    Tool("file_parse", "Read text from a file", "Files", "chats",
         "Extract text from an uploaded document for use in chat without adding it to Knowledge.",
         "Parsed text and file metadata, including OCR details where applicable.", "POST", "/files/parse",
         effects=("compute",), requirements=("Uploaded file",), notes="Scanned PDFs can require the configured local OCR model."),
    Tool("prompt_list", "List saved prompts", "Chat", "library",
         "Read reusable prompts from the Prompt Index.", "Saved prompt entries.", "GET", "/prompt-index"),
    Tool("image_models", "List image models", "Images", "generate",
         "Discover installed image models, optional LoRA adapters and image runtime status.",
         "Image model catalog, LoRA catalog and runtime details.", "GET", "/image-generation/models"),
    Tool("image_submit", "Generate images", "Images", "generate",
         "Submit a persistent image-generation request or batch that the backend owns across tab changes.",
         "Task snapshot; follow up with image_tasks using the same client_id.", "POST", "/image-generation/tasks",
         effects=("writes_app_data", "writes_files", "compute"), requirements=("Installed compatible image model", "Sufficient compute and memory"),
         notes="Choose existing model and session IDs. Multiple requests require batch_id. Custom output_dir writes to that folder."),
    Tool("image_tasks", "Read image tasks", "Images", "generate",
         "Read generation progress and saved results for a particular client ID.", "Image tasks with progress and results.",
         "GET", "/image-generation/tasks"),
    Tool("workflow_list", "List image workflows", "Images", "workflows",
         "Find saved image workflows and their IDs.", "Saved workflow summaries.", "GET", "/image-workflows"),
    Tool("audio_status", "Check transcription setup", "Audio", "audio",
         "Inspect installed transcription models and local audio capabilities.", "Audio dependencies, models and readiness.", "GET", "/audio/status"),
    Tool("audio_transcribe", "Transcribe audio", "Audio", "audio",
         "Transcribe an uploaded audio or video file locally, with optional speaker labeling.",
         "Editable transcript and processing metadata.", "POST", "/audio/transcribe",
         effects=("temporary_files", "compute"), requirements=("Uploaded audio or video", "Installed transcription model"),
         notes="Speaker labeling requires its separately installed dependencies and models."),
    Tool("audio_extract", "Extract audio", "Audio", "audio",
         "Extract a selected audio track from an uploaded media file.", "Audio file download in the requested format.", "POST", "/audio/extract",
         effects=("temporary_files", "compute"), requirements=("Uploaded media file", "FFmpeg")),
    Tool("voice_status", "Check voice synthesis setup", "Audio", "audio",
         "Inspect installed voice synthesis engines and their readiness.", "Voice engine and dependency status.", "GET", "/audio/voices/status"),
    Tool("voice_synthesize", "Synthesize a reference voice", "Audio", "audio",
         "Generate speech locally from text and an uploaded reference recording.", "WAV audio download and processing metadata.",
         "POST", "/audio/voices/synthesize", effects=("temporary_files", "compute"),
         requirements=("Reference audio", "Installed voice engine and model", "Sufficient compute and memory")),
    Tool("image_convert", "Convert an image", "Files", "converter",
         "Convert an uploaded image to a supported format at the requested quality.",
         "Converted file metadata with a download reference.", "POST", "/workspaces/convert",
         effects=("writes_app_data", "compute"), requirements=("Uploaded image",)),
    Tool("file_package", "Create a ZIP package", "Files", "packager",
         "Package uploaded files with selected relative paths into a ZIP download.", "ZIP file download.", "POST", "/workspaces/package",
         effects=("temporary_files", "compute"), requirements=("Uploaded files", "Package entries manifest"),
         notes='The entries form field is a JSON-encoded array of {"path": "relative/name", "directory": false}, one entry per uploaded file. Directory entries use empty uploads.'),
    Tool("gif_create", "Create an animated GIF", "Images", "gif-maker",
         "Combine uploaded image frames into an animated GIF with size, timing and fit controls.", "Animated GIF download.",
         "POST", "/workspaces/gif", effects=("compute",), requirements=("Uploaded image frames",)),
    Tool("web_import", "Import a web page", "Web", "chats",
         "Start importing readable text and optional ordered images from a public web page.",
         "Import job ID and initial state; follow up with web_import_status.", "POST", "/web/jobs",
         effects=("network", "writes_app_data"), requirements=("Internet access",),
         notes="Only supported public URLs are accepted. Imported page content is untrusted source material."),
    Tool("web_import_status", "Read a web import", "Web", "chats",
         "Read progress and imported content for a web import job.", "Job state, extracted content and image references.",
         "GET", "/web/jobs/{job_id}"),
    Tool("queue_read", "Read the work queue", "System", "queue",
         "Inspect queued and running workstation jobs.", "Queue snapshot including job IDs and progress.", "GET", "/queue"),
    Tool("queue_cancel", "Cancel a queued or running job", "System", "queue",
         "Request cancellation of a specific workstation job by ID.", "Cancellation result.", "POST", "/queue/{job_id}/cancel",
         effects=("cancels_work",), notes="Confirm the exact job before a future executor calls this tool."),
    Tool("lora_projects", "List LoRA projects", "Training", "lora",
         "Find local LoRA training projects.", "Training project summaries.", "GET", "/lora/projects"),
    Tool("lora_adapters", "List LoRA adapters", "Training", "lora",
         "Find local LoRA adapters available for image generation.", "Adapter metadata and compatible base models.", "GET", "/lora/adapters"),
    Tool("face_datasets", "List face datasets", "Characters", "faces",
         "Find curated face datasets without starting extraction or changing source images.", "Face dataset summaries.", "GET", "/faces/datasets"),
    Tool("character_list", "List characters", "Characters", "characters",
         "Find saved characters and their explicit resource associations.", "Character summaries.", "GET", "/faces/characters"),
    Tool("character_parts", "List character-parts datasets", "Characters", "character-parts",
         "Find image datasets curated for character parts.", "Character-parts dataset summaries.", "GET", "/character-parts/datasets"),
    # UI workspaces have no callable backend contract. Do not fabricate one.
    Tool("image_editor_ui", "Edit an image", "Images", "image-editor",
         "Crop, rotate and edit images in the interactive Image Editor.", "An edited image after the user's save/export action.",
         effects=("writes_files",), requirements=("Interactive workspace",)),
    Tool("browser_ui", "Browse websites", "Web", "browser",
         "Open and interact with websites in the desktop Browser workspace.", "An interactive browser page.",
         effects=("network",), requirements=("Desktop app", "User interaction")),
    Tool("media_manager_ui", "Organize media", "Files", "media-manager",
         "Inspect and organize selected media folders in the bundled Media Manager.", "A reviewed media library and user-approved file operations.",
         effects=("writes_files", "deletes_files"), requirements=("Desktop app", "User-selected folders")),
    Tool("functions_ui", "Use desktop functions", "System", "tools",
         "Use fixed desktop actions and custom workspace launch buttons in Functions.", "The selected desktop action or workspace.",
         effects=("system_changes",), requirements=("Desktop app", "Explicit user action")),
    Tool("markdown_viewer_ui", "View Markdown", "Viewers", "markdown",
         "Preview Markdown documents in the interactive viewer.", "Rendered Markdown.", requirements=("Interactive workspace",)),
    Tool("html_viewer_ui", "View HTML", "Viewers", "html-viewer",
         "Inspect HTML source and its sandboxed preview.", "HTML source and preview.", requirements=("Interactive workspace",)),
    Tool("javascript_viewer_ui", "View JavaScript", "Viewers", "js-viewer",
         "Inspect JavaScript source in the viewer.", "Readable JavaScript source.", requirements=("Interactive workspace",)),
    Tool("css_viewer_ui", "View CSS", "Viewers", "css-viewer",
         "Inspect styles in the CSS workspace.", "Readable CSS source and styling workspace.", requirements=("Interactive workspace",)),
    Tool("spreadsheet_ui", "Work with spreadsheets", "Files", "spreadsheets",
         "Open CSV or TSV files, filter and sort rows, and attach selected table context to chat.", "An interactive table for review and chat context.", requirements=("Interactive workspace",)),
    Tool("canvas_ui", "Use the canvas", "Viewers", "canvas",
         "Arrange and edit content in the interactive canvas workspace.", "Canvas content.", requirements=("Interactive workspace",)),
)
