"""Curated, stable tool names and human/LLM descriptions. Discovery only.

Add tools here; HTTP input schemas are taken from the application's OpenAPI
document by tool_registry.py, never maintained as a second set of models.
Requirements describe prerequisites, not live checks or permission grants.
"""
from dataclasses import dataclass


@dataclass(frozen=True)
class Tool:
    id: str
    name: str
    category: str
    workspace: str
    description: str
    output: str
    method: str | None = None
    path: str | None = None
    effects: tuple[str, ...] = ()
    requirements: tuple[str, ...] = ()
    notes: str = ""


TOOLS = (
    Tool('linked_app_processes', 'Read linked application processes', 'System', 'integrations',
         'Read process names, IDs and executable paths for Cura, Discord, Spotify and scrcpy, plus supplied scrcpy readiness.',
         'Technical process metadata and local integration readiness.', 'GET', '/integrations/status'),
    Tool('linked_app_embed', 'Prepare an application embed', 'Applications', 'integrations',
         'Validate a Spotify content link or Discord server ID and return its official embed URL.',
         'An allowlisted embed URL; it opens only on an explicit desktop action.', 'POST', '/integrations/embed'),
    Tool('discord_preview', 'Preview Discord content', 'Applications', 'integrations',
         'Prepare an embed and message preview with automatic mentions disabled; no content is sent.',
         'A reviewable Discord payload.', 'POST', '/integrations/discord/preview'),
    Tool('discord_send', 'Send reviewed content to Discord', 'Applications', 'integrations',
         'Explicitly send the supplied message, embed and attachments through a user-provided webhook or bot.',
         'Discord delivery confirmation and message ID.', 'POST', '/integrations/discord/send',
         effects=('network', 'sends_content'), requirements=('Explicit Send action', 'User-provided webhook or bot credentials'),
         notes='Credentials are request-scoped and are not discovered from installed Discord profiles.'),
    Tool('spotify_recording_save', 'Save captured playback audio', 'Audio', 'integrations',
         'Save an explicitly captured WebM playback recording as a local application artifact.',
         'Recording ID and download metadata.', 'POST', '/integrations/spotify/recordings', effects=('writes_app_data',)),
    Tool('slicer_readiness', 'Read CuraEngine readiness', '3D', 'slicer',
         'Locate the installed CuraEngine and list supported single-extruder machine definitions.',
         'Engine path, STL support and printer choices.', 'GET', '/slicer/readiness'),
    Tool('slicer_start', 'Slice an STL model', '3D', 'slicer',
         'Explicitly slice an uploaded STL with the selected printer and material settings using local CuraEngine.',
         'A background job ID; source STL and Cura profiles remain unchanged.', 'POST', '/slicer/jobs',
         effects=('compute', 'writes_app_data'), requirements=('Installed CuraEngine', 'Explicit STL and printer settings')),
    Tool('slicer_status', 'Read slicing progress', '3D', 'slicer',
         'Read the active or latest slicing job, progress, elapsed time and result state.', 'Slice state.', 'GET', '/slicer/status'),
    Tool('slicer_stop', 'Stop slicing', '3D', 'slicer',
         'Stop the selected active CuraEngine job without touching source models.', 'Cancellation acknowledgement.',
         'POST', '/slicer/jobs/{ident}/stop', effects=('cancels_work',)),
    Tool('slicer_download', 'Download sliced G-code', '3D', 'slicer',
         'Download a successfully completed local slice. It is not sent to a printer.', 'A G-code file.', 'GET', '/slicer/jobs/{ident}/file'),
    Tool("visual_review_capabilities", "Read visual classification readiness", "Images", "image-manager",
         "Read installed local face and vision providers and supported scene labels without starting inference.",
         "Provider readiness, scene vocabulary and face matching threshold.", "GET", "/visual-review/capabilities"),
    Tool("visual_review_catalog", "Browse people and scene classifications", "Images", "image-manager",
         "Filter reviewed or classified images by person, scene, rating, or names, captions and tags.",
         "Paginated image records, person groups, scene counts and saved review metadata.", "GET", "/visual-review/catalog"),
    Tool("visual_review_classify", "Classify selected images", "Images", "image-manager",
         "Group all detected faces and optionally classify visible settings in explicitly selected catalog images. Names come only from user labels.",
         "A background batch ID; read visual_review_job for progress.", "POST", "/visual-review/classify",
         effects=("compute", "writes_app_data"), requirements=("Registered image IDs", "Installed face provider and/or local vision model"),
         notes="Sources remain unchanged. Groups are similarity suggestions; multiple people may be associated with one image. Completed stages and manual corrections are reused."),
    Tool("visual_review_classify_catalog", "Classify unprocessed catalog images", "Images", "image-manager",
         "Explicitly process up to 1,000 visible catalog images missing the requested face or scene classifications. Repeat to continue.",
         "Background batch and remaining count.", "POST", "/visual-review/classify-catalog", effects=("compute", "writes_app_data")),
    Tool("visual_review_job", "Read visual classification progress", "Images", "image-manager",
         "Read current or last saved classification progress and per-item failures.", "Batch progress and errors.", "GET", "/visual-review/job"),
    Tool("visual_review_stop", "Stop visual classification", "Images", "image-manager",
         "Stop the current batch while retaining completed classifications and corrections.", "Cancellation acknowledgement.", "POST", "/visual-review/stop", effects=("cancels_work",)),
    Tool("storage_libraries_list", "List storage libraries", "Files", "dashboard",
         "List app-owned media libraries, the default for new files, availability and drive free space.",
         "Registered library locations and availability.", "GET", "/storage-libraries"),
    Tool("storage_library_add", "Create or attach a storage library", "Files", "dashboard",
         "Create a dedicated app folder on a selected local drive, or reattach a marked library. Existing files stay in place.",
         "The registered library ID and folder path.", "POST", "/storage-libraries", effects=("writes_app_data",), requirements=("Explicit local parent folder",)),
    Tool("storage_library_default", "Set default storage library", "Files", "dashboard",
         "Choose where new generated and imported media files are stored. Existing objects retain their locations.",
         "Updated default and library availability.", "PUT", "/storage-libraries/default/{library_id}", effects=("writes_app_data",)),
    Tool("folder_review_start", "Start Folder Review", "Files", "folder-review",
         "Inventory a selected local folder and review readable files in batches; images get metadata only and PDFs use native text only.",
         "A background review ID; per-file findings and a combined Markdown report are saved locally.", "POST", "/folder-review/reviews",
         effects=("compute", "writes_app_data", "network"), requirements=("Explicit local folder", "Configured Ollama text model for analysis"),
         notes="Read-only sources; no OCR, image interpretation or code execution. Empty model requests extraction only. Coverage limits and exclusions are reported."),
    Tool("folder_review_status", "Read Folder Review progress", "Files", "folder-review",
         "Read active work and recent saved reviews without starting work.", "Progress, file type counts and coverage.", "GET", "/folder-review/status"),
    Tool("folder_review_files", "Read Folder Review findings", "Files", "folder-review",
         "Read paginated per-file analysis, metadata and omissions.", "Recorded file findings and metadata.", "GET", "/folder-review/reviews/{review_id}/files"),
    Tool("folder_review_cancel", "Stop Folder Review", "Files", "folder-review",
         "Stop future reads and inference while retaining completed findings.", "Review state.", "POST", "/folder-review/reviews/{review_id}/cancel", effects=("cancels_work",)),
    Tool("folder_review_export", "Export Folder Review", "Files", "folder-review",
         "Download a saved folder analysis, inventory and per-file coverage as Markdown.", "A Markdown report containing information from the chosen folder.", "GET", "/folder-review/reviews/{review_id}/export"),
    Tool("image_manager_state", "Read Image Manager status", "Images", "image-manager",
         "Read the independent still-image folder catalog summary, saved image functions, duplicate groups, recent plans and transfer receipts.",
         "Catalog summary and background task progress.", "GET", "/image-manager/state"),
    Tool("image_manager_images", "Browse catalog images", "Images", "image-manager",
         "Search and filter still-image metadata by selected folder, exact saved tag, format, date, favorites or checked duplicate hash.",
         "Paginated catalog image metadata with stable IDs and catalog-wide tag choices.", "GET", "/image-manager/images",
         notes="Catalog snapshot; source folders are scanned only by explicit requests."),
    Tool("image_manager_task", "Run an image folder task", "Images", "image-manager",
         "Explicitly scan registered folders, hash duplicate candidates, prepare organization or duplicate-folder plans, run a saved image function, save a report, or apply a reviewed transfer plan.",
         "Background task ID; read image_manager_state for progress and results.", "POST", "/image-manager/tasks",
         effects=("compute", "writes_app_data", "writes_files", "deletes_files"), requirements=("Explicit registered folder/image IDs",),
         notes="Image functions cannot apply transfers. Applying requires an exact COPY n or MOVE n phrase for a ready plan. Move unlinks sources only after verified copies. Directory links, motion media and NVIDIA paths are excluded."),
    Tool("image_manager_plan", "Review an image transfer plan", "Images", "image-manager",
         "Read all source paths, destination paths, signatures and SHA-256 values for a prepared copy or move plan.",
         "Reviewable plan; reading it does not perform transfers.", "GET", "/image-manager/plans/{identifier}"),
    Tool("image_manager_function", "Save an image function", "Images", "image-manager",
         "Save ordered scan, duplicate-check, organization-plan, duplicate-folder-plan and report steps with explicit source and output folders.",
         "Saved image function, without executing it.", "POST", "/image-manager/functions", effects=("writes_app_data",)),
    Tool("image_manager_stop", "Stop an image folder task", "Images", "image-manager",
         "Request cancellation of an active image task and retain completed catalog records and verified transfers.",
         "Cancellation acknowledgement.", "POST", "/image-manager/tasks/{identifier}/stop", effects=("cancels_work",)),
    Tool("hash_audit_start", "Audit selected folders", "Files", "hash-auditor",
         "Read full file contents under explicitly selected local roots and record SHA-256 hashes and filesystem metadata.",
         "Background scan ID and progress. Source files are read only.", "POST", "/hash-auditor/scans",
         effects=("compute", "writes_app_data"), requirements=("Explicit local folder or drive roots",),
         notes="Never starts automatically. Skips links, cloud placeholders, NVIDIA paths and its own database. Large scopes can take a long time."),
    Tool("hash_audit_status", "Read hash audit progress", "Files", "hash-auditor",
         "Read active scan progress, recent audit history and saved catalogue counts.", "Scan status and recorded coverage.", "GET", "/hash-auditor/status"),
    Tool("hash_audit_matches", "Find recorded file matches", "Files", "hash-auditor",
         "Find equal SHA-256 hashes or metadata candidates across all recorded locations.", "Paginated matching groups with file paths and hard-link identities.", "GET", "/hash-auditor/groups",
         notes="Metadata matches do not prove equal contents. Results describe recorded reads; rescan to refresh them."),
    Tool("hash_audit_files", "Read hash inventory", "Files", "hash-auditor",
         "Search recorded file paths and inspect saved hashes, timestamps and read errors.", "Paginated recorded files.", "GET", "/hash-auditor/files"),
    Tool("hash_audit_cancel", "Cancel a hash audit", "Files", "hash-auditor",
         "Stop a running hash audit after the current read and keep completed file records.", "Cancellation acknowledgement.", "POST", "/hash-auditor/scans/{scan_id}/cancel", effects=("cancels_work",)),
    Tool("hash_audit_export", "Export a hash inventory", "Files", "hash-auditor",
         "Download the full recorded inventory or all matches of the selected type as CSV.", "CSV download including full paths, SHA-256 hashes and observation times.", "GET", "/hash-auditor/export"),
    Tool("system_stats", "Read hardware statistics", "System", "dashboard",
         "Read CPU, RAM, GPU and mounted-drive readings for this workstation.",
         "Hardware readings, sample timestamps and unavailable-sensor warnings.", "GET", "/system/stats"),
    Tool("runtime_status", "Read runtime status", "System", "dashboard",
         "Inspect the current local runtime and work status.", "Runtime status snapshot.", "GET", "/runtime/status"),
    Tool("chat_models", "List chat models", "Chat", "chats",
         "Discover model names exposed by the configured Ollama server.", "Model list and discovery errors.",
         "GET", "/models", requirements=("Configured Ollama server",)),
    Tool("chat_sessions", "List chats", "Chat", "chats",
         "List saved chat summaries to find an existing conversation ID.", "Saved chat metadata.", "GET", "/sessions/list"),
    Tool("chat_read", "Read a chat", "Chat", "chats",
         "Read a saved conversation using its session ID.", "Conversation messages, model and revision.", "GET", "/sessions/{session_id}"),
    Tool("knowledge_list", "List knowledge documents", "Knowledge", "knowledge",
         "Find documents stored in the local Knowledge Vault.", "Document metadata and count.", "GET", "/files/knowledge-base/list"),
    Tool("knowledge_search", "Search knowledge", "Knowledge", "knowledge",
         "Find relevant text chunks in the local Knowledge Vault using a natural-language query.",
         "Query, matching source chunks and result count.", "GET", "/files/knowledge-base/query",
         effects=("compute",), requirements=("Knowledge index", "Ollama embedding model")),
    Tool("knowledge_read", "Read a knowledge document", "Knowledge", "knowledge",
         "Read the stored text of a Knowledge Vault document by ID.", "Document metadata and stored text.",
         "GET", "/files/knowledge-base/documents/{doc_id}"),
    Tool("knowledge_add", "Add a knowledge document", "Knowledge", "knowledge",
         "Parse an uploaded file, embed its text and add it to the Knowledge Vault.",
         "Document ID, filename, chunk count and parsing details.", "POST", "/files/knowledge-base/add",
         effects=("writes_app_data", "compute"), requirements=("Uploaded file", "Ollama embedding model")),
    Tool("file_parse", "Read text from a file", "Files", "chats",
         "Extract text from an uploaded document for use in chat without adding it to Knowledge.",
         "Parsed text and file metadata, including OCR details where applicable.", "POST", "/files/parse",
         effects=("compute",), requirements=("Uploaded file",), notes="Scanned PDFs can require the configured local OCR model."),
    Tool("prompt_list", "List Index entries", "Chat", "library",
         "Read saved notes, prompts and reference text from Index.", "Saved Index entries.", "GET", "/prompt-index"),
    Tool("image_models", "List image models", "Images", "generate",
         "Discover installed image models, optional LoRA adapters and image runtime status.",
         "Image model catalog, LoRA catalog and runtime details.", "GET", "/image-generation/models"),
    Tool("image_submit", "Generate images", "Images", "generate",
         "Submit a persistent image-generation request or batch that the backend owns across tab changes.",
         "Task snapshot; follow up with image_tasks using the same client_id.", "POST", "/image-generation/tasks",
         effects=("writes_app_data", "writes_files", "compute"), requirements=("Installed compatible image model", "Sufficient compute and memory"),
         notes="Choose existing model and session IDs. Multiple requests require batch_id. Custom output_dir writes to that folder."),
    Tool("image_tasks", "Read image tasks", "Images", "generate",
         "Read generation progress and saved results for a particular client ID.", "Image tasks with progress and results.",
         "GET", "/image-generation/tasks"),
    Tool("workflow_list", "List image workflows", "Images", "workflows",
         "Find saved image workflows and their IDs.", "Saved workflow summaries.", "GET", "/image-workflows"),
    Tool("audio_status", "Check transcription setup", "Audio", "audio",
         "Inspect installed transcription models and local audio capabilities.", "Audio dependencies, models and readiness.", "GET", "/audio/status"),
    Tool("audio_transcribe", "Transcribe audio", "Audio", "audio",
         "Transcribe an uploaded audio or video file locally, with optional speaker labeling.",
         "Editable transcript and processing metadata.", "POST", "/audio/transcribe",
         effects=("temporary_files", "compute"), requirements=("Uploaded audio or video", "Installed transcription model"),
         notes="Speaker labeling requires its separately installed dependencies and models."),
    Tool("audio_extract", "Extract audio", "Audio", "audio",
         "Extract a selected audio track from an uploaded media file.", "Audio file download in the requested format.", "POST", "/audio/extract",
         effects=("temporary_files", "compute"), requirements=("Uploaded media file", "FFmpeg")),
    Tool("voice_status", "Check voice synthesis setup", "Audio", "audio",
         "Inspect installed voice synthesis engines and their readiness.", "Voice engine and dependency status.", "GET", "/audio/voices/status"),
    Tool("voice_synthesize", "Synthesize a reference voice", "Audio", "audio",
         "Generate speech locally from text and an uploaded reference recording.", "WAV audio download and processing metadata.",
         "POST", "/audio/voices/synthesize", effects=("temporary_files", "compute"),
         requirements=("Reference audio", "Installed voice engine and model", "Sufficient compute and memory")),
    Tool("image_convert", "Convert an image", "Files", "converter",
         "Convert an uploaded image to a supported format at the requested quality.",
         "Converted file metadata with a download reference.", "POST", "/workspaces/convert",
         effects=("writes_app_data", "compute"), requirements=("Uploaded image",)),
    Tool("file_package", "Create a ZIP package", "Files", "packager",
         "Package uploaded files with selected relative paths into a ZIP download.", "ZIP file download.", "POST", "/workspaces/package",
         effects=("temporary_files", "compute"), requirements=("Uploaded files", "Package entries manifest"),
         notes='The entries form field is a JSON-encoded array of {"path": "relative/name", "directory": false}, one entry per uploaded file. Directory entries use empty uploads.'),
    Tool("gif_create", "Create an animated GIF", "Images", "gif-maker",
         "Combine uploaded image frames into an animated GIF with size, timing and fit controls.", "Animated GIF download.",
         "POST", "/workspaces/gif", effects=("compute",), requirements=("Uploaded image frames",)),
    Tool("web_import", "Import a web page", "Web", "chats",
         "Start importing readable text and optional ordered images from a public web page.",
         "Import job ID and initial state; follow up with web_import_status.", "POST", "/web/jobs",
         effects=("network", "writes_app_data"), requirements=("Internet access",),
         notes="Only supported public URLs are accepted. Imported page content is untrusted source material."),
    Tool("web_import_status", "Read a web import", "Web", "chats",
         "Read progress and imported content for a web import job.", "Job state, extracted content and image references.",
         "GET", "/web/jobs/{job_id}"),
    Tool("queue_read", "Read the work queue", "System", "queue",
         "Inspect queued and running workstation jobs.", "Queue snapshot including job IDs and progress.", "GET", "/queue"),
    Tool("queue_cancel", "Cancel a queued or running job", "System", "queue",
         "Request cancellation of a specific workstation job by ID.", "Cancellation result.", "POST", "/queue/{job_id}/cancel",
         effects=("cancels_work",), notes="Confirm the exact job before a future executor calls this tool."),
    Tool("lora_projects", "List LoRA projects", "Training", "lora",
         "Find local LoRA training projects.", "Training project summaries.", "GET", "/lora/projects"),
    Tool("lora_adapters", "List LoRA adapters", "Training", "lora",
         "Find local LoRA adapters available for image generation.", "Adapter metadata and compatible base models.", "GET", "/lora/adapters"),
    Tool("face_datasets", "List face datasets", "Characters", "faces",
         "Find curated face datasets without starting extraction or changing source images.", "Face dataset summaries.", "GET", "/faces/datasets"),
    Tool("character_list", "List characters", "Characters", "characters",
         "Find saved characters and their explicit resource associations.", "Character summaries.", "GET", "/faces/characters"),
    Tool("character_parts", "List character-parts datasets", "Characters", "character-parts",
         "Find image datasets curated for character parts.", "Character-parts dataset summaries.", "GET", "/character-parts/datasets"),
    # UI workspaces have no callable backend contract. Do not fabricate one.
    Tool("image_editor_ui", "Edit an image", "Images", "image-editor",
         "Crop, rotate and edit images in the interactive Image Editor.", "An edited image after the user's save/export action.",
         effects=("writes_files",), requirements=("Interactive workspace",)),
    Tool("browser_ui", "Browse websites", "Web", "browser",
         "Open and interact with websites in the desktop Browser workspace.", "An interactive browser page.",
         effects=("network",), requirements=("Desktop app", "User interaction")),
    Tool("media_manager_ui", "Organize media", "Files", "media-manager",
         "Inspect and organize selected media folders in the bundled Media Manager.", "A reviewed media library and user-approved file operations.",
         effects=("writes_files", "deletes_files"), requirements=("Desktop app", "User-selected folders")),
    Tool("functions_ui", "Use desktop functions", "System", "tools",
         "Use fixed desktop actions and custom workspace launch buttons in Functions.", "The selected desktop action or workspace.",
         effects=("system_changes",), requirements=("Desktop app", "Explicit user action")),
    Tool("markdown_viewer_ui", "View Markdown", "Viewers", "markdown",
         "Preview Markdown documents in the interactive viewer.", "Rendered Markdown.", requirements=("Interactive workspace",)),
    Tool("html_viewer_ui", "View HTML", "Viewers", "html-viewer",
         "Inspect HTML source and its sandboxed preview.", "HTML source and preview.", requirements=("Interactive workspace",)),
    Tool("javascript_viewer_ui", "View JavaScript", "Viewers", "js-viewer",
         "Inspect JavaScript source in the viewer.", "Readable JavaScript source.", requirements=("Interactive workspace",)),
    Tool("css_viewer_ui", "View CSS", "Viewers", "css-viewer",
         "Inspect styles in the CSS workspace.", "Readable CSS source and styling workspace.", requirements=("Interactive workspace",)),
    Tool("spreadsheet_ui", "Work with spreadsheets", "Files", "spreadsheets",
         "Open CSV or TSV files, filter and sort rows, and attach selected table context to chat.", "An interactive table for review and chat context.", requirements=("Interactive workspace",)),
    Tool("canvas_ui", "Use the canvas", "Viewers", "canvas",
         "Arrange and edit content in the interactive canvas workspace.", "Canvas content.", requirements=("Interactive workspace",)),
)
