export const chatHelp = [
  ['Transcript navigation', [
    ['Pin / Unpin', 'Save a message pin with this conversation. Pinning does not change the message or send it to the model again.'],
    ['Pinned', 'Open the list of pinned messages and choose one to jump to its original position in the transcript.'],
    ['Top / Bottom', 'Jump to either end of this chat. Reading older messages pauses automatic following of streamed text; Bottom resumes it.'],
    ['Steer', 'During a supported active chat reply, enter a new direction. Stop & steer saves the partial reply, runs your instruction next, and preserves queued prompts and the composer draft.'],
  ]],
  ['Models', [
    ['Chat model', 'Select the installed Ollama model used for your next message. Changing it keeps the conversation; earlier replies are not regenerated. Model size and architecture affect speed, memory use and capabilities.'],
    ['Model status', 'Shows connection and request readiness. A listed model can still fail to load if the runtime is unavailable or memory is exhausted. Status updates automatically when the service becomes available.'],
    ['Model order', 'Use the arrows in Chat options to arrange the model dropdown. Selecting a model there also selects it for chat.'],
    ['Vision models', 'Use a model that supports images when asking about attached pictures. Text-only models cannot inspect image pixels. Image generation uses its own model picker.'],
    ['Memory Summary Model', 'Chooses the local model that summarizes older chat context. Use active model follows the chat model.'],
  ]],
  ['Conversation controls', [
    ['Send', 'Enter sends your message; Shift+Enter inserts a newline. Messages submitted while work is busy wait in the shared queue.'],
    ['Stop', 'Stops the current reply. Use Cancel waiting prompt to remove a message that has not started.'],
    ['Waiting prompts', 'Follow-ups wait for the earlier reply, then join Prompt Queue with the updated conversation context. Cancel waiting prompt removes only that queued message.'],
    ['New chat', 'Starts a separate history. Use this for a clean topic or character change; changing settings alone keeps earlier dialogue and summaries.'],
    ['Attach / paste', 'Use +, drop files, or paste with Ctrl+V. Pending images remain removable until Send; removing an attachment keeps the original file.'],
    ['Documents', 'Attach supported text, PDF or Word files to give the model extracted text. Documents can be opened beside chat. Scans without extractable text may need another workflow.'],
    ['Rename chat', 'Use Chat options, the chat list’s menu, right-click, or F2 on a focused saved chat. Enter saves and Escape cancels.'],
    ['Export conversation', 'Save the current conversation as TXT, Markdown or JSON. Export thinking trace separately for recorded model reasoning text.'],
    ['Split chat / pin workspace', 'A second chat has its own history and model while sharing the request queue. Pin a workspace beside chat through Workspace options.'],
    ['Checklists', 'Edit checklist items in an assistant message and save to retain the change history. Other text in that message is preserved.'],
  ]],
  ['Chat options and memory', [
    ['Response length', 'Sets an output token budget: Short 256, Brief 512, Medium 1,024, Long 2,048, Very Long 4,096. Unlimited still respects runtime and context limits. Tokens are pieces of text, not words.'],
    ['Knowledge', 'Off supplies no Knowledge excerpts. All searches the available index; Selected searches only your chosen documents. At most five relevant excerpts are supplied within the context budget.'],
    ['Context estimate', 'Estimates how much of the configured context window the request uses. Reserves leave room for the reply and app instructions. Tokenizers differ; provider trimming is unknown.'],
    ['Context budget details', 'Breaks down system instructions, rolling summary, recent messages and reserves. Last request reports the processed request’s counts when available. Saved history is preserved.'],
    ['Compact memory', 'Summarizes older turns while retaining the four newest messages. The rolling summary can omit detail; the saved conversation remains available.'],
    ['Durable Memory', 'Save a lasting preference or project fact explicitly. The saved-memory control in Response influences determines whether those memories are supplied to later requests.'],
    ['Response influences', 'Inspect the app’s current prompts, roleplay, Knowledge and saved-memory inputs. Each recorded reply can show the inputs assembled for that request; this does not measure their influence on its wording.'],
    ['Thinking trace', 'Displays only reasoning text emitted by a supporting model. Models that emit no trace cannot provide one here. Export preserves the recorded history.'],
    ['On startup', 'Choose New Chat or Resume Last Chat. Preferences persist on this device; Refresh can reopen the current workspace.'],
  ]],
  ['Model settings', [
    ['Temperature', 'Controls sampling randomness. Lower values tend toward more predictable wording; higher values allow more variation and can increase mistakes.'],
    ['Top P', 'Limits token sampling to a probability mass. Lower values narrow the choices; it interacts with Temperature and Top K.'],
    ['Top K', 'Limits sampling to a number of likely tokens at each step. Lower values narrow the candidate set.'],
    ['Repeat Penalty', 'Discourages recently repeated tokens. Excessive penalties can distort wording or discourage useful repetition.'],
    ['Max Tokens', 'Adjusts the output budget and synchronizes Response length to its nearest preset. Check the Response length selection after changing it.'],
    ['System Prompt', 'Adds your general instructions to the model request. Explicit instructions remain active alongside any chosen style or roleplay fields.'],
    ['Response Style', 'Adds the selected style instructions. Default adds none. Style choices cannot guarantee that every model follows the requested format.'],
    ['Built-in profiles', 'Apply a named chat preset. Review the sampling and prompt settings after selecting one.'],
    ['Custom profiles', 'Save chat and image settings together. Changes autosave while a custom profile is selected.'],
    ['Reset Startup Preferences', 'Restores startup preferences without deleting saved chats or source files.'],
  ]],
  ['Roleplay fields', [
    ['Roleplay On / Off', 'Includes or excludes the current character fields in future model requests. Earlier character dialogue and the rolling summary remain in the conversation.'],
    ['Character / User Name', 'Name the roles used in this chat. Include names controls whether role names are included in the roleplay instructions.'],
    ['Greeting', 'Provides an opening message or setup beat for the character.'],
    ['Description', 'Describes the character’s traits, appearance, voice and boundaries.'],
    ['Scenario', 'Describes the current scene or situation.'],
    ['Example Dialogs', 'Provides sample exchanges to guide tone and behavior.'],
    ['Pre-History Instructions', 'Adds roleplay instructions to the system prompt assembled before conversation history.'],
    ['Post-History Instructions', 'Despite the field name, this implementation puts these instructions in the same system prompt before chat history.'],
    ['Character System Prompt', 'Adds instructions specific to the current character.'],
    ['Character Post-History Instruction', 'Also contributes to the combined system prompt before chat history. Use Response influences to inspect the assembled text.'],
    ['Character Note', 'Adds extra character context to the roleplay instructions.'],
    ['Ban emojis', 'Asks the model to avoid emojis; adherence depends on the model.'],
    ['Save / reset roleplay preset', 'Saves or resets these chat fields. Saving a preset does not update Character Creator. Loading a character explicitly copies its saved text; linked media is not automatically sent.'],
  ]],
  ['Tools and tool calls', [
    ['Tool registry', 'Dashboard lists application tools, requirements, effects and API schemas. Automatic tool execution is not connected to ordinary chat. Copying the catalog into a prompt does not grant the model permission or a way to call those APIs.'],
    ['Generate image', 'Uses your message text with the selected image model and Generate settings. LoRAs are optional. Send / Enter still sends a text chat.'],
    ['/Edit', 'Edits the latest image or one explicitly chosen with Use with /Edit. Review and adjust the edited copy before sending it.'],
    ['Image conversion', 'An explicit conversion request for an attached image can run the app’s local image converter. The original stays unchanged.'],
    ['/docx', 'Describe a document after /docx and Send to create a Word document through the app’s document flow.'],
    ['Canvas', 'Explicit canvas or whiteboard requests can use the app’s structured canvas editing flow. Selected objects are supplied, or the whole canvas when none are selected.'],
    ['Internet import', 'Explicitly imports one public HTTP(S) page and available images into a saved source. A new chat receives bounded extracted text with attribution; text inside images is not read automatically.'],
    ['Import limits', 'Web imports are spaced at least 10 seconds apart, limited to 30 requests per hour, and cached for 24 hours. Images count toward the limits; local and private-network addresses are refused.'],
    ['Audio transcription', 'Record or upload audio, transcribe, review the text, then explicitly insert it into your message. Transcribing alone does not send a chat message.'],
    ['Read aloud', 'Speaks a completed reply using the chosen local voice. Automatic speech is opt-in and can be stopped without removing the reply.'],
    ['Cloned chat voice', 'Audio → Voice cloning → Use this voice for chat saves a reference for local synthesis. Use one clear 6–30 second voice recording; OmniVoice and Qwen also need its exact transcript. Speech uses up to 1,500 characters after the reply finishes.'],
    ['Functions', 'Saved desktop action sequences run when you explicitly choose Run in Functions. Stop prevents subsequent steps; completed actions remain.'],
  ]],
];
