export const creativeHelp = {
  generate: [['Request and results', [
    ['Model', 'Select an installed image model before generating. Verboa uses text-to-image only, dimensions in multiples of 16, and commonly starts with 8 steps, guidance 2 and an empty negative prompt.'],
    ['Prompt / negative prompt', 'Describe desired content and what to discourage. Review these fields before submitting a request.'],
    ['Steps / Guidance / Seed shortcuts', 'Edit the visible number fields directly, or expand their presets and adjustments for the existing shortcut buttons. Random seed stays visible. Closing an expander retains the current values.'],
    ['Tab options', 'Contains Clear Generate tab, Reset defaults and Jump to Chat. Clear and Reset remain separate actions with their original behavior.'],
    ['LoRA / None', 'Choose a compatible adapter or None to use the base model alone. Add a chosen adapter’s trigger explicitly when needed.'],
    ['Generate / Stop', 'Submits the current settings to the shared queue. Stop cancels remaining work while retaining completed images.'],
    ['Batch / increments', 'Starts with current settings, then advances each enabled increment together for successive images. A blank starting seed uses 1 when Seed increments are enabled.'],
    ['Preview / Image N of M', 'Select completed results while later images continue. Click a preview to enlarge it or use Edit to open the image editor.'],
    ['Output folder / Use library', 'Selects where new export copies are saved. Generated results also remain available in the Gallery.'],
    ['Analyze & Iterate', 'Uses an installed chat model to propose revised prompts. Review and apply suggestions explicitly; model, LoRA, seed and generation settings stay selected.'],
    ['Read reference details', 'Uses an installed vision model to produce editable appearance, style, composition and lighting descriptions. Reading saves a local analysis workflow; prompts change only when you apply details.'],
    ['Prompt phrase buttons', 'Click a saved phrase to copy it, then paste into a prompt. Custom buttons can be searched and edited.'],
    ['Save image prompts', 'Saves the positive and negative prompt pair as a separate named entry. Name each variation so you can find it again.'],
  ]]],
  'image-editor': [['Image and history', [
    ['Open / drop image', 'Loads a PNG, JPEG or WebP for local editing. The source file remains intact.'],
    ['Fit / 100%', 'Fit uses a reduced preview. Use 100% to judge actual pixels; export keeps the full resolution.'],
    ['Color adjustments', 'Changes exposure, contrast, color balance and other offered controls for the current editing pass.'],
    ['Rotate', 'Rotates the image in 90-degree steps and participates in edit history.'],
    ['Lock / Unlock / Reset', 'Locks the current pass, up to 16 stages. Unlock revises a previous pass; Reset clears only the current pass. Undo can restore a removed sample.'],
    ['Remove blur / refinement', 'Sharpens existing detail without resizing or smoothing. It cannot reconstruct missing detail or reverse heavy blur. Compare at 100%.'],
    ['Export PNG', 'Creates a full-resolution 8-bit sRGB copy. Animation and original metadata are not retained.'],
  ]], ['Reference colors and Magic Edit', [
    ['Reference color samples', 'Click the reference to sample a color, then apply it to an enclosed area or brush spot. Each sample keeps separate areas; changes affect the current pass.'],
    ['Apply color / fill / brush', 'When armed, click the edited image to apply the chosen color. Fill follows connected similar colors; brush spots control the area directly. Use Undo, a brush spot or lower tolerance if outlines have gaps.'],
    ['Magic Edit', 'Describe the result and paint a specific area to change. Outside the selected mask is preserved in the accepted image. Review a generated candidate before accepting.'],
    ['Reference guidance', 'An installed vision model converts references to editable text. Generation uses that text and the current image; it does not condition directly on reference pixels.'],
    ['Skin-tone request', 'Opens Magic Edit with your current reference assigned to skin tone. Review guidance and paint the relevant area before generating.'],
    ['Strength / working canvas', 'Lower strength stays closer to the source. Small images can use a larger working copy; accepted images keep their original proportions and dimensions.'],
    ['Runtime', 'Magic Edit needs an installed compatible SDXL model and CUDA runtime. It does not download models or dependencies.'],
  ]]],
  workflows: [['Processing workflows', [
    ['New workflow / assets', 'Creates a saved draft with owned image copies. Upload sources, masks and control maps, then assign them to stages.'],
    ['Workflow options', 'Contains provider refresh, Reload saved and Delete workflow. Save and Branch next scene stay visible; deleting still opens its review dialog.'],
    ['Stages / order', 'Runs top to bottom. Previous-image links follow the order; choose a specific image or stage for a fixed source.'],
    ['Operation / adapter', 'Installed SDXL supports image-to-image and masked edits; Ollama vision describes images; Lanczos resizes on CPU. A stage without an installed adapter cannot run.'],
    ['Prompt / settings', 'SDXL stages use prompts and generation settings. Describe / OCR reports content separately; Lanczos resizes without a prompt.'],
    ['References', 'Assign owned assets to the available roles. ControlNet and multi-reference adapters are not installed in this implementation.'],
    ['Validate / Prepare snapshot', 'Saves pending edits and checks configuration. Prepare stores a read-only input snapshot without running generation.'],
    ['Run / Stop workflow', 'Uses the shared Prompt Queue. Stopping waits for the provider to exit; completed results remain available.'],
    ['Run history', 'Each run keeps its original input snapshot. Review saved outputs after an interrupted run before starting again.'],
    ['Keep as reference / Branch next scene', 'Explicitly promotes a result for reuse. Branching copies owned references; choose a kept result as the new source.'],
    ['Export / stitched reference', 'Keeps stage order. Stitches fit images without cropping and can scale to reference limits; ZIP retains original outputs. Completed images also appear in Gallery → Workflow Images.'],
  ]], ['Iterative scenes', [
    ['Plan the next frame', 'Choose an installed Ollama model and describe your intention. Propose visual actions shows concrete before/after changes and uncertainties without modifying the scene. Select actions and Apply reviewed actions, then generate separately. Completed proposals are saved; edited scenes require a new plan. Stop planning cancels local inference.'],
    ['New scene / starting image', 'Saves character, camera, lighting, pose and object state. Generate the first frame from text or attach an image.'],
    ['Scene options', 'Contains Reload saved and Refresh models and characters. Reload still asks before discarding unsaved changes.'],
    ['State fields', 'Edits save automatically. Change the fields for the next frame; other details carry forward. Natural-language action planning is not implemented.'],
    ['Character references', 'Copies the profile’s chosen references for review. This adapter conditions on the previous frame and text; it does not use a face adapter.'],
    ['Object state / JSON', 'Retain object identity while changing placement or contact. Applying edited JSON validates before replacing saved state.'],
    ['Denoising / Generate', 'Denoising applies when a source is selected. Generation needs the local SDXL CUDA runtime and supports up to 1024 × 1024. Review identity, hands and objects after each frame.'],
    ['Choose frame / regenerate / branch', 'Restores the frame’s state, restores original inputs for another run, or makes a separate branch. Earlier frames remain saved.'],
  ]]],
  lora: [['Preparation workflow', [
    ['New project', 'Starts an editable adapter project. Choose the image base model, training goal and analysis model before running.'],
    ['Analyze & Train', 'Queues analysis followed by training. It fills blank or automatic captions and preserves edited captions. Use Analyze current dataset first to review suggestions separately.'],
    ['CPU assistance / preparation budget', 'Controls preprocessing workers and extra RAM. Auto uses up to 256 MiB; Light up to 64 MiB, reduced when memory is low. The budget excludes model memory.'],
    ['Timing report', 'Separates preparation waits, vision analysis and training time. Parallel worker times can overlap.'],
  ]]],
  faces: [['Datasets and detection', [
    ['Create dataset', 'Creates a working collection for extracted faces.'],
    ['Import files / folders / library', 'Adds source images or video inputs using the offered controls. Large selections are processed in batches and originals stay unchanged.'],
    ['Detect faces', 'Finds every detected face, including smaller faces. Install the local face models if readiness reports them missing.'],
    ['Crop / padding / output size', 'Keeps square crops within source bounds. Output sizes pad rather than stretch; Re-crop uses stored detections without scanning again.'],
    ['Accept / reject', 'Curates which detections belong in the dataset. Review mistaken or low-quality detections before export.'],
    ['Remove from dataset', 'Removes the chosen dataset item through its own card control. It preserves the original source image.'],
    ['Export / save as character', 'Exports curated dataset copies or makes a character with accepted face references.'],
    ['Tie to character', 'Links this dataset to a profile without moving, copying or training the linked source.'],
  ]]],
  characters: [['Profile', [
    ['Related tools / Character options', 'Related tools opens Faces, Audio or Packager. Character options contains Rename, Recalculate and Delete; deleting still requires confirmation.'],
    ['Name / biography / notes', 'Defines the saved character profile. A character can exist without face images.'],
    ['References / resources', 'Links existing faces, parts, LoRAs, audio, images, video, documents and other resources. Existing resources remain in their workspaces.'],
    ['Upload files / Saved file', 'Creates an app copy up to 128 MiB; images are limited to 24 megapixels. Saved file links a previous upload again. Video playback depends on the codec.'],
    ['Unlink', 'Removes the profile link while retaining the source and saved file copy.'],
    ['Load into chat', 'Explicitly copies the character’s saved text into roleplay fields. Browsing a profile alone does not change chat or automatically attach its media.'],
  ]], ['Face references', [
    ['Representative face', 'Chooses a real accepted crop closest to the group centroid. It is not an averaged or synthesized face.'],
    ['Primary / additional reference', 'Keeps your explicit chosen references separate from the computed representative.'],
    ['Similarity / coherence / spread', 'Describes comparisons within the saved face group. These values do not establish real-world identity.'],
    ['Linked datasets', 'Opens the profile’s face, part or training resources in their own workspaces. Missing resources retain their links for review.'],
  ]]],
  'character-parts': [['Sources and focus', [
    ['New dataset / import', 'Adds owned source copies from files, folders or the available image library. Hidden and locked library images are excluded.'],
    ['Draw region', 'Drag a rectangle or set its edges numerically. Crops keep original resolution and the full source remains available.'],
    ['Region name / side / view', 'Labels the area, anatomical side and viewing angle. Left and right refer to the character.'],
    ['Use as focus', 'Uses a named crop as a temporary visual reference for suggestions in other images. Include enough surrounding anatomy to assess how the region joins the character.'],
    ['Suggest / vision model', 'Uses an installed local vision model to propose regions. Compare notes and source context before accepting; old-reference analysis is marked.'],
  ]], ['Curation and export', [
    ['Accept / reject', 'Reviews full images and crops independently. Rejected selections remain recoverable. Check small digits, occlusion and left/right labels.'],
    ['Remove', 'Hides items from the working view without changing saved datasets or earlier exports.'],
    ['Full image / Crop', 'Sets which representation each item contributes to export.'],
    ['Export media → selected / approved / rejected', 'Creates ZIP copies with captions and a manifest. Selected uses checked items; approved and rejected span the entire dataset across filters.'],
    ['Tie to character', 'Optionally links the dataset to a character’s references without copying, moving or training source files.'],
  ]]],
};
