const sourceControls = kind => [
  ['File actions / drop file', `Open reads a local ${kind} file up to 2 MB into this viewer. Copy source is also in File actions; Save source stays on the toolbar. Source remains available while switching tabs.`],
  ['Preview / Edit source', 'HTML and CSS toggle between a sandboxed preview and editable source. Copy and Save use the current source text; the source file is not overwritten automatically. JavaScript remains a text editor.'],
  ['Draft lifetime', 'Source remains while switching tabs. Refreshing or closing the app clears unsaved viewer content.'],
];

export const fileToolHelp = {
  shortcuts: [['Reference and personal entries', [
    ['Application folders', 'Open a folder to read its entries. New application folder creates an empty reference folder; it does not create a folder on disk.'],
    ['Search / filters', 'Search keys, actions and behavior, then filter by application, category or type. Matching folders open while filtering.'],
    ['New entry', 'Choose an existing application or type a new one to create its folder. Personal entries are stored locally on this device.'],
    ['Icon', 'Choose PNG, JPG, WebP or ICO up to 128 KB, or restore the automatic icon. Application folders and custom icons are saved in local browser storage.'],
    ['Reference options → Save / Copy', 'Exports every matching reference entry, including entries in collapsed folders.'],
    ['Built-in Word reference', 'Covers Windows desktop with an English / US keyboard. Source links and checked dates identify built-in entries. Mac, web and custom bindings can differ.'],
    ['Key combinations', 'Press keys joined by + together in the application being described. Reading a reference does not execute it.'],
  ]]],
  browser: [['Browsing', [
    ['Address / Go', 'Enter a public page address. F6 or Ctrl+L focuses the address bar. Local and private-network pages are blocked.'],
    ['Back / Forward / Reload', 'Navigate the current page’s history or request it again.'],
    ['Close page', 'Closes the page while retaining this app’s website login data. The app’s persistent browser profile is separate from Chrome.'],
    ['Pop-up requests', 'Review a requested extra window before opening it. Approved login windows use the same app browser profile. Some providers restrict embedded sign-in.'],
    ['Inspect page', 'After confirmation, lists rendered HTML, inline code and up to 200 loaded source resources. Individual source reads are limited to 2 MB; server-side project code is not available.'],
    ['Open source in viewer', 'Sends a chosen HTML, CSS or JavaScript source to its local viewer for inspection, copying or saving.'],
    ['Screenshot', 'Requires confirmation because a signed-in page can contain private information.'],
  ]], ['Browser privacy', [
    ['Profile location', 'Shows where this app stores its own persistent browser data.'],
    ['Clear cookies / cache / site data', 'Clears only the selected browser data after confirmation. Clearing cookies or site data can sign you out.'],
    ['Page permissions', 'Camera, microphone, location, notifications and clipboard requests need approval for the current page. Device access, screen sharing and local-network access are blocked.'],
  ]]],
  'local-files': [['Open and inspect', [
    ['Open file', 'Uses the desktop file picker to open supported DOCX, SQLite, video or 3D files. Processing begins only through the controls you choose.'],
    ['Close file', 'Releases the selected file and its temporary processing data. Save edits or outputs first.'],
    ['Word text editing', 'Edits existing paragraphs and direct bold/italic formatting. Page layout, inherited styles and table restructuring are outside this text editor.'],
    ['Save / Save as', 'Saves Word edits through the file controls. Review any protected-content acknowledgement before saving a document with unsupported features.'],
    ['SQLite tables / query', 'Reads a SQLite snapshot with bounded SELECT queries and up to 100 displayed rows. Close and reopen to see external changes. Database content is not sent to AI automatically.'],
    ['3D files', 'Opens the shared 3D editor. Save a project before closing the Local Files viewer; Open model reopens the selected file after graphics are released.'],
  ]], ['Video tools', [
    ['Inspect metadata', 'Reads duration, dimensions, frame rate and other available file metadata.'],
    ['Quick / Balanced / Detailed / Custom', 'Choose the sampling coverage: up to 3, 6 or 12 analyzed moments. Events between sampled moments may be missed.'],
    ['Vision model / focus', 'Select an installed vision-capable model and optionally describe what to examine.'],
    ['Analyze video', 'Automatically samples moments across the clip and creates a summary with timestamped observations. Extracting frames first is optional. A single opening thumbnail is only a preview.'],
    ['Analyze frame selection', 'Checked frames become the candidate set for analysis, up to the selected workload’s frame limit. Clear the selection to sample automatically across the video.'],
    ['Extract frames', 'Produces sampled frame images without content analysis.'],
    ['Add video & analysis to REVIEW', 'Registers this open clip and its analysis in the shared REVIEW catalog. Review, tag, organize or recover it there; registration does not start AI analysis.'],
    ['Transcribe audio', 'Uses installed Audio models on CPU for up to two hours. Temporary audio is removed when the file closes; Stop waits for an active transcription call.'],
    ['Save results', 'Save the prepared output before closing the file or refreshing the app.'],
  ]]],
  'document-editor': [['Files and editing', [
    ['New / Open', 'Start a blank working draft or import a Word document. Replacing a draft asks you to keep or discard unsaved work.'],
    ['Export DOCX', 'Creates a Word-compatible copy of the working document. Microsoft Word is not required.'],
    ['Recovery copies', 'Open a locally saved recovery copy or remove it explicitly. Removing a recovery copy leaves exported DOCX files intact.'],
    ['Home ribbon', 'Sets font, size, emphasis, text color, highlight, alignment, paragraph spacing, indentation, headings and lists. Undo / Redo reverses draft edits.'],
    ['Find / Replace', 'Finds text in the current document and replaces the selected match or matches through the provided controls.'],
    ['Tables', 'Click inside a table for Table Layout and Table Design. Select a cell range to merge/split, size columns, choose shading/borders, and repeat the first row in exported DOCX.'],
    ['Styles', 'Apply or create named paragraph styles. Modifying a style updates its paragraphs; Reset to style clears direct overrides. Style changes support Undo.'],
    ['Contents / bookmarks', 'References creates live heading-based contents and manages point bookmarks. Link to a heading or bookmark and check missing destinations.'],
    ['Footnotes / endnotes', 'Insert a note, click its number or Show notes, and edit its formatted body. Numbering and conversion update automatically and support Undo.'],
    ['Citations / bibliography', 'References → Manage sources adds books, journal articles and websites. Insert/edit citations with locators, choose basic APA author–date or Numbered, and insert a live bibliography. Sources travel with DOCX and reusable JSON lists.'],
    ['Pictures / Picture Format', 'Inserts local images and edits width, proportional sizing or alternative text. Remove deletes the image from the draft.'],
    ['Links / symbols / page breaks', 'Insert a web or mail link, symbol or page break. Links support HTTP, HTTPS and mailto addresses; selected text becomes the link.'],
  ]], ['Layout, view and review', [
    ['Page layout', 'Choose Letter, A4 or Legal, orientation and margins. The page-shaped editing surface approximates paper layout; automatic pagination and exact page counts are not implemented.'],
    ['Zoom / ruler / paragraph marks', 'Adjust the editor view without changing document text. Heading navigation follows the heading styles in your draft.'],
    ['Word count', 'Counts whitespace-separated words. Counts can differ from Word.'],
    ['Spelling / read only', 'Spelling uses available browser dictionaries. Read only prevents draft editing.'],
    ['Supported scope', 'Text, named styles, merged tables, headers/footers, page-number fields, contents, bookmarks, notes and local citations are supported. Precise pagination/printing, multiple sections, columns and full citation-style coverage are upcoming pieces.'],
    ['Planned review features', 'Comments, tracked changes, comparison, grammar, dictation, read aloud, collaboration and advanced picture wrapping/effects are not implemented.'],
  ]], ['Planned ribbon features', [
    ['Diagram', 'Shapes, connectors, SmartArt and diagram arrangement are not implemented.'],
    ['Draw', 'Pens, ink, lasso selection, drawing canvas and ink-to-math are not implemented.'],
    ['Outlining', 'Outline restructuring and promote/demote are not implemented. Heading navigation is available under View.'],
    ['Design', 'Themes, style sets, page colors, watermarks and page borders are not implemented.'],
    ['Further references', 'Captions, indexes, authorities, automatic cross-reference fields and page references are upcoming pieces.'],
    ['Mailings', 'Mail merge, recipients, envelopes and labels are not implemented.'],
    ['Developer', 'Content controls, XML mapping, templates and document protection are not implemented. VBA, COM and Word add-ins are outside this editor.'],
  ]]],
  'js-viewer': [['Source controls', sourceControls('JavaScript')], ['Inspection', [
    ['JavaScript source', 'Displays source as text. It is not executed in this viewer. Use Browser → Inspect page to bring in a loaded page resource.'],
  ]]],
  'html-viewer': [['Source controls', sourceControls('HTML')], ['Preview', [
    ['HTML preview', 'Renders the current HTML in an isolated preview with scripts and remote resources disabled.'],
  ]]],
  'css-viewer': [['Source controls', sourceControls('CSS')], ['Preview', [
    ['HTML to style', 'Enter sample markup to preview your CSS. The preview isolates the source and blocks scripts and remote resources.'],
  ]]],
  'styling-library': [['Browse examples', [
    ['Find an example / Categories', 'Search names, descriptions and keywords, or choose Buttons, Forms, Layouts, Effects, Typography or Animations. These built-in examples work offline.'],
    ['Preview theme', 'Switch every preview between dark and light palettes. The application theme stays as selected in Workspace options.'],
    ['Pause / Play animations', 'Pause keyframe animations in the previews. Device reduced-motion preferences are respected, and previews are unloaded while this tab is hidden.'],
    ['View code', 'Open a larger live preview with its HTML and CSS source. Preview buttons demonstrate their appearance; form controls and hover states are interactive.'],
  ]], ['Use an example', [
    ['HTML / CSS', 'HTML defines the structure; CSS defines its appearance. Choose either source tab. CSS includes the palette and base styles used by the standalone example.'],
    ['Copy source / Copy full example', 'Copy the selected language or a complete HTML document with embedded CSS. Copying leaves your current chat and files in place.'],
    ['Save HTML example', 'Download one self-contained HTML file to open in your browser or HTML Viewer. Examples include a reduced-motion rule and require no external fonts or libraries.'],
    ['Edit in CSS / Styling', 'Open the selected example’s CSS and matching HTML in the existing CSS viewer. Change the source and click Preview to try your variation.'],
  ]]],
  markdown: [['Text and preview', [
    ['Plain Text', 'Paste or edit the Markdown source.'],
    ['Show Markdown', 'Renders headings, lists, code blocks and other supported Markdown from your current text.'],
    ['Copy / Save', 'Copies or downloads the current text using the available controls.'],
    ['Draft lifetime', 'Text stays while switching workspaces. Refreshing or closing the app clears this draft.'],
  ]]],
  spreadsheets: [['CSV controls', [
    ['Open / drop CSV', 'Reads a CSV up to 10 MB. Choose comma, semicolon or tab delimiters as needed. Formulas remain text.'],
    ['Filter', 'Narrows visible rows to matching data.'],
    ['Column heading', 'Sorts the table by that column.'],
    ['Row selection', 'Select rows to prepare a smaller context for chat.'],
    ['Columns to include in chat', 'Choose the columns included by the chat handoff.'],
    ['Use file / filtered / selected in chat', 'Stages the chosen data for chat, up to 14,000 characters. Any sampling is explicitly stated.'],
  ]]],
  canvas: [['Drawing tools', [
    ['Select / Free-form select', 'Drag a rectangular or free-form pixel selection, move it, resize its corner handles, or use Edit to copy, cut, crop, invert, rotate or flip it.'],
    ['Brushes / Shapes / Text', 'Draw on the active visible layer. Shift constrains shapes and lines; right-click uses Color 2. Apply text commits its editable draft.'],
    ['Color / Size / Opacity', 'Choose two colors, a brush style, stroke width and opacity. Fill tolerance controls matching pixels; transparent selections use Color 2.'],
    ['View / Layers', 'Show rulers, grid, thumbnail or layers. Layers can be added, duplicated, named, hidden, reordered and merged. Ctrl-wheel zooms; Fit shows the artwork.'],
    ['Undo / Redo', 'Steps backward or forward through canvas edits.'],
    ['Use in chat', 'Stages a removable PNG attachment in chat. Review the attachment and message before Send. Raster Paint does not accept the previous object-based chat edits.'],
    ['File / Save project', 'Open images, import layers, save PNG/JPEG/WebP/BMP, or save an editable .lawpaint project. Drafts are saved locally in IndexedDB. Previous Canvas artwork is imported when there is no Paint draft; its original record is preserved.'],
    ['Resize / Properties / Print', 'Resize or skew artwork, adjust canvas dimensions/background, or print the artwork. JPEG and BMP use a white background. Save a project before replacing work to preserve its layers.'],
  ]]],
  converter: [['Image conversion', [
    ['Choose / drop images', 'Accepts still images up to 100 MB and 24 megapixels each. File size and pixel dimensions are separate limits. Original files are preserved.'],
    ['Output format', 'Choose PNG, JPG, WebP, BMP, TIFF or ICO. JPG and BMP replace transparency with white.'],
    ['ICO size', 'Choose a square size from 16 to 256 pixels. ICO preserves supported transparency.'],
    ['Convert / Save', 'Creates and saves converted copies. Chat can also convert an attached image through an explicit request.'],
  ]]],
  packager: [['Build a ZIP', [
    ['Add files / folders', 'Accepts any file type. Add more with another selection or drop. Folder drops retain empty folders; the folder picker includes files only.'],
    ['File list / Remove', 'Review package paths and remove unwanted entries before creating the archive. Source files remain on disk.'],
    ['Package name / compression', 'Sets the archive name and compression option. Matching filenames receive numbered names; folder structure is retained.'],
    ['Save ZIP', 'Creates an archive with up to 1,000 items and 512 MiB. Existing originals are not moved.'],
  ]]],
  'hash-auditor': [['Audit controls', [
    ['Folders / drive roots', 'Enter one absolute path per line or choose folders. Nothing is scanned until Start audit.'],
    ['Start audit', 'Reads regular files in full to record SHA-256 hashes and filesystem metadata. Links, cloud placeholders, NVIDIA paths and the audit database are skipped.'],
    ['Stop', 'Cancels unfinished scanning while keeping recorded observations. Audits continue across tab changes and refreshes; quitting interrupts them.'],
    ['Hash matches', 'Compares recorded hashes across all audits. Dates show when paths were read; rescan to refresh observations. Hard links are labeled as paths to one physical file.'],
    ['Metadata candidates', 'Compares chosen filesystem fields exactly. Names are case-insensitive and timestamps use nanoseconds. Metadata matches do not prove identical bytes; embedded EXIF and document properties are not compared.'],
    ['History / coverage', 'Shows errors, skips and completed audits. A completed scan marks unseen paths unavailable; cancellation retains observations for paths it never reached.'],
    ['Export', 'Includes all matching rows, beyond the currently displayed page. The auditor does not delete files.'],
  ]]],
  'folder-review': [['Review controls', [
    ['Folder / text model', 'Select the folder and a local text model. File contents go to the configured Ollama service; source files are not edited or executed.'],
    ['Start Folder Review', 'Reviews files individually and combines the findings into a saved report.'],
    ['Batch size and coverage limits', 'Divides long text into contiguous batches and automatically reduces their size to fit the model context. All readable text within the file limits is included. Entry limits, skips and unreadable PDF pages are recorded in the report. PDFs are inspected up to 500 pages.'],
    ['Compaction and memory', 'Compacts batch findings into per-file analyses and a folder overview, while retaining the full per-file report. Releases image-model GPU memory before inference, unloads other Ollama models, and verifies release of the review model after completion. Progress shows batch, compaction and memory preparation counts.'],
    ['File coverage', 'Python receives static source analysis; other supported text gets summaries. Word contributes paragraphs and tables; PDFs contribute native text only. Images contribute metadata, not pixels.'],
    ['Skipped files', 'Credential files, links, cloud placeholders, dependency/tooling folders and report storage are excluded. Unsupported binaries receive filesystem metadata only.'],
    ['Stop and recovery', 'Keeps completed file and source-batch findings, including when later compaction fails. Cancellation waits for model preparation and CPU offloading to exit. A restart marks active work interrupted and rebuilds reports from saved findings without restarting inference. Invalid saved data is flagged.'],
    ['Provider fallback', 'Temporary connection/HTTP failures get one retry with the same model and complete request. Invalid, unfinished, empty or oversized responses remain explicit failures. The workspace shows retry counts.'],
    ['Report / Copy / Save Markdown', 'Review per-file references, hashes and text coverage before using a model summary. Reports can contain content from your chosen folder.'],
  ]]],
};
