const sourceControls = kind => [
  ['Open / drop file', `Reads a local ${kind} file up to 2 MB into this viewer. Source remains available while switching tabs.`],
  ['Source', 'Edit or inspect the source text. Copy and Save use the current text; the source file is not overwritten automatically.'],
  ['Draft lifetime', 'Source remains while switching tabs. Refreshing or closing the app clears unsaved viewer content.'],
];

export const fileToolHelp = {
  shortcuts: [['Reference and personal entries', [
    ['Application folders', 'Open a folder to read its entries. New application folder creates an empty reference folder; it does not create a folder on disk.'],
    ['Search / filters', 'Search keys, actions and behavior, then filter by application, category or type. Matching folders open while filtering.'],
    ['New entry', 'Choose an existing application or type a new one to create its folder. Personal entries are stored locally on this device.'],
    ['Icon', 'Choose PNG, JPG, WebP or ICO up to 128 KB, or restore the automatic icon. Application folders and custom icons are saved in local browser storage.'],
    ['Save / Copy', 'Exports every matching reference entry, including entries in collapsed folders.'],
    ['Built-in Word reference', 'Covers Windows desktop with an English / US keyboard. Source links and checked dates identify built-in entries. Mac, web and custom bindings can differ.'],
    ['Key combinations', 'Press keys joined by + together in the application being described. Reading a reference does not execute it.'],
  ]]],
  browser: [['Browsing', [
    ['Address / Go', 'Enter a public page address. F6 or Ctrl+L focuses the address bar. Local and private-network pages are blocked.'],
    ['Back / Forward / Reload', 'Navigate the current page’s history or request it again.'],
    ['Close page', 'Closes the page while retaining this app’s website login data. The app’s persistent browser profile is separate from Chrome.'],
    ['Pop-up requests', 'Review a requested extra window before opening it. Approved login windows use the same app browser profile. Some providers restrict embedded sign-in.'],
    ['Inspect page', 'After confirmation, lists rendered HTML, inline code and up to 200 loaded source resources. Individual source reads are limited to 2 MB; server-side project code is not available.'],
    ['Open source in viewer', 'Sends a chosen HTML, CSS or JavaScript source to its local viewer for inspection, copying or saving.'],
    ['Screenshot', 'Requires confirmation because a signed-in page can contain private information.'],
  ]], ['Browser privacy', [
    ['Profile location', 'Shows where this app stores its own persistent browser data.'],
    ['Clear cookies / cache / site data', 'Clears only the selected browser data after confirmation. Clearing cookies or site data can sign you out.'],
    ['Page permissions', 'Camera, microphone, location, notifications and clipboard requests need approval for the current page. Device access, screen sharing and local-network access are blocked.'],
  ]]],
  'local-files': [['Open and inspect', [
    ['Open file', 'Uses the desktop file picker to open supported DOCX, SQLite, video or 3D files. Processing begins only through the controls you choose.'],
    ['Close file', 'Releases the selected file and its temporary processing data. Save edits or outputs first.'],
    ['Word text editing', 'Edits existing paragraphs and direct bold/italic formatting. Page layout, inherited styles and table restructuring are outside this text editor.'],
    ['Save / Save as', 'Saves Word edits through the file controls. Review any protected-content acknowledgement before saving a document with unsupported features.'],
    ['SQLite tables / query', 'Reads a SQLite snapshot with bounded SELECT queries and up to 100 displayed rows. Close and reopen to see external changes. Database content is not sent to AI automatically.'],
    ['3D files', 'Opens the shared 3D editor. Save a project before closing the Local Files viewer; Open model reopens the selected file after graphics are released.'],
  ]], ['Video tools', [
    ['Inspect metadata', 'Reads duration, dimensions, frame rate and other available file metadata.'],
    ['Quick / Balanced / Detailed / Custom', 'Choose the sampling coverage: up to 3, 6 or 12 analyzed moments. Events between sampled moments may be missed.'],
    ['Vision model / focus', 'Select an installed vision-capable model and optionally describe what to examine.'],
    ['Analyze video', 'Automatically samples moments across the clip and creates a summary with timestamped observations. Extracting frames first is optional. A single opening thumbnail is only a preview.'],
    ['Analyze frame selection', 'Checked frames become the candidate set for analysis, up to the selected workload’s frame limit. Clear the selection to sample automatically across the video.'],
    ['Extract frames', 'Produces sampled frame images without content analysis.'],
    ['Transcribe audio', 'Uses installed Audio models on CPU for up to two hours. Temporary audio is removed when the file closes; Stop waits for an active transcription call.'],
    ['Save results', 'Save the prepared output before closing the file or refreshing the app.'],
  ]]],
  'document-editor': [['Files and editing', [
    ['New / Open', 'Start a blank working draft or import a Word document. Replacing a draft asks you to keep or discard unsaved work.'],
    ['Export DOCX', 'Creates a Word-compatible copy of the working document. Microsoft Word is not required.'],
    ['Recovery copies', 'Open a locally saved recovery copy or remove it explicitly. Removing a recovery copy leaves exported DOCX files intact.'],
    ['Home ribbon', 'Sets font, size, emphasis, text color, highlight, alignment, paragraph spacing, indentation, headings and lists. Undo / Redo reverses draft edits.'],
    ['Find / Replace', 'Finds text in the current document and replaces the selected match or matches through the provided controls.'],
    ['Insert table', 'Creates a basic table. With the cursor in a table, use the Insert ribbon to add or remove rows and columns.'],
    ['Pictures / Picture Format', 'Inserts local images and edits width, proportional sizing or alternative text. Remove deletes the image from the draft.'],
    ['Links / symbols / page breaks', 'Insert a web or mail link, symbol or page break. Links support HTTP, HTTPS and mailto addresses; selected text becomes the link.'],
  ]], ['Layout, view and review', [
    ['Page layout', 'Choose Letter, A4 or Legal, orientation and margins. The page-shaped editing surface approximates paper layout; automatic pagination and exact page counts are not implemented.'],
    ['Zoom / ruler / paragraph marks', 'Adjust the editor view without changing document text. Heading navigation follows the heading styles in your draft.'],
    ['Word count', 'Counts whitespace-separated words. Counts can differ from Word.'],
    ['Spelling / read only', 'Spelling uses available browser dictionaries. Read only prevents draft editing.'],
    ['Supported scope', 'Common text editing and DOCX creation are supported. Print/PDF output, exact style inheritance, merged-cell editing, headers, footers, sections and columns are unfinished.'],
    ['Planned review features', 'Comments, tracked changes, comparison, grammar, dictation, read aloud, collaboration and advanced picture wrapping/effects are not implemented.'],
  ]], ['Planned ribbon features', [
    ['Diagram', 'Shapes, connectors, SmartArt and diagram arrangement are not implemented.'],
    ['Draw', 'Pens, ink, lasso selection, drawing canvas and ink-to-math are not implemented.'],
    ['Outlining', 'Outline restructuring and promote/demote are not implemented. Heading navigation is available under View.'],
    ['Design', 'Themes, style sets, page colors, watermarks and page borders are not implemented.'],
    ['References', 'Tables of contents, notes, citations, bibliographies, captions, indexes and cross-references are not implemented.'],
    ['Mailings', 'Mail merge, recipients, envelopes and labels are not implemented.'],
    ['Developer', 'Content controls, XML mapping, templates and document protection are not implemented. VBA, COM and Word add-ins are outside this editor.'],
  ]]],
  'js-viewer': [['Source controls', sourceControls('JavaScript')], ['Inspection', [
    ['JavaScript source', 'Displays source as text. It is not executed in this viewer. Use Browser → Inspect page to bring in a loaded page resource.'],
  ]]],
  'html-viewer': [['Source controls', sourceControls('HTML')], ['Preview', [
    ['HTML preview', 'Renders the current HTML in an isolated preview with scripts and remote resources disabled.'],
  ]]],
  'css-viewer': [['Source controls', sourceControls('CSS')], ['Preview', [
    ['HTML to style', 'Enter sample markup to preview your CSS. The preview isolates the source and blocks scripts and remote resources.'],
  ]]],
  markdown: [['Text and preview', [
    ['Plain Text', 'Paste or edit the Markdown source.'],
    ['Show Markdown', 'Renders headings, lists, code blocks and other supported Markdown from your current text.'],
    ['Copy / Save', 'Copies or downloads the current text using the available controls.'],
    ['Draft lifetime', 'Text stays while switching workspaces. Refreshing or closing the app clears this draft.'],
  ]]],
  spreadsheets: [['CSV controls', [
    ['Open / drop CSV', 'Reads a CSV up to 10 MB. Choose comma, semicolon or tab delimiters as needed. Formulas remain text.'],
    ['Filter', 'Narrows visible rows to matching data.'],
    ['Column heading', 'Sorts the table by that column.'],
    ['Row selection', 'Select rows to prepare a smaller context for chat.'],
    ['Columns to include in chat', 'Choose the columns included by the chat handoff.'],
    ['Use file / filtered / selected in chat', 'Stages the chosen data for chat, up to 14,000 characters. Any sampling is explicitly stated.'],
  ]]],
  canvas: [['Drawing tools', [
    ['Select', 'Click an object to select it; Shift-click selects several. Drag selected objects to move them.'],
    ['Text / Rectangle / Ellipse', 'Adds the chosen object to the 1200 × 800 artwork.'],
    ['Line / Arrow / Draw', 'Adds lines, arrows or freehand strokes.'],
    ['Color', 'Changes the selected drawing color or applicable selected object styling.'],
    ['Undo / Redo', 'Steps backward or forward through canvas edits.'],
    ['Use in chat', 'Supplies selected objects, or the whole canvas when none are selected. Explicit canvas requests can create or edit structured objects.'],
    ['Copy Canvas', 'Copies the artwork area without the surrounding controls. Canvas state is saved on this device.'],
  ]]],
  converter: [['Image conversion', [
    ['Choose / drop images', 'Accepts still images up to 20 MB and 24 megapixels each. Original files are preserved.'],
    ['Output format', 'Choose PNG, JPG, WebP, BMP, TIFF or ICO. JPG and BMP replace transparency with white.'],
    ['ICO size', 'Choose a square size from 16 to 256 pixels. ICO preserves supported transparency.'],
    ['Convert / Save', 'Creates and saves converted copies. Chat can also convert an attached image through an explicit request.'],
  ]]],
  packager: [['Build a ZIP', [
    ['Add files / folders', 'Accepts any file type. Add more with another selection or drop. Folder drops retain empty folders; the folder picker includes files only.'],
    ['File list / Remove', 'Review package paths and remove unwanted entries before creating the archive. Source files remain on disk.'],
    ['Package name / compression', 'Sets the archive name and compression option. Matching filenames receive numbered names; folder structure is retained.'],
    ['Save ZIP', 'Creates an archive with up to 1,000 items and 512 MiB. Existing originals are not moved.'],
  ]]],
  'hash-auditor': [['Audit controls', [
    ['Folders / drive roots', 'Enter one absolute path per line or choose folders. Nothing is scanned until Start audit.'],
    ['Start audit', 'Reads regular files in full to record SHA-256 hashes and filesystem metadata. Links, cloud placeholders, NVIDIA paths and the audit database are skipped.'],
    ['Stop', 'Cancels unfinished scanning while keeping recorded observations. Audits continue across tab changes and refreshes; quitting interrupts them.'],
    ['Hash matches', 'Compares recorded hashes across all audits. Dates show when paths were read; rescan to refresh observations. Hard links are labeled as paths to one physical file.'],
    ['Metadata candidates', 'Compares chosen filesystem fields exactly. Names are case-insensitive and timestamps use nanoseconds. Metadata matches do not prove identical bytes; embedded EXIF and document properties are not compared.'],
    ['History / coverage', 'Shows errors, skips and completed audits. A completed scan marks unseen paths unavailable; cancellation retains observations for paths it never reached.'],
    ['Export', 'Includes all matching rows, beyond the currently displayed page. The auditor does not delete files.'],
  ]]],
  'folder-review': [['Review controls', [
    ['Folder / text model', 'Select the folder and a local text model. File contents go to the configured Ollama service; source files are not edited or executed.'],
    ['Start Folder Review', 'Reviews files individually and combines the findings into a saved report.'],
    ['Batch size and coverage limits', 'Divides long text into contiguous batches. Entry limits, skips and unreadable PDF pages are recorded in the report. PDFs are inspected up to 500 pages.'],
    ['File coverage', 'Python receives static source analysis; other supported text gets summaries. Word contributes paragraphs and tables; PDFs contribute native text only. Images contribute metadata, not pixels.'],
    ['Skipped files', 'Credential files, links, cloud placeholders, dependency/tooling folders and report storage are excluded. Unsupported binaries receive filesystem metadata only.'],
    ['Stop', 'Keeps completed findings. Switching tabs and refreshing preserves saved results; restarting the app interrupts active work.'],
    ['Report / Copy / Save Markdown', 'Review per-file references, hashes and text coverage before using a model summary. Reports can contain content from your chosen folder.'],
  ]]],
};
