export const classificationHelp = ['Review and classification', [
  ['Review selection / slideshow', 'Opens selected items for rating, captions, tags and face corrections. Previous / Next or the arrow keys move between items; notes save on navigation and Save & close.'],
  ['Group faces', 'Uses installed local face models to group similar faces. Names are supplied by you; the app does not identify people by their real-world identity.'],
  ['Scene classification model', 'Choose an installed vision model to add scene labels, or leave scene classification off.'],
  ['Classify selection', 'Processes only selected items with the enabled face and scene options. Opening the manager does not start classification.'],
  ['Classify unprocessed catalog', 'Processes up to 1,000 unprocessed images per batch, retaining saved names and corrections.'],
  ['Stop classification', 'Stops remaining classification work while retaining completed results.'],
  ['Name / Save name', 'Every person thumbnail and every face in a reviewed photo has its own name field. Enter or Save name saves the trimmed name for the whole person group; Escape restores the saved name.'],
  ['Person thumbnail', 'Filters photos to that person. A photo with several people can appear in several groups; clicking the thumbnail is separate from editing its name.'],
  ['Change person / Move face', 'Reassigns only the selected face to an existing or new person. Other faces in the photo retain their groups.'],
  ['Not a face / Undo', 'Excludes a mistaken detection. Undo last face correction restores the previous grouping for that correction.'],
  ['Merge groups', 'Combines all faces into the chosen target group and keeps its name. Review the two thumbnails first; shared classifications update across workspaces.'],
  ['People / scene / rating filters', 'Narrow the classified catalog; search also matches names, captions and tags. Clear photo filters resets those filters.'],
  ['Scene labels', 'Ctrl/Cmd-select multiple labels to correct them manually. Manual corrections survive later scans.'],
  ['Like / Dislike / Return to review', 'Records a review rating. Like and Dislike advance to the next item when one is available.'],
  ['Caption / notes', 'Edit text, then Save notes or Save & close.'],
  ['Existing tag / Create & apply tag', 'Adds a tag while retaining other tags and saving notes. Editing the comma-separated list directly requires Save notes.'],
  ['Export selection & notes', 'Exports original copies with captions, ratings and tags. Source files stay in place.'],
]];

export const mediaHelp = {
  'sound-mixer': [['Mixer controls', [
    ['Master / output', 'The shared playback volume, mute and output device also update Settings and Audio. Channel settings save automatically; tracks, live inputs and unsaved recordings last only until refresh or app closure.'],
    ['Channel faders / Mute / Solo', 'Adjust a workspace or local track independently. Solo can select several channels; all other channels are silenced until solos are cleared. Mute takes priority over Solo.'],
    ['EQ & pan', 'Low, mid and high EQ range from -12 to +12 dB. Pan moves a processed channel left or right. The output limiter reduces peaks after mixing. Level meters measure actual PCM audio.'],
    ['Local tracks', 'Add up to eight audio files, 100 MB each, from this computer. Play, pause, rewind, seek and loop each independently. Play all uses the current positions. Stop inputs pauses tracks and releases the microphone. Files are never uploaded.'],
    ['Microphone / Monitor', 'Enable requests permission for the selected input. Its channel joins the recording while speaker monitoring stays off; enable Monitor with headphones. Disable immediately releases the microphone. Opening this tab never requests capture.'],
    ['Record mix / Stop / Save', 'Records processed renderer channels and the enabled microphone, after their faders and master level, for up to five minutes or 32 MB. Leaving the tab keeps a recording running. Save downloads the result; clear only removes the unsaved result.'],
    ['External and installed voices', 'Desktop Browser, Media Manager and linked players support channel mute and volume for HTML players. They cannot feed the mixer EQ, meters or recording. Installed Windows speech voices use the Speech fader for new chunks; mute stops speech. Their PCM also stays outside the mix recording. Cross-origin players without CORS retain volume/mute only.'],
    ['Presets / Board settings', 'Flat, Voice and Music adjust the board. Board settings contains Save settings and Load settings. Exported JSON contains channel levels, EQ, pan, mute, solo and limiter settings, without audio files, device identifiers or recordings. Loading never starts playback or capture.'],
  ]]],
  audio: [['Transcription', [
    ['Record microphone / Stop recording', 'Records up to 10 minutes. Stop recording before transcribing; leaving this workspace discards an unfinished recording.'],
    ['Upload audio', 'Accepts a complete recording up to 2 hours and 250 MB. Supported formats include WAV, MP3, M4A, AAC, OGG, FLAC, WebM and MP4 audio.'],
    ['Transcription model', 'Choose an installed Whisper model. Large-v3 Turbo is roughly 1.6 GB, small 500 MB and base 150 MB; smaller models use less memory.'],
    ['Language', 'Automatic detects the language. An explicit choice can help with short clips.'],
    ['Processing / CPU assistance', 'Auto uses an available NVIDIA GPU or falls back to CPU. CPU assistance adjusts parallel workers to cores and memory; Light uses fewer cores.'],
    ['Separate speakers', 'Compares voices across the recording and produces timestamped speaker turns. Choose a known speaker count when possible. Speaker models use roughly 110 MB; labels distinguish voices without identifying people.'],
    ['Transcribe audio / Stop', 'Starts local transcription of the completed recording. Long inputs are processed in sections; Stop cancels unfinished work.'],
    ['Transcript / speaker names', 'Review words, timestamps and speaker labels before using them, particularly quiet or overlapping speech. Edit labels and individual turns directly.'],
    ['Copy / Save / Insert into chat', 'Uses the reviewed transcript. Inserting stages text in the composer; it does not send the message. Unsaved audio and text clear on refresh or close.'],
  ]], ['Audio extraction', [
    ['Input / Track', 'Open or drop a video/audio file up to 2 GB and 2 hours. Track 1 is its first audio track; another number can select an alternate language.'],
    ['Format', 'MP3 and M4A produce compact copies. WAV uses 16-bit uncompressed audio; FLAC compresses without further loss.'],
    ['Channels / sample rate', 'Choose mono or stereo and a sample rate up to 48 kHz. Surround audio is mixed to stereo.'],
    ['Extract / Save / Transcribe', 'Creates a local audio copy up to 250 MB, then lets you listen, save or use it for transcription. Video, subtitles, cover art and metadata are omitted.'],
    ['Extraction lifetime', 'Leaving Audio stops playback but extraction can continue. Refreshing or closing clears unsaved results and cancels unfinished requests.'],
  ]], ['Text to speech', [
    ['Text / voice / speed', 'Enter up to 20,000 characters and choose an installed system voice and playback speed. These settings also apply to chat Read aloud.'],
    ['Read aloud / Stop', 'Starts or stops requested local playback. No speech starts merely by opening the workspace.'],
  ]], ['Voice cloning', [
    ['Engine / language', 'Select an installed local engine. Chatterbox Turbo is English-only; the other engines offer their listed languages. Chatterbox retains its audio watermark.'],
    ['Record / upload reference', 'Use a clear 6–30 second recording of one voice you own or have permission to use. Avoid music or overlapping speakers. Save reference recording keeps the original microphone audio.'],
    ['Reference transcript', 'Review the exact words spoken. OmniVoice and Qwen transcribe a blank reference before generating; Chatterbox uses the recording alone. Use the sample phrase only if you read it word for word.'],
    ['Demo this voice', 'Generates your entered text or the displayed sample, then plays it when ready. This is local speech generation; CPU processing can take several minutes.'],
    ['Save text / Save WAV', 'Save the words or finished audio before refreshing or closing. Leaving the workspace stops playback but a submitted generation can finish.'],
    ['Use this voice for chat', 'Saves the reference and selects it in chat voice settings. Review character-reference notes before using them as a transcript.'],
  ]]],
  images: [['Browse and organize', [
    ['Collections / folders', 'Choose a collection or saved folder. Folder images are app copies with source links; deleting a source chat leaves saved folder copies intact.'],
    ['Search / filters', 'Narrow the gallery by its available filters.'],
    ['Image tags', 'Click a tag to apply or remove it. A new tag is applied to the current image. Tag filters match every selected tag while allowing additional tags.'],
    ['Thumbnail', 'Opens the original image. Image actions can send it to Editor, Generate, a workflow or an export.'],
    ['Selection', 'Ctrl-click toggles an item; Shift-click selects a range and Ctrl+Shift adds the range. Select all includes matches across pages.'],
    ['Remove / Delete', 'Review the scope shown by the action before confirming. Removing a reference and deleting stored bytes are different operations.'],
  ]], ['Hidden and Locked', [
    ['Hide / Restore', 'Hides catalog items until you explicitly restore them.'],
    ['Lock selected images', 'Review the selection before confirming. Private app copies are encrypted; external source files and backups are not encrypted by this feature.'],
    ['Cancel / Escape', 'Closes the lock dialog before confirming. Images are locked only after you explicitly confirm the selection.'],
    ['PIN', 'Use 4–12 digits. There is no PIN bypass. Locked images and identical copies remain hidden elsewhere until restored.'],
    ['Unlock / automatic lock', 'Unlocking lets you browse this folder without exposing its content in other views. It relocks on leaving, hiding the app or after 15 minutes.'],
    ['Workflow Images', 'Browse completed workflow outputs and stitched references separately. Keep or save a stitched PNG to use it as a later reference.'],
  ]]],
  'image-manager': [['Folders and catalog', [
    ['Add source folder / Scan folders', 'Scans checked folders for still images. Originals stay in place; opening the workspace never starts a scan.'],
    ['Catalog coverage', 'Scans skip animated/multiple-frame images, directory links and NVIDIA paths. Previews respect EXIF orientation.'],
    ['Search / All tags', 'Filters catalog matches. Saved tag choices cover the available catalog, including hidden images. Choosing a tag clears Untagged only.'],
    ['More filters', 'Contains date, format, favorites and Untagged only filters. The summary shows active filters.'],
    ['Selection', 'Ctrl-click toggles an image; Shift-click selects a range. Actions include selected items on other pages.'],
    ['Tag selected images → Add tag / Set tags', 'Expand after selecting images. Add tag keeps existing tags. Set tags replaces them; submitting a blank tag list clears them. Collapsing the tools retains your tag draft.'],
    ['Selection options', 'Appears after selecting images and groups favorites, hiding, organization and reviewed deletion. Hidden images stay hidden after rescanning or restarting until restored.'],
  ]], classificationHelp, ['Duplicates and file actions', [
    ['Find exact duplicates', 'Compares SHA-256 byte hashes, not visual similarity. Hardlinked paths can share disk space. No files are removed by the search.'],
    ['Send duplicates', 'Rechecks hashes and prepares a plan for the source folder’s Duplicates subfolder. Matching hashes get their own groups with relative folders retained.'],
    ['Organize / Copy / Move', 'Prepares exact source and destination paths for review. Copy retains originals; Move removes each source only after verifying its destination. Existing names receive suffixes.'],
    ['Date layout', 'Uses EXIF capture time when available, otherwise the file’s modified date.'],
    ['Apply plan', 'Executes the reviewed transfer plan. Plans stop if source or target files change. Functions prepare plans for up to 1,000 catalog images; review and apply separately.'],
    ['Delete / Trash / Restore', 'Delete reviews files before moving them to recoverable Trash on the same drive. Trash retains bytes and does not free disk space. Restore checks for collisions.'],
    ['Image functions / History', 'Save ordered scan, duplicate, plan and report steps. Jobs continue across tabs; Stop retains completed work. History shows the latest ten transfer receipts.'],
  ]], ['Image tools', [
    ['Scope / output folder', 'Choose image folder, then Read image folder directly in Image tools to scan new or changed files. Or use selected catalog images. Choose a separate output folder; each run creates a new output subfolder. The fixed action area explains any missing step.'],
    ['Convert / resize', 'Creates new copies. PNG and WebP retain transparency; JPEG flattens onto the chosen background. Original metadata is omitted.'],
    ['Sizing / sheets', 'Exact dimensions is the default and keeps large PNG compilations at the requested size using temporary disk space. Fit into one image optionally shrinks compilation tiles to 64 MP. Multiple sheets preserves regular-grid tile sizes across smaller outputs. The whole catalog folder is processed without a source count, pixel or byte cap.'],
    ['Grid / full fill / order', 'Auto or custom columns support incomplete final rows. Balanced full fill places whole images in orientation-separated rows with no added gaps. Choose filename order, reverse or Shuffle.'],
    ['Preparation / naming', 'Optional near-white border trimming and portrait/landscape 1080p sizing affect exported copies only. A prefix numbers copies; dimensions.csv records order, sizes and sheet positions. Originals are retained.'],
    ['Stitch / GIF', 'Compilation exports default to sheets only; individual copies are optional. Exact PNG grids have no generic megapixel limit. JPEG supports 65,500 pixels per side and WebP 16,383; use PNG for larger dimensions. GIFs share a 128 MiB budget and flatten transparency.'],
  ]]],
  'media-manager': [['Library and playback', [
    ['Source folders / Scan', 'Choose a source folder and scan with the destination blank to browse and review MP4 files in place. Scanning saves catalog entries and reports without changing media files. A destination is only needed to preview an archive move.'],
    ['Library / date filters', 'Filter by dates and media metadata; thumbnails open playback or a preview.'],
    ['Selection', 'Ctrl-click toggles files, Shift-click selects a range, and Ctrl+Shift adds a range. Bulk actions include selections hidden by filters.'],
    ['Enter Media Manager / F6', 'Enter moves keyboard focus into the embedded workspace. F6 returns to app navigation.'],
    ['Reload thumbnails', 'Retries this workspace’s previews after a failure.'],
    ['Duplicate copies', 'Scanning includes MP4 subfolders and identifies identical copies by hash. With a destination, the move preview uses Year / Category / Original filename and can keep every copy, separate extra copies into _Duplicates, or leave them in the source.'],
    ['Custom folders', 'Create or connect a real folder. Selected clips move only after reviewing and confirming their plan.'],
    ['Custom tags', 'Tags follow the content hash, so identical video copies share them. Create & apply adds the new tag to the selected items.'],
    ['Capture frames / image tools', 'Save chosen video frames or create converted, resized, stitched or GIF copies through the explicit tool controls.'],
    ['Rename', 'Changes a selected video filename while retaining .mp4. Existing destination files are not overwritten.'],
    ['Plan / Move / Copy', 'Review destinations and the operation before confirming. Planning does not transfer files.'],
    ['Delete / Trash / Restore', 'Delete moves the reviewed copy to recoverable Trash on its drive. Restore refuses collisions; permanent deletion requires a separate confirmation.'],
  ]], ['Frames, clips and image tools', [
    ['Video → frames', 'Uses decoded source-frame numbers, including variable-rate video. An interval of 1/15 saves frames 1, 16, 31 and so on.'],
    ['First / last frame / output width', 'Limits the sampled range and exported resolution. Rotation can use the original orientation or saved viewing rotation.'],
    ['Parse frames / output folder', 'Creates a new frame-set folder with images and a source-frame manifest. The source video remains in place.'],
    ['CLIP / start / end', 'Mark the range while playing, preview it, then save a new MP4. Apply viewing rotation optionally changes the saved clip’s orientation.'],
    ['Image folder / include subfolders', 'Reads up to 1,000 JPEG, PNG, WebP, BMP or TIFF images. Animated and multipage inputs contribute their first image only.'],
    ['Size / format / background', 'Creates a new output subfolder per run. PNG/WebP retain transparency; JPEG flattens it onto the background. Original metadata is omitted.'],
    ['Stitch / GIF options', 'Uses one common image size and saves individual copies too. GIFs have up to 256 colors; listed frames play in order with no generated in-between frames.'],
    ['Timing / loop / order', 'Sets animation delay, repeat count and frame order before creating copies.'],
  ]], ['Video classification', [
    ['Classify selection', 'Uses a representative preview for each selected video, up to 20 at a time. It is not an analysis of every video frame.'],
    ['Person names / corrections', 'Name grouped people, correct mistaken face matches and filter by person or scene. An optional local vision model adds scene labels.'],
    ['Review notes / export', 'Save ratings, captions and tags, then export selected copies and notes through the review controls.'],
  ]]],
  review: [['Review controls', [
    ['Images / People & scenes / Organize files', 'Images is the main review gallery. Open People & scenes for face groups and classification, or Organize files for transfers and advanced metadata. Each view keeps its controls separate.'],
    ['Show / Favorites only / Tags', 'Choose To review, Reviewed (no rating), Liked, Disliked or All images. Favorites are independent bookmarks and can be combined with any filter. Open Tags when you need tag filters.'],
    ['Start review / Done & next', 'Click an image or Start review to inspect it. Like and Dislike save a rating and advance. Done & next marks a new image reviewed without a rating, preserving any existing Like or Dislike.'],
    ['Select images / More actions', 'Select images to show Like and Dislike plus a compact menu for folders, workflows, favorites, exports and deletion. Choose a menu action, then Apply.'],
    ['Caption / tags', 'Edit the review metadata before saving.'],
    ['Edit / workflow / folder', 'Send a chosen image to Editor, begin a workflow, or save a copy in a Gallery folder.'],
    ['Export selected', 'Exports only selected images and their review metadata.'],
    ['Export a rating group', 'Choose Liked or Disliked in Show, then Select images, Select all, and Export selected in More actions.'],
  ]]],
  'gif-maker': [['Frames', [
    ['Add images / drop', 'Adds PNG, JPEG or WebP frames. The draft remains while you use other workspaces.'],
    ['Frame order / delay', 'Arrange frames and set how long each remains visible.'],
    ['Frame thumbnail', 'Click to view the original. Copy thumbnail uses a small PNG; Save thumbnail uses the selected thumbnail export size.'],
    ['ZIP frames', 'Exports all frames in their current order. Source images stay unchanged.'],
    ['Retry thumbnail', 'Retries only the failed frame preview. Unlock or remove locked frames before previewing or creating an animation.'],
  ]], ['Output', [
    ['Dimensions / fit / background', 'Sets output size and how images fit. Small images enlarge as needed; transparent areas use the background color.'],
    ['Frame limits', 'Images are limited to 40 MiB and 24 megapixels each, with 160 MiB total input.'],
    ['Preview / playback', 'Checks frame order, timing and fit before export.'],
    ['Output folder / Use library', 'Selects where new exported copies are saved.'],
    ['Create / Save GIF', 'Queues animation creation and saves the completed output. GIF exports use a separate CPU queue.'],
  ]]],
};
