export const classificationHelp = ['Review and classification', [
  ['Review selection / slideshow', 'Opens selected items for rating, captions, tags and face corrections. Previous / Next or the arrow keys move between items; notes save on navigation and Save & close.'],
  ['Group faces', 'Uses installed local face models to group similar faces. Names are supplied by you; the app does not identify people by their real-world identity.'],
  ['Scene classification model', 'Choose an installed vision model to add scene labels, or leave scene classification off.'],
  ['Classify selection', 'Processes only selected items with the enabled face and scene options. Opening the manager does not start classification.'],
  ['Classify unprocessed catalog', 'Processes up to 1,000 unprocessed images per batch, retaining saved names and corrections.'],
  ['Stop classification', 'Stops remaining classification work while retaining completed results.'],
  ['Name / Save name', 'Every person thumbnail and every face in a reviewed photo has its own name field. Enter or Save name saves the trimmed name for the whole person group; Escape restores the saved name.'],
  ['Person thumbnail', 'Filters photos to that person. A photo with several people can appear in several groups; clicking the thumbnail is separate from editing its name.'],
  ['Change person / Move face', 'Reassigns only the selected face to an existing or new person. Other faces in the photo retain their groups.'],
  ['Not a face / Undo', 'Excludes a mistaken detection. Undo last face correction restores the previous grouping for that correction.'],
  ['Merge groups', 'Combines all faces into the chosen target group and keeps its name. Review the two thumbnails first; shared classifications update across workspaces.'],
  ['People / scene / rating filters', 'Narrow the classified catalog; search also matches names, captions and tags. Clear photo filters resets those filters.'],
  ['Scene labels', 'Ctrl/Cmd-select multiple labels to correct them manually. Manual corrections survive later scans.'],
  ['Like / Dislike / Return to review', 'Records a review rating. Like and Dislike advance to the next item when one is available.'],
  ['Caption / notes', 'Edit text, then Save notes or Save & close.'],
  ['Existing tag / Create & apply tag', 'Adds a tag while retaining other tags and saving notes. Editing the comma-separated list directly requires Save notes.'],
  ['Export selection & notes', 'Exports original copies with captions, ratings and tags. Source files stay in place.'],
]];

export const mediaHelp = {
  audio: [['Transcription', [
    ['Record microphone / Stop recording', 'Records up to 10 minutes. Stop recording before transcribing; leaving this workspace discards an unfinished recording.'],
    ['Upload audio', 'Accepts a complete recording up to 2 hours and 250 MB. Supported formats include WAV, MP3, M4A, AAC, OGG, FLAC, WebM and MP4 audio.'],
    ['Transcription model', 'Choose an installed Whisper model. Large-v3 Turbo is roughly 1.6 GB, small 500 MB and base 150 MB; smaller models use less memory.'],
    ['Language', 'Automatic detects the language. An explicit choice can help with short clips.'],
    ['Processing / CPU assistance', 'Auto uses an available NVIDIA GPU or falls back to CPU. CPU assistance adjusts parallel workers to cores and memory; Light uses fewer cores.'],
    ['Separate speakers', 'Compares voices across the recording and produces timestamped speaker turns. Choose a known speaker count when possible. Speaker models use roughly 110 MB; labels distinguish voices without identifying people.'],
    ['Transcribe audio / Stop', 'Starts local transcription of the completed recording. Long inputs are processed in sections; Stop cancels unfinished work.'],
    ['Transcript / speaker names', 'Review words, timestamps and speaker labels before using them, particularly quiet or overlapping speech. Edit labels and individual turns directly.'],
    ['Copy / Save / Insert into chat', 'Uses the reviewed transcript. Inserting stages text in the composer; it does not send the message. Unsaved audio and text clear on refresh or close.'],
  ]], ['Audio extraction', [
    ['Input / Track', 'Open or drop a video/audio file up to 2 GB and 2 hours. Track 1 is its first audio track; another number can select an alternate language.'],
    ['Format', 'MP3 and M4A produce compact copies. WAV uses 16-bit uncompressed audio; FLAC compresses without further loss.'],
    ['Channels / sample rate', 'Choose mono or stereo and a sample rate up to 48 kHz. Surround audio is mixed to stereo.'],
    ['Extract / Save / Transcribe', 'Creates a local audio copy up to 250 MB, then lets you listen, save or use it for transcription. Video, subtitles, cover art and metadata are omitted.'],
    ['Extraction lifetime', 'Leaving Audio stops playback but extraction can continue. Refreshing or closing clears unsaved results and cancels unfinished requests.'],
  ]], ['Text to speech', [
    ['Text / voice / speed', 'Enter up to 20,000 characters and choose an installed system voice and playback speed. These settings also apply to chat Read aloud.'],
    ['Read aloud / Stop', 'Starts or stops requested local playback. No speech starts merely by opening the workspace.'],
  ]], ['Voice cloning', [
    ['Engine / language', 'Select an installed local engine. Chatterbox Turbo is English-only; the other engines offer their listed languages. Chatterbox retains its audio watermark.'],
    ['Record / upload reference', 'Use a clear 6–30 second recording of one voice you own or have permission to use. Avoid music or overlapping speakers. Save reference recording keeps the original microphone audio.'],
    ['Reference transcript', 'Review the exact words spoken. OmniVoice and Qwen transcribe a blank reference before generating; Chatterbox uses the recording alone. Use the sample phrase only if you read it word for word.'],
    ['Demo this voice', 'Generates your entered text or the displayed sample, then plays it when ready. This is local speech generation; CPU processing can take several minutes.'],
    ['Save text / Save WAV', 'Save the words or finished audio before refreshing or closing. Leaving the workspace stops playback but a submitted generation can finish.'],
    ['Use this voice for chat', 'Saves the reference and selects it in chat voice settings. Review character-reference notes before using them as a transcript.'],
  ]]],
  images: [['Browse and organize', [
    ['Collections / folders', 'Choose a collection or saved folder. Folder images are app copies with source links; deleting a source chat leaves saved folder copies intact.'],
    ['Search / filters', 'Narrow the gallery by its available filters.'],
    ['Image tags', 'Click a tag to apply or remove it. A new tag is applied to the current image. Tag filters match every selected tag while allowing additional tags.'],
    ['Thumbnail', 'Opens the original image. Image actions can send it to Editor, Generate, a workflow or an export.'],
    ['Selection', 'Ctrl-click toggles an item; Shift-click selects a range and Ctrl+Shift adds the range. Select all includes matches across pages.'],
    ['Remove / Delete', 'Review the scope shown by the action before confirming. Removing a reference and deleting stored bytes are different operations.'],
  ]], ['Hidden and Locked', [
    ['Hide / Restore', 'Hides catalog items until you explicitly restore them.'],
    ['Lock selected images', 'Review the selection before confirming. Private app copies are encrypted; external source files and backups are not encrypted by this feature.'],
    ['Cancel / Escape', 'Closes the lock dialog before confirming. Images are locked only after you explicitly confirm the selection.'],
    ['PIN', 'Use 4–12 digits. There is no PIN bypass. Locked images and identical copies remain hidden elsewhere until restored.'],
    ['Unlock / automatic lock', 'Unlocking lets you browse this folder without exposing its content in other views. It relocks on leaving, hiding the app or after 15 minutes.'],
    ['Workflow Images', 'Browse completed workflow outputs and stitched references separately. Keep or save a stitched PNG to use it as a later reference.'],
  ]]],
  'image-manager': [['Folders and catalog', [
    ['Add source folder / Scan folders', 'Scans checked folders for still images. Originals stay in place; opening the workspace never starts a scan.'],
    ['Catalog coverage', 'Scans skip animated/multiple-frame images, directory links and NVIDIA paths. Previews respect EXIF orientation.'],
    ['Search / All tags', 'Filters catalog matches. Saved tag choices cover the available catalog, including hidden images. Choosing a tag clears Untagged only.'],
    ['More filters', 'Contains date, format, favorites and Untagged only filters. The summary shows active filters.'],
    ['Selection', 'Ctrl-click toggles an image; Shift-click selects a range. Actions include selected items on other pages.'],
    ['Add tag / Set tags', 'Add tag keeps existing tags. Set tags replaces them; submitting a blank tag list clears them.'],
    ['More actions', 'Groups favorites, hiding, organization and reviewed deletion. Hidden images stay hidden after rescanning or restarting until restored.'],
  ]], classificationHelp, ['Duplicates and file actions', [
    ['Find exact duplicates', 'Compares SHA-256 byte hashes, not visual similarity. Hardlinked paths can share disk space. No files are removed by the search.'],
    ['Send duplicates', 'Rechecks hashes and prepares a plan for the source folder’s Duplicates subfolder. Matching hashes get their own groups with relative folders retained.'],
    ['Organize / Copy / Move', 'Prepares exact source and destination paths for review. Copy retains originals; Move removes each source only after verifying its destination. Existing names receive suffixes.'],
    ['Date layout', 'Uses EXIF capture time when available, otherwise the file’s modified date.'],
    ['Apply plan', 'Executes the reviewed transfer plan. Plans stop if source or target files change. Functions prepare plans for up to 1,000 catalog images; review and apply separately.'],
    ['Delete / Trash / Restore', 'Delete reviews files before moving them to recoverable Trash on the same drive. Trash retains bytes and does not free disk space. Restore checks for collisions.'],
    ['Image functions / History', 'Save ordered scan, duplicate, plan and report steps. Jobs continue across tabs; Stop retains completed work. History shows the latest ten transfer receipts.'],
  ]], ['Image tools', [
    ['Scope / output folder', 'Use selected images or the visible folder catalog. Scan new or changed source files first. Each run creates a new output subfolder.'],
    ['Convert / resize', 'Creates new copies. PNG and WebP retain transparency; JPEG flattens onto the chosen background. Original metadata is omitted.'],
    ['Stitch / GIF', 'Creates a strip, grid or animation plus individual image copies. Stitches support up to 64 MP; GIFs are bounded by memory and flatten transparency.'],
  ]]],
  'media-manager': [['Library and playback', [
    ['Source folders / Scan', 'Adds catalog entries for chosen media locations. Review scan results before preparing file operations.'],
    ['Library / date filters', 'Filter by dates and media metadata; thumbnails open playback or a preview.'],
    ['Selection', 'Ctrl-click toggles files, Shift-click selects a range, and Ctrl+Shift adds a range. Bulk actions include selections hidden by filters.'],
    ['Enter Media Manager / F6', 'Enter moves keyboard focus into the embedded workspace. F6 returns to app navigation.'],
    ['Reload thumbnails', 'Retries this workspace’s previews after a failure.'],
    ['Duplicate copies', 'Keep every copy, separate extra copies into _Duplicates, or leave them in the source. Scanning includes MP4 subfolders and prepares a Year / Category / Original filename plan without moving files.'],
    ['Custom folders', 'Create or connect a real folder. Selected clips move only after reviewing and confirming their plan.'],
    ['Custom tags', 'Tags follow the content hash, so identical video copies share them. Create & apply adds the new tag to the selected items.'],
    ['Capture frames / image tools', 'Save chosen video frames or create converted, resized, stitched or GIF copies through the explicit tool controls.'],
    ['Rename', 'Changes a selected video filename while retaining .mp4. Existing destination files are not overwritten.'],
    ['Plan / Move / Copy', 'Review destinations and the operation before confirming. Planning does not transfer files.'],
    ['Delete / Trash / Restore', 'Delete moves the reviewed copy to recoverable Trash on its drive. Restore refuses collisions; permanent deletion requires a separate confirmation.'],
  ]], ['Frames, clips and image tools', [
    ['Video → frames', 'Uses decoded source-frame numbers, including variable-rate video. An interval of 1/15 saves frames 1, 16, 31 and so on.'],
    ['First / last frame / output width', 'Limits the sampled range and exported resolution. Rotation can use the original orientation or saved viewing rotation.'],
    ['Parse frames / output folder', 'Creates a new frame-set folder with images and a source-frame manifest. The source video remains in place.'],
    ['CLIP / start / end', 'Mark the range while playing, preview it, then save a new MP4. Apply viewing rotation optionally changes the saved clip’s orientation.'],
    ['Image folder / include subfolders', 'Reads up to 1,000 JPEG, PNG, WebP, BMP or TIFF images. Animated and multipage inputs contribute their first image only.'],
    ['Size / format / background', 'Creates a new output subfolder per run. PNG/WebP retain transparency; JPEG flattens it onto the background. Original metadata is omitted.'],
    ['Stitch / GIF options', 'Uses one common image size and saves individual copies too. GIFs have up to 256 colors; listed frames play in order with no generated in-between frames.'],
    ['Timing / loop / order', 'Sets animation delay, repeat count and frame order before creating copies.'],
  ]], ['Video classification', [
    ['Classify selection', 'Uses a representative preview for each selected video, up to 20 at a time. It is not an analysis of every video frame.'],
    ['Person names / corrections', 'Name grouped people, correct mistaken face matches and filter by person or scene. An optional local vision model adds scene labels.'],
    ['Review notes / export', 'Save ratings, captions and tags, then export selected copies and notes through the review controls.'],
  ]]],
  review: [['Review controls', [
    ['Request / filters', 'Choose a request or narrow results to the image group you want to inspect.'],
    ['Like / Dislike / To review', 'Records image preferences without changing image pixels.'],
    ['Caption / tags', 'Edit the review metadata before saving.'],
    ['Edit / workflow / folder', 'Send a chosen image to Editor, begin a workflow, or save a copy in a Gallery folder.'],
    ['Export selected', 'Exports only selected images and their review metadata.'],
    ['Export liked / disliked', 'Exports the entire rating group as image copies with caption text, ratings and tags.'],
  ]]],
  'gif-maker': [['Frames', [
    ['Add images / drop', 'Adds PNG, JPEG or WebP frames. The draft remains while you use other workspaces.'],
    ['Frame order / delay', 'Arrange frames and set how long each remains visible.'],
    ['Frame thumbnail', 'Click to view the original. Copy thumbnail uses a small PNG; Save thumbnail uses the selected thumbnail export size.'],
    ['ZIP frames', 'Exports all frames in their current order. Source images stay unchanged.'],
    ['Retry thumbnail', 'Retries only the failed frame preview. Unlock or remove locked frames before previewing or creating an animation.'],
  ]], ['Output', [
    ['Dimensions / fit / background', 'Sets output size and how images fit. Small images enlarge as needed; transparent areas use the background color.'],
    ['Frame limits', 'Images are limited to 40 MiB and 24 megapixels each, with 160 MiB total input.'],
    ['Preview / playback', 'Checks frame order, timing and fit before export.'],
    ['Output folder / Use library', 'Selects where new exported copies are saved.'],
    ['Create / Save GIF', 'Queues animation creation and saves the completed output. GIF exports use a separate CPU queue.'],
  ]]],
};
