export const modelHelp = [
  ['Scene and files', [
    ['New scene / Open file', 'Starts a scene or opens STL, 3MF or a .law3d project. Replacing unsaved edits requires an explicit choice. STL input is interpreted as millimeters; 3MF uses declared units.'],
    ['Add / Insert shape / Custom', 'Adds another STL or 3MF, inserts a primitive, or sets custom shape dimensions.'],
    ['Save project', 'Saves editable objects and paint in .law3d format. Save before closing the app or the Local Files viewer.'],
    ['Export STL', 'Exports scene geometry in millimeters. STL does not preserve paint, textures, declared units or separate editable object structure.'],
    ['Close model', 'Closes the scene after handling unsaved edits. Original files are not overwritten automatically.'],
  ]],
  ['Objects and geometry', [
    ['Select / object list', 'Click an object, Shift-click to add to the selection, or use the object list. Ctrl/Cmd+A selects all; Escape clears selection.'],
    ['Move / Rotate / Scale', 'Uses viewport handles for one selected object. Enter exact transforms in the inspector, then Apply transform.'],
    ['Copy / Cut / Paste / Duplicate', 'Copies, moves or duplicates objects inside the editor. Keyboard shortcuts are Ctrl/Cmd+C, X, V and D.'],
    ['Delete / Undo / Redo', 'Removes selected objects or steps through edit history. Delete removes; Ctrl/Cmd+Z and Y undo/redo.'],
    ['Settle / Mirror', 'Settles selected geometry onto Z = 0 or mirrors it across a chosen axis.'],
    ['Measure', 'Click two surface points to measure their distance in scene units.'],
    ['Simplify / Smooth', 'Simplify reduces detail using a tolerance. Smooth rounds edges and adds surface detail.'],
    ['Split', 'Cuts the selected object at the chosen axis and plane position.'],
    ['Merge / Intersect / Subtract', 'Runs solid operations on closed meshes. Subtract retains the first selected object as the base and removes the others’ overlapping volume.'],
    ['Hollow', 'Creates an enclosed cavity with a faceted spherical inset, up to 5,000 input triangles. It does not add a drain opening. Wall thickness uses scene units.'],
    ['Extrude down / Emboss', 'Extrude adds the XY footprint below the object’s lowest point. Emboss adds centered text to a flat top surface using the chosen size and depth.'],
  ]],
  ['Paint and view', [
    ['Paint / texture picker', 'Applies materials to selected objects. The picker samples a material from the viewport; imported meshes without UVs use a top-down texture projection.'],
    ['Material / Color', 'Choose plastic, matte, metal, gold or glass, then adjust color, roughness, metallic and opacity. Apply brush reuses the sampled material on selected objects.'],
    ['Load texture / swatches / stamps', 'Use a local PNG, JPEG or WebP up to 12 MB, a procedural texture, or a shape stamp. Images are limited to 2048 pixels per side. Recent materials stay in memory. Transparent stamps reveal the underlying paint.'],
    ['Generate QR', 'Enter an HTTP or HTTPS URL to generate a texture locally. The URL is encoded without visiting the website. Turn off transparent background for a white QR background.'],
    ['Camera', 'Starts a local video-only preview after explicit permission. Capture texture, Cancel, or leaving Paint stops it. A full desktop restart is required after installing the camera service.'],
    ['Orbit / zoom / pan', 'Drag to rotate, scroll or pinch to zoom, and right-drag to pan.'],
    ['Fit model / Center view / Reset view', 'Frames the model or restores the isometric camera. Named camera buttons select Front, Back, Left, Right, Top, Bottom or Isometric.'],
    ['Orthographic / Wireframe / X-ray', 'Changes the preview projection or surface display without modifying geometry.'],
    ['Shading / Shadows / Colors / Reflections / Smoothing', 'Changes viewport appearance.'],
    ['Grid / XYZ axes', 'Toggles spatial guides: X is red, Y green and Z blue.'],
    ['Dimensions / bounds / area', 'Reports scene or selected-object measurements, triangle counts and mesh counts.'],
  ]],
  ['Windows mesh repair', [
    ['Repair source mesh with Windows', 'Open this section after importing an STL or 3MF. It repairs the opened source file; save a project to retain scene edits before switching repair previews.'],
    ['Repair model', 'Runs Microsoft’s public Windows mesh-repair API locally. It does not upload geometry or use an AI model. Exact parity with the separate 3D Builder app has not been established.'],
    ['Show original / Show repaired', 'Compare shape and dimensions before saving. Repair can change surface geometry and triangle counts.'],
    ['Windows mesh verification', 'Reports meshes with errors and triangle counts before and after repair. Passing this check does not guarantee a printable result for every slicer or printer.'],
    ['Save repaired 3MF', 'Saves supported model data with declared units. Unsupported extensions and slicer-specific settings may not survive repair.'],
    ['Save repaired STL', 'Saves repaired surface geometry in millimeters. Choose millimeters when importing it into a slicer.'],
    ['New filename', 'Repair exports refuse existing filenames. Cancelling the save dialog retains the repair result.'],
    ['Cancel repair / Cancel export', 'Stops unfinished preparation or processing while preserving the source. Save a result before closing the repair view or changing its source.'],
    ['Repair limits', 'Input/output are limited to 128 MB each, expanded 3MF to 256 MB and geometry to 8 million triangles. The Windows worker times out after 15 minutes.'],
    ['Desktop availability', 'Native repair needs the Windows desktop app. After a desktop update, fully quit and reopen it to load the repair service.'],
  ]],
];
