export const workflowSettingsHelp = [
  ['Workflow settings', [
    ['Scene continuity notes', 'Records appearance, action and details that must remain consistent. These planning notes are not silently appended to the prompt.'],
    ['Attach images', 'Select multiple single-frame PNG, JPEG or WebP files up to 20 MiB and 24 megapixels each. Attaching saves pending draft changes first.'],
    ['Positive prompt', 'Describes the desired image or edit. Review model suggestions before applying them to this field.'],
    ['Negative prompt', 'Describes things to discourage. Support depends on the selected model and adapter.'],
    ['Seed', '-1 requests a new random seed. Fixing a seed helps comparisons but does not guarantee identical output across models or hardware.'],
    ['Steps', 'Counts SDXL refinement passes. Steps multiplied by nonzero change strength must be at least one.'],
    ['Guidance', 'Controls prompt influence. Excessive guidance can introduce harsh contrast or distorted details.'],
    ['Stage mask', 'White marks the area to edit; black preserves it. Match the source dimensions. Processing workflows require an uploaded mask.'],
    ['Control map type / map', 'Records edges, depth, pose or another prepared map. Map extraction and compatible control adapters are not implemented.'],
    ['Control influence', 'Sets the intended map influence for an adapter that supports it. The control-map stage cannot run without a compatible installed adapter.'],
    ['Change strength', 'Zero stays closest to the source; one allows the largest change. Exact behavior depends on the adapter.'],
    ['Size multiplier', 'Lanczos resamples on CPU at 2×, 3× or 4×, with output limited to 24 megapixels. It does not reconstruct missing detail with AI.'],
  ]],
  ['Scene fields', [
    ['Visible action', 'Describe the resulting pose and contact, such as a hand gripping a tool and a screw sitting deeper in a board.'],
    ['Starting image', 'Optional for the first frame. Upload makes a scene-owned copy.'],
    ['Denoising strength', 'Small changes commonly use 0.15–0.30 and moderate changes 0.30–0.50. Higher values can redesign the scene; zero preserves the source.'],
    ['Visual style', 'Describes the medium or overall visual treatment for the next frame.'],
    ['Name / Appearance', 'Sets the character name and visible characteristics in the scene prompt.'],
    ['Clothing / Accessories', 'Describes garments and carried or worn items to retain in the scene.'],
    ['Location / Background details', 'Sets the environment and surrounding visible details.'],
    ['Framing', 'Describes the crop or shot scale, such as close-up or full body.'],
    ['Angle / Camera position', 'Describes the viewpoint and where the camera sits relative to the subject.'],
    ['Focal length / Camera orientation', 'Describes lens perspective and camera alignment. These are text instructions to the image model, not a physical camera simulation.'],
    ['Light source / Direction', 'Describes where light comes from and which way it falls.'],
    ['Intensity / Lighting style', 'Describes light strength and treatment, such as soft diffuse light or sharp shadows.'],
    ['Stance / Body orientation', 'Describes the overall pose and facing direction.'],
    ['Left arm / Right arm', 'Describes each arm separately using the character’s anatomical left and right.'],
    ['Left hand / Right hand / Wrist rotation', 'Describes hand placement, grip and wrist direction. Check the generated frame for anatomical mistakes.'],
    ['Gaze', 'Describes where the character is looking.'],
    ['Object appearance / position / orientation', 'Keeps the object’s identity while describing how it looks, where it sits and which way it faces.'],
    ['Object contact / progression', 'Describes interactions and task progress, such as contact with a hand or partial insertion into another object.'],
  ]],
];

export const imageAdjustmentHelp = ['Image adjustment controls', [
  ['Temperature', 'Shifts the white balance toward cooler or warmer colors.'],
  ['Tint', 'Adjusts the green-to-magenta balance.'],
  ['Brightness', 'Raises or lowers overall image brightness.'],
  ['Exposure', 'Adjusts light in exposure-value stops, from -3 to +3 EV.'],
  ['Contrast', 'Increases or reduces differences between lighter and darker tones.'],
  ['Highlights', 'Adjusts the brighter tonal regions.'],
  ['Shadows', 'Adjusts darker regions without applying the same change everywhere.'],
  ['Whites', 'Adjusts the brightest tones.'],
  ['Blacks', 'Adjusts the darkest tones.'],
  ['Reduce red hue / cast', 'Reduces a red color cast; zero leaves this correction off.'],
  ['Vibrance', 'Adjusts color intensity with a different balance from global saturation.'],
  ['Saturation', 'Increases or reduces color intensity across the image.'],
  ['Sharpness', 'Increases edge definition; excessive sharpening can create halos.'],
  ['Clarity', 'Adjusts local contrast to change perceived detail.'],
  ['Remove blur', 'Sharpens existing detail without inventing missing image content.'],
  ['Low-resolution refinement', 'Refines existing detail without changing the output dimensions.'],
  ['Vignette', 'Adjusts the brightness near the image edges.'],
  ['Slider / number / locked marker', 'Use either input for the setting. Neutral is zero; after locking, the marker shows the prior value and the readout shows the current pass’s change.'],
]];
