export const workstationHelp = {
  library: [['Index controls', [
    ['Search / category / tags', 'Find saved prompt and reference entries by their content and organization.'],
    ['Select / Copy', 'Select an entry to inspect it and copy its text for reuse.'],
    ['New / edit entry', 'Saves authored content and its category or tags.'],
    ['Knowledge connections', 'Links an Index entry to Knowledge documents through explicit connections.'],
  ]]],
  knowledge: [['Documents and retrieval', [
    ['Import / create node', 'Adds supported source text or an authored document to the local index. Saved content becomes available to Knowledge retrieval in chat.'],
    ['Node type', 'Note holds general knowledge, Idea holds a concept, Project groups goals and tasks, Place describes a setting, Event records an occurrence, and Reference holds source notes.'],
    ['Character node', 'Creates a snapshot of a saved character’s biography, notes, tags and resource references, with a link back to that character.'],
    ['Search / tags', 'Finds documents using names, tags and notes. Node tags allow up to 12 entries of 30 characters each.'],
    ['Document / chunks', 'Inspects the indexed text available to retrieval. Chunks can overlap. Names and visual styling organize the graph without replacing indexed source text.'],
    ['Chat Knowledge scope', 'Off disables retrieval, All searches the available index, and Selected limits it to chosen documents. Disconnected nodes can still be retrieved.'],
  ]], ['Graph and connections', [
    ['Rotate / pan / zoom', 'Drag the background to rotate, Shift/right-drag to pan and scroll to zoom. Graph arrow keys rotate the view.'],
    ['Move node / depth', 'Drag unlocked nodes to arrange them. Alt-drag or Deeper/Closer changes depth; node arrow keys move, and Page Up/Down adjusts depth.'],
    ['Appearance / lock', 'Customize node appearance or lock its position. These settings are saved with the graph.'],
    ['Connect / document links', 'Creates explicit links between documents. Imported wiki-style links can also form connections; unresolved or ambiguous links are marked.'],
    ['Connections', 'Lines show saved links, not inferred similarity or proof that a model used a document.'],
  ]]],
  tools: [['System actions', [
    ['Windows Snipping Tool', 'Opens the Windows tool for choosing a screen area to capture.'],
    ['Open PowerShell', 'Opens an interactive terminal.'],
    ['Update Installed Programs', 'Opens a terminal and installs available WinGet updates when explicitly selected.'],
    ['Refresh GPU Driver', 'Requests a Windows graphics reset. The screen can briefly flicker or beep.'],
  ]], ['Custom buttons and captures', [
    ['New button / destination', 'Creates a shortcut to an allowlisted tool or workspace. User-created buttons are stored on this device and sorted alphabetically.'],
    ['Edit / remove button', 'Changes or removes only the selected custom shortcut.'],
    ['Copy tab', 'Captures the tab’s current content at maximized window size while retaining its selections and scroll position. The capture is copied for explicit use.'],
  ]], ['Function Builder', [
    ['Template / steps', 'Choose a template or add supported actions in order. THEN runs the next step after the previous one.'],
    ['Application / window', 'Select the fixed app launcher or a program shortcut. Match any title is appropriate only when one matching app window exists.'],
    ['Accessible field / button', 'Targets a control exposed by the application. Use a clipboard step when an accessible control is unavailable.'],
    ['Point at target', 'Within five seconds, hover over the intended field or button. Keep the same window size and layout for playback; pointer steps cannot confirm the app accepted an action.'],
    ['Text / previous result', 'Enter the text for the step. Use the displayed previous-result token to include text or an audit result from the preceding step.'],
    ['Capture window', 'Brings the target forward and captures its visible view. Keep overlays clear; elevated apps may need manual handoff.'],
    ['Folder audit', 'Reads metadata from the chosen folder, up to 20,000 entries or 30 seconds. Links and NVIDIA paths are skipped.'],
    ['Copy result / Save result', 'Copies the latest screenshot or text. Saves text as Markdown, audits as JSON and screenshots as PNG with unique names in the selected output folder.'],
    ['Add result to chat', 'Stages removable attachments for review before Send.'],
    ['Save / Run / Stop', 'Saving never executes a function. Run performs the reviewed steps; Stop prevents subsequent steps while preserving completed actions and files.'],
  ]]],
  dashboard: [['Hardware and software', [
    ['PC statistics', 'Shows local CPU, RAM, GPU and mounted-volume readings. Most refresh about every five seconds while visible; sensor and memory configuration checks are cached for about 15 seconds.'],
    ['CPU temperature / clock', 'Windows reports nominal frequency here. Temperature requires an exposed sensor, such as supported WMI data from a running hardware monitor.'],
    ['RAM', 'Available includes reclaimable memory; used is total minus available. Reported memory speed is the configured transfer rate.'],
    ['GPU', 'Shows available NVIDIA usage, temperature, clock and VRAM readings. Availability is not a guarantee that a particular model will fit.'],
    ['Drives / folder sizes', 'Lists mounted volumes separately in GiB/TiB. Folder percentages use scanned file sizes; hardlinks are counted once, and links or cloud placeholders are skipped.'],
    ['Copy specs', 'Copies the selected system report sections. Review the selection before sharing.'],
    ['Software specs / logs', 'Reports app versions, source layout, model catalogs and registered APIs. Log exports can contain paths and errors; credentials are redacted.'],
    ['Compatibility', 'Checks detected runtime requirements. A feature can be listed as available without verifying every workload or model.'],
  ]], ['Tool registry and maintenance', [
    ['Tool registry / filters', 'Browse tool requirements, outputs, effects and API schemas. Automatic model tool execution is not connected; registry entries do not grant tools to chat.'],
    ['Copy catalog / download', 'Exports the full catalog for review. Individual item TXT and Copy use the selected tool.'],
    ['Check / prepare maintenance', 'Runs only when requested. Prepared updates require a reviewed proposal and explicit approval; proposals expire after ten minutes.'],
    ['GitHub review / validate / commit / publish', 'Each step runs separately on the selected source snapshot. Validate checks isolated tests, dependencies, the build and outgoing content; commit and publish use the validated selection.'],
  ]], ['Storage and backups', [
    ['Storage libraries / Create', 'Creates an app-owned folder on a chosen drive. Reattach an existing app library using its parent and folder name; unrelated folders are not adopted.'],
    ['Use for new files', 'Changes the default for new managed media, documents, character files and datasets. Existing files and projects stay where they are.'],
    ['Library scope', 'Chats, settings, indexes, audit records, encrypted vaults and models keep their existing locations. Reconnect an unavailable library to access its files.'],
    ['SAVE METADATA', 'Exports counts, storage totals and basic numeric settings from original app data. It excludes personal content and external library totals and cannot restore app data.'],
    ['EXPORT BACK-UP', 'Creates a verified private ZIP of app data, media, LoRA artifacts and desktop preferences, including locked images and registered library files. Reconnect libraries and finish active jobs first.'],
    ['Backup exclusions', 'Installed base models, app code, external files/logs and unsaved edits are not included. Save edits and retain those items separately.'],
    ['IMPORT BACK-UP', 'Verifies a full backup and replaces current data after confirmation, retaining current data and preferences in recovery storage. Managed library files restore into original app data; external libraries remain on disk.'],
    ['Reset app data', 'Permanently clears the listed app data and preferences after confirmation. It keeps installed base models and external files; external library registrations are removed. It creates no automatic backup.'],
  ]], ['PC Bridge', [
    ['Start bridge / address', 'Start explicitly on both PCs each session. Use a private LAN or VPN address; address changes require pairing again. This delegates tasks without pooling GPU memory.'],
    ['Create invitation / pair', 'Use the other PC’s invitation to approve delegation in both directions. Keep the invitation private.'],
    ['Send bridge job', 'Sends the chosen prompt and settings. It does not send chat history, attachments, memories, Knowledge, LoRAs or training datasets.'],
    ['Results / Save to Chats', 'Bridge results stay in Bridge until you explicitly save them to Chats. Keep both apps open; reconnection resumes status without automatically replacing a disconnected job.'],
  ]]],
  queue: [['Requests', [
    ['Pending / active', 'GPU requests run in submission order. GIF exports use a separate serial CPU queue that can run alongside GPU work.'],
    ['Progress / wait estimate', 'Distinguishes queue waiting from running, loading and saving. Settings, model loading and hardware affect estimates.'],
    ['Cancel / Stop', 'Cancels waiting work or asks an active worker to stop. The next job in that lane waits for the worker to exit.'],
    ['Waiting chat prompts', 'Join the shared queue after earlier replies are saved so they receive the latest chat context.'],
    ['Open result', 'Returns to the submitting chat or image view; GIF outputs return to GIF Maker. Completed, cancelled and failed jobs retain their displayed status.'],
    ['Reset / Unload', 'Cancels queued/active runtime work and waits for workers before unloading. Correct missing models or invalid inputs before retrying.'],
    ['Queue lifetime', 'The queue lasts for the backend run. Closing or restarting clears pending work; keep the app open to finish it.'],
    ['Timing report', 'Stores the last 200 observed requests in local UI storage. Only successful runs update averages; the report retains initial estimates for comparison.'],
  ]]],
};
