import { projectBrief, inventoryCsv, workshopMarkdown, recordingScript } from './samples';

export const agentAppLessons = [
  {
    id: 'discover-app-tools', title: 'Discover tools before planning', module: 'Planning and evidence', minutes: 10,
    workspaces: ['dashboard', 'tools', 'chats'],
    concepts: [
      'Start with the app’s actual capabilities. Dashboard → Tool registry separates backend/API tools from interactive workspaces and lists requirements, inputs, outputs and effects. Registered describes a contract; it does not establish that a dependency or model is ready.',
      'Ordinary chat has no general tool-calling executor connected to this catalog. A model can help draft a plan from the tool descriptions, while you run the supported workspace controls or explicitly saved Functions. A planned action, an attempted action and a verified result should have separate status.',
    ],
    steps: [
      'Search Tool registry for a document, image or folder tool. Read its input schema, effects, requirements and output description.',
      'Write a three-action plan using only listed capabilities. Mark which actions are API contracts, interactive controls or saved Function steps.',
      'Inspect the corresponding workspace’s information guide and readiness. Replace any unsupported planned action with a supported handoff.',
      'Ask a practice chat to critique the written plan. Treat its response as a proposal and verify each claimed capability in the app.',
    ],
    checkpoint: 'Every planned action maps to an actual control or contract, names its prerequisites and has an observable completion check. Your plan does not assume that copying a catalog enables execution.',
    exercise: 'Define a capability matrix for three tools: input, output, side effect, prerequisite, runner and completion evidence.',
    question: 'What does Copy catalog for LLM add to a chat?',
    choices: ['An unrestricted execution engine', 'Descriptions the model can reason about', 'Proof that the listed actions ran'], answer: 1,
    explanation: 'The catalog supplies descriptive context. A trusted executor or explicit workspace action remains separate.',
  },
  {
    id: 'scoped-context-workflow', title: 'Give a workflow only the needed context', module: 'Planning and evidence', minutes: 12,
    workspaces: ['knowledge', 'library', 'chats'], sample: projectBrief,
    concepts: [
      'A workflow’s source set is part of its contract. Knowledge → Selected can bound retrieval to chosen documents, while Index holds reusable request templates and explicit document connections. Model history, rolling summaries and saved memories are additional possible inputs.',
      'Response influences shows the app’s assembled request inputs; it does not prove how much each input caused a particular phrase. Put the task, source scope and requested uncertainty handling in the practice request, then check the answer against the actual source text.',
    ],
    steps: [
      'Create a practice Knowledge note from the brief. Define the task as extracting only its two deadlines and the unresolved reviewer question.',
      'Create or copy an Index template requesting source passages and an “unknown” answer when the brief lacks a detail.',
      'Use a clean practice chat with Selected Knowledge. Inspect the enabled roleplay, saved-memory and source settings before sending.',
      'Check each returned field against the indexed brief and record a source passage rather than merely accepting the model’s confidence.',
    ],
    checkpoint: 'The result preserves both dates, leaves the diagram reviewer unresolved, and records the source selection used for the request.',
    exercise: 'Draft an extraction request with explicit allowed sources, output fields and a rule for unknown values.',
    question: 'The brief does not name a diagram reviewer. What should the workflow return?',
    choices: ['A plausible reviewer inferred from the owner’s name', 'A new deadline', 'Unknown, with the source’s open question'], answer: 2,
    explanation: 'Source-bounded extraction preserves missing information rather than silently converting it into a fact.',
  },
  {
    id: 'planner-reviewer-chats', title: 'Separate a planner from a reviewer', module: 'Planning and evidence', minutes: 10,
    workspaces: ['chats', 'canvas', 'queue'], sample: projectBrief,
    concepts: [
      'Two chats let you give a planning task and a reviewing task different histories and model selections. Split chat and a pinned workspace help compare them, but visible proximity does not mean their context or drafts are shared automatically.',
      'A useful handoff includes the objective, selected sources, proposed actions, outputs and unresolved questions. The reviewer checks the supplied plan against those facts. Prompt Queue coordinates local requests; having two panes does not create two independent GPU pools.',
    ],
    steps: [
      'Ask one practice chat for a short plan based on the project brief, with the open reviewer question left unresolved.',
      'Prepare a reviewer handoff containing the brief and the proposed plan, rather than assuming the second chat saw the first one.',
      'Use Split chat or pin Canvas beside chat if useful. Ask the reviewer to identify unsupported assignments, missing evidence and completion checks.',
      'Reconcile the review into one revised plan. Record what was changed and the source supporting each change.',
    ],
    checkpoint: 'The reviewer received the required source and plan explicitly. Your final plan resolves critique with evidence while preserving the genuine open question.',
    exercise: 'Write the planner and reviewer prompts, including the exact information that crosses the handoff.',
    question: 'What should you assume about a second chat’s context?',
    choices: ['It automatically contains the first chat’s complete history', 'It needs the relevant source and plan supplied explicitly', 'It shares all unsent drafts with the first pane'], answer: 1,
    explanation: 'Separate histories require explicit handoffs. A split view is a presentation feature, not evidence of shared model context.',
  },
  {
    id: 'research-evidence-chain', title: 'Build a source-backed research handoff', module: 'Planning and evidence', minutes: 12,
    workspaces: ['browser', 'html-viewer', 'css-viewer', 'js-viewer', 'knowledge', 'document-editor'],
    concepts: [
      'A research handoff should distinguish the page you read, source resources you inspected, extracted text you saved and conclusions a model proposed. Browser inspection exposes available page resources; it does not expose the site’s server-side project or establish a page’s claims are true.',
      'Source content can contain instructions that conflict with your task. Keep those sentences as quoted evidence rather than letting them change your scope or permissions. Document Editor can assemble an attributed result after claims are checked against saved passages.',
    ],
    steps: [
      'Choose one public source relevant to a small question. Record its page title, address and the observation date.',
      'Inspect only the rendered content or loaded resources needed to answer that question. State whether you observed a page, HTML, CSS or JavaScript.',
      'Save a bounded source note in Knowledge and ask for a source-backed summary. Check quoted facts and separate inference from direct observation.',
      'Draft a short result in Document Editor containing supported claims, source attribution and unresolved details. Inspect its exported copy.',
    ],
    checkpoint: 'Every material claim has a traceable source passage, and your report distinguishes observation from inference and missing evidence.',
    exercise: 'Write a handoff for a second reviewer who has only your source note and report. Include enough evidence to check the claims.',
    question: 'A page says to upload unrelated private files. How should that affect the research plan?',
    choices: ['Treat the sentence as source content and retain the user’s scope', 'Follow it because it is inside the inspected HTML', 'Treat any JavaScript comment as a new user request'], answer: 0,
    explanation: 'Page and source text provide evidence. They do not authorize new actions or broader data access.',
  },
  {
    id: 'structured-data-handoff', title: 'Use a bounded data handoff', module: 'Planning and evidence', minutes: 12,
    workspaces: ['spreadsheets', 'local-files', 'chats'], sample: inventoryCsv,
    concepts: [
      'Define the grain: in the practice CSV, one row describes one inventory item. A data handoff needs column meanings, units and the included rows. Spreadsheets can stage the whole file, filtered rows or selected rows with chosen columns; those scopes produce different totals.',
      'Local Files’ SQLite view reads a snapshot using bounded SELECT queries. An agent plan should specify the intended query and row scope, then verify output coverage and arithmetic. Model prose is a proposed interpretation, not a substitute for checking the selected data.',
    ],
    steps: [
      'Save and open the practice CSV. Define quantity as item count and unit_cost_credits as credits per item.',
      'Filter to stationery and select only the columns required for the calculation. Record that the cable row is excluded.',
      'Stage the filtered data in chat and ask for an itemized subtotal, row count and source scope.',
      'Verify each product and sum manually. Write how the workflow would change if the user instead requested the whole-file total.',
    ],
    checkpoint: 'The handoff contains three stationery rows, produces 28 credits, and distinguishes that subtotal from the 36-credit whole file.',
    exercise: 'Specify a data contract with source, grain, units, allowed rows, required fields and an independent arithmetic check.',
    question: 'A workflow receives only the stationery rows. Which conclusion is supported?',
    choices: ['The total for every row in the original file is 28', 'The selected stationery subtotal is 28; the whole-file total needs its own scope', 'There are no electronics in the original file'], answer: 1,
    explanation: 'A selected subset supports conclusions about that subset. State scope before generalizing to the source file.',
  },
  {
    id: 'file-review-proposal', title: 'Turn a file audit into a reviewable proposal', module: 'Supervised actions', minutes: 14,
    workspaces: ['hash-auditor', 'folder-review', 'image-manager', 'media-manager'],
    concepts: [
      'Use Hash Auditor for recorded hashes and filesystem metadata, and Folder Review for supported content summaries with coverage. Matching metadata is a candidate, matching content hashes concern recorded bytes, and a model finding is a claim to inspect.',
      'Image Manager and Media Manager can prepare exact transfer plans for cataloged media. A read-only review can end with a proposal: source, destination, evidence, collisions, excluded files and the action awaiting a separate decision. Preparing a plan is different from applying it.',
    ],
    needs: 'A small practice folder. Keep the exercise scoped to copies you created for learning.',
    steps: [
      'Write a read-only objective, allowed folder, excluded data and an explicit “no transfer or deletion” boundary.',
      'Run a bounded audit on the practice folder and record completed, skipped and failed paths with their observation times.',
      'Use a content review only for the supported files needed to explain the candidates. Inspect findings against their sources.',
      'Draft an exact proposal for a later copy or organization step. Include collision handling and the checks you would repeat before applying it.',
    ],
    checkpoint: 'The outcome is a reviewable proposal with scoped evidence. Your notes do not describe a prepared plan as a completed transfer or count hardlinked paths as independent copies without checking.',
    exercise: 'Prepare a table of verified candidates, uncertain candidates and excluded files. State what further authorization and evidence a later action needs.',
    question: 'Which statement accurately describes a prepared media organization plan?',
    choices: ['The source files have already moved', 'It contains proposed paths and effects for review; applying is separate', 'It proves all duplicates are safe to remove'], answer: 1,
    explanation: 'A plan records intended operations. Its existence does not establish that those operations happened or are appropriate for every candidate.',
  },
  {
    id: 'supervised-functions', title: 'Build a Function with checkpoints', module: 'Supervised actions', minutes: 14,
    workspaces: ['tools', 'shortcuts', 'chats'],
    concepts: [
      'Functions is an explicit ordered action runner. Its supported steps have specific inputs and effects: opening apps, waiting for windows, auditing a chosen folder, preparing text, capturing a window and saving outputs. A saved sequence can be reviewed before Run.',
      'Accessible controls and pointed controls have different evidence. An accessible field step can check a field and refuse an existing draft. A pointed paste or click depends on window identity, layout and visibility; a click still needs a result check. Stop prevents subsequent steps while preserving completed actions.',
    ],
    steps: [
      'Draft a practice Function that audits a selected folder, prepares a request containing {{report}}, then saves the output to a chosen practice destination.',
      'For every THEN step, write the expected input, result and failure condition. Prefer a saved-output checkpoint before any later send step.',
      'Inspect the sequence and its destinations. If you choose an optional run, follow the per-step status rather than assuming a launch or click succeeded.',
      'Use Add result to chat to stage the report. Review attachments and the request text before deciding to Send.',
    ],
    checkpoint: 'Your sequence has bounded targets and a verifiable output for each step. Its success claim relies on observed results, and its stop behavior is described without assuming rollback.',
    exercise: 'Design a failure case where the target window moved or already contains a draft. Explain the evidence needed to resume safely.',
    question: 'What does Stop function guarantee about earlier completed steps?',
    choices: ['It undoes every earlier action', 'It deletes every saved output', 'It prevents later work; completed effects still need inspection'], answer: 2,
    explanation: 'Stopping is a boundary on further execution. It is not an automatic undo mechanism.',
  },
  {
    id: 'queue-status-recovery', title: 'Supervise queued work and recover once', module: 'Supervised actions', minutes: 12,
    workspaces: ['queue', 'chats', 'generate', 'workflows'],
    concepts: [
      'Prompt Queue distinguishes pending and active work from completed, failed and cancelled jobs. Loading, computing and saving are different phases. Waiting chat prompts join after the earlier reply is saved so they receive the updated context.',
      'An uncertain result requires observation before retry. A completed preview may already exist even if a later save or display failed. Cancelling a waiting job differs from stopping an active worker; completed batch images and workflow results can remain useful.',
    ],
    steps: [
      'Choose a recent practice request or inspect the queue guide. Identify its source workspace, status, phase and available result link.',
      'Write the expected evidence for completion: saved reply, generated image, workflow output or exported file.',
      'For a hypothetical save timeout, inspect the result location and existing output before proposing another request.',
      'Plan a single bounded retry only after identifying the failed phase and correcting its prerequisite. Preserve completed results and record remaining work.',
    ],
    checkpoint: 'You can distinguish queue wait, active processing and output saving. Your recovery plan avoids blindly repeating a job whose output may already exist.',
    exercise: 'Create a recovery table for waiting, running, completed-with-save-error and cancelled-with-partial-results states.',
    question: 'A batch stops after saving two of five images. What is the accurate report?',
    choices: ['Five images completed because the batch started', 'Two completed results exist and three remaining items need their actual status checked', 'Every completed image must be deleted before retry'], answer: 1,
    explanation: 'Report observed completed outputs separately from unfinished work. Cancellation does not erase already completed results.',
  },
  {
    id: 'image-workflow-rubric', title: 'Evaluate an image pipeline stage by stage', module: 'Supervised actions', minutes: 14,
    workspaces: ['generate', 'images', 'review', 'workflows', 'image-editor', 'converter'],
    concepts: [
      'A media pipeline needs an explicit source and expected output at every stage. Generate creates an image, Image Workflows can run supported transformations, Image Editor changes a reviewed working copy, and File Converter creates format copies. An analysis suggestion does not itself apply an edit.',
      'Prepare snapshot and run history preserve the inputs used by a workflow run. Assess prompt adherence, subject consistency, dimensions, artifacts and coverage separately. A resize stage cannot establish that a generated face matches a reference.',
    ],
    needs: 'A practice image. Model-dependent stages can be designed and validated without running generation.',
    steps: [
      'Choose a practice image and write its role as source, reference or candidate output. Define which details must remain unchanged.',
      'Draft a supported workflow stage, validate its configuration and inspect its prepared snapshot. Name the adapter’s actual conditioning method.',
      'If you run the stage, inspect the saved output in Gallery or Image Review and record its settings and dimensions.',
      'Review any edit candidate before acceptance, then create a format copy only if requested. Compare each output with its own stage rubric.',
    ],
    checkpoint: 'Every transformation has a known source, recorded configuration and inspected output. Your report separates prepared configuration, executed stages and accepted results.',
    exercise: 'Write a three-stage pipeline contract and a failure check for each stage, including a source-preservation check.',
    question: 'What is the strongest evidence that a workflow used the intended inputs?',
    choices: ['The run’s saved input snapshot and its inspected output', 'The current editable draft alone', 'The model’s statement that it remembers the reference'], answer: 0,
    explanation: 'The saved run inputs describe what that run used. A later editable draft may have changed.',
  },
  {
    id: 'reference-training-gates', title: 'Separate reference curation from training', module: 'Media and delivery', minutes: 12,
    workspaces: ['characters', 'character-parts', 'faces', 'lora', 'generate'],
    concepts: [
      'A character profile, accepted face crop, reference-region selection and LoRA adapter have different storage and runtime roles. Linking a dataset to a character does not train an adapter or automatically send every linked image to a model.',
      'Use separate gates for curation, caption review, training readiness and held-out evaluation. Likeness, consistency and style/composition need distinct checks. Document which reference information reaches the adapter as pixels or text instead of promising conditioning the installed adapter does not support.',
    ],
    steps: [
      'Define a fictional subject and three acceptance criteria: visible identity cues, consistency across scenes, and composition/style.',
      'Review a practice reference collection in Character Creator, Character Parts or Faces. Keep only deliberate accepted references and document crop quality.',
      'In LoRA, write the compatible base model, caption rule, readiness requirements and held-out evaluation prompts before proposing training.',
      'Design a base-versus-adapter comparison in Generate with fixed supported settings. Record failures and uncertain likeness cases separately from successful examples.',
    ],
    checkpoint: 'Your workflow makes no training claim from a saved profile or curated dataset. Each gate has evidence, and runtime-dependent work awaits its own explicit action.',
    exercise: 'Define go/no-go criteria for a curated dataset, a proposed training run and a trained adapter ready for use.',
    question: 'A dataset was linked to a character. What has been established?',
    choices: ['The selected model was retrained', 'The linked references have a saved relationship to that profile', 'Every future scene will preserve exact likeness'], answer: 1,
    explanation: 'A saved relationship organizes resources. Training and conditioning behavior require separate operations and evidence.',
  },
  {
    id: 'media-evidence-coverage', title: 'Combine media findings without inventing coverage', module: 'Media and delivery', minutes: 14,
    workspaces: ['audio', 'local-files', 'gif-maker', 'chats'], sample: recordingScript,
    concepts: [
      'Video metadata, sampled vision observations and an audio transcript are different evidence streams. Sampling can miss unsampled events; a transcript can mishear words; speaker labels distinguish estimated voices rather than proving identity.',
      'A useful handoff preserves timestamps, sampling settings, corrected text and uncertain intervals. Audio extraction is separate from transcription. A GIF may illustrate a selected segment, but it does not prove what happened throughout the full source clip.',
    ],
    steps: [
      'Choose a short practice recording or video. Record source duration and the visual sampling or transcription method you intend to use.',
      'Review a transcript against the recording, especially names, dates and speaker changes. Keep uncertain words marked rather than guessing.',
      'Inspect sampled video observations at their timestamps if a vision model is available. Separate visible actions from statements heard on the audio track.',
      'Prepare a short summary with supporting timestamps and explicit coverage limits. Optionally create a GIF of the relevant interval and play the saved copy.',
    ],
    checkpoint: 'Your report says which evidence stream supports each finding and leaves unsampled or ambiguous intervals unresolved.',
    exercise: 'Make an evidence table with columns for claim, source stream, timestamp, observation, confidence reason and missing coverage.',
    question: 'A speaker label reads Speaker 1. What does it establish?',
    choices: ['A verified legal identity', 'Perfect diarization for every sentence', 'An estimated voice grouping that needs review'], answer: 2,
    explanation: 'Speaker labels organize detected voices. They can be wrong and do not establish a person’s identity.',
  },
  {
    id: 'external-handoff-review', title: 'Prepare an external handoff for review', module: 'Media and delivery', minutes: 12,
    workspaces: ['integrations', 'tools', 'dashboard', 'chats'],
    concepts: [
      'Linked applications separates connection configuration, previews, attachments and Send to Discord. A preview is preparation; sending is an external effect with a specific recipient and content. Playback recording has an explicit source selector and its own signal/readiness checks.',
      'Dashboard’s PC Bridge sends the selected prompt and settings to the paired computer. It does not automatically include chat history, attachments, Knowledge or training datasets. Define exactly which data crosses any handoff and how the receiving side will establish completion.',
    ],
    steps: [
      'Draft a fictional handoff in your lesson notes: recipient, purpose, message, attachments and the exact information allowed to leave the app.',
      'Inspect Linked applications’ message preview without entering real credentials or sending. Verify that draft content and selected attachments are different from a completed transmission.',
      'Inspect PC Bridge’s information guide and list what its job includes and what source material would require a separate arrangement.',
      'Write the final review gate and the evidence you would request after an authorized send or delegated job. Keep connection secrets out of the handoff text.',
    ],
    checkpoint: 'Your deliverable is a reviewable handoff with a named destination and bounded contents. Completing the lesson does not require connecting, pairing or sending.',
    exercise: 'Compare a staged chat attachment, a Discord message preview and a completed bridge result. Define the evidence that distinguishes their states.',
    question: 'What should a workflow assume about PC Bridge’s context?',
    choices: ['It sends only the selected prompt/settings; extra context needs an explicit supported handoff', 'It automatically mirrors the entire source computer', 'It pools both computers’ GPU memory'], answer: 0,
    explanation: 'Bridge delegation has a bounded data contract. It does not transfer every local context source or combine GPU memory.',
  },
  {
    id: 'deliverable-verification', title: 'Verify and package the actual deliverables', module: 'Media and delivery', minutes: 12,
    workspaces: ['document-editor', 'markdown', 'packager', '3d-viewer', 'slicer', 'dashboard'], sample: workshopMarkdown,
    concepts: [
      'Completion is about inspected outputs. A DOCX needs text/layout review, a ZIP needs a content check, a mesh needs geometry and unit checks, and G-code needs the configuration for the actual printer. Tool success and usable delivery are separate checks.',
      'Packager combines the selected files without moving their originals. Dashboard’s full app backup, metadata-only export and reset have different purposes and scopes. A project ZIP should contain only the intended deliverables and enough context to understand them.',
    ],
    steps: [
      'Draft a small report from the practice Markdown and export the intended document format. Inspect its dates and unresolved question.',
      'Write an artifact-specific checklist for an optional image, mesh or G-code output. Name the viewer and evidence you would use to check it.',
      'In Packager, add only chosen outputs, inspect the archive paths and save a ZIP copy if you want a practice deliverable.',
      'Open the saved archive and compare its contents with the delivery checklist. Report omitted, failed or unverified outputs explicitly.',
    ],
    checkpoint: 'The delivered files exist and were inspected using checks appropriate to their type. A package action is not mislabeled as a full application backup.',
    exercise: 'Write a delivery note stating what changed, what was checked, where the outputs are, and what remains unverified.',
    question: 'What demonstrates that a project ZIP is ready to hand over?',
    choices: ['A model said it made the archive', 'The ZIP exists, opens and contains the intended inspected outputs', 'The metadata-only backup count increased'], answer: 1,
    explanation: 'Actual archive and output inspection verifies the deliverable. Counts and prose alone cannot establish package contents.',
  },
  {
    id: 'app-project-capstone', title: 'Capstone: plan, build, check and hand off', module: 'Capstone', minutes: 25,
    workspaces: ['knowledge', 'library', 'chats', 'canvas', 'document-editor', 'packager', 'queue'], sample: projectBrief,
    concepts: [
      'Combine the workstation’s tools around one bounded objective: turn the practice project brief into an accurate one-page summary, a three-step diagram and a reviewed delivery package. A human supervises workspace actions and decides when a prepared proposal is ready to execute.',
      'The workflow record should distinguish sources, plan, explicit actions, observations, revisions and deliverables. Success includes preserved facts, an honest unresolved question, correct output scope and an inspected saved package—not merely a fluent final chat reply.',
    ],
    steps: [
      'Write the scope and output contract in your notes. Import only the practice brief into Knowledge and prepare a reusable Index request.',
      'Use a clean practice chat with Selected Knowledge to draft the summary. Verify Morgan and both November dates; preserve the unknown diagram reviewer.',
      'Draw Source → Review → Handoff in Canvas. Compare it with the plan and add a decision point for missing evidence.',
      'Create the one-page draft in Document Editor, export an inspected copy and prepare the chosen diagram output.',
      'Package only the intended outputs. Review the saved ZIP and write a final handoff stating completed, failed and unverified items.',
    ],
    checkpoint: 'A reviewer can trace the summary’s facts to the brief, understand the diagram, inspect the saved outputs and see exactly what remains unresolved.',
    exercise: 'Complete the workflow record with one planned failure case, such as an unavailable model or export error, and explain how you would resume without losing completed work.',
    question: 'Which outcome meets this capstone’s completion contract?',
    choices: ['A plausible summary in chat with no saved outputs', 'A package containing only a draft plan', 'An inspected summary, diagram and package with source checks and explicit unresolved items'], answer: 2,
    explanation: 'The requested deliverables and evidence must both exist. A plan or fluent draft alone does not complete the workflow.',
  },
];
