import { projectBrief, inventoryCsv, workshopMarkdown, sampleHtml, recordingScript, cubeStl } from './samples';

export const universityAppLessons = [
  {
    id: 'workspace-tour', title: 'Find your way around the workstation', module: 'Workspace basics', minutes: 8,
    workspaces: ['dashboard', 'tools', 'shortcuts', 'break-room'],
    concepts: [
      'A workspace groups tools for a particular job. The sidebar opens those workspaces; the information button explains the controls in the active one. Workspace options can pin a supported workspace beside chat, so you can read a reference while asking questions.',
      'Dashboard shows services, hardware readings, compatibility and a tool catalog. A catalog entry describes a feature; its requirements tell you what else it needs. Functions holds custom navigation buttons and explicitly run action sequences. Shortcut Registry is a searchable reference for keyboard actions.',
    ],
    steps: [
      'Open Dashboard and find the selected model, available memory and compatibility information. Write down one ready feature and one requirement you would need to check.',
      'Open Shortcut Registry and search for an action you use, such as Find. Compare its application name with the application where you intend to use it.',
      'Open Functions and inspect Add Button. A workspace destination makes a navigation shortcut; saving a button is separate from pressing it.',
      'Use the app’s Timer for a short study session. Break Room provides a local matching game when you want a pause.',
    ],
    checkpoint: 'You can locate a workspace, open its information guide, and distinguish a listed feature from a feature whose prerequisites you have checked.',
    exercise: 'Create a three-step route for a task you often do: where you would check readiness, where you would work, and where you would inspect the result.',
    question: 'Dashboard lists a tool as registered. What does that establish?',
    choices: ['Every model can execute it from chat', 'The app has that tool contract; its prerequisites still need checking', 'The requested job has already completed'], answer: 1,
    explanation: 'Registration describes the app’s available contract. It does not prove readiness, execution or a completed result.',
  },
  {
    id: 'chat-controls', title: 'Choose a model and manage a chat', module: 'Workspace basics', minutes: 10,
    workspaces: ['chats', 'dashboard', 'queue'],
    concepts: [
      'The chat model selector chooses the installed Ollama model for your next message. A vision model can inspect an attached image; a text-only model works with text. Image generation has a separate model selector in Generate.',
      'Response length reserves reply tokens. Temperature, Top P and Top K affect how the model chooses wording; they do not supply facts. Stop interrupts an active reply, while Cancel waiting prompt removes work that has not started. Saved chat history and the context supplied with one request are different things.',
    ],
    needs: 'An installed chat model for the optional comparison. You can inspect the controls and write your plan without running a request.',
    steps: [
      'Open Chat and its information guide. Find Chat model, Response length and Temperature; write what each one changes.',
      'Start a new practice chat. Ask for three names for a fictional workshop, then compare two response-length settings with the same request.',
      'Inspect Response influences and the context estimate. Note which source or memory settings are enabled before interpreting the reply.',
      'Open Prompt Queue to distinguish waiting, running and completed requests. Rename the practice chat so you can find the comparison later.',
    ],
    checkpoint: 'Your notes name the selected model, the one setting you changed, and an observable difference in the two replies. A confident reply is still checked against its sources.',
    exercise: 'Explain why a longer reply limit, a vision-capable model, and a higher Temperature solve three different problems.',
    question: 'Which choice lets the model inspect an attached photograph?',
    choices: ['A vision-capable chat model', 'A longer response limit alone', 'A higher Repeat Penalty'], answer: 0,
    explanation: 'Image understanding requires a model with vision support. Sampling and length settings do not add that capability.',
  },
  {
    id: 'knowledge-index-project', title: 'Build a small Knowledge project', module: 'Sources and documents', minutes: 12,
    workspaces: ['knowledge', 'library', 'chats'], sample: projectBrief,
    concepts: [
      'Knowledge stores source text and organizes it as nodes and explicit connections. A Note, Project or Reference node describes how you organize material. Its indexed text is what retrieval searches; a line in the graph records a saved connection.',
      'Index stores reusable prompts and reference entries. You can link an Index entry to Knowledge documents. In Chat, Knowledge Off, All and Selected control which indexed sources may supply relevant excerpts. Selecting a document supplies context; it does not train a model.',
    ],
    steps: [
      'Copy the practice brief and create a Knowledge note with a distinctive name such as Workshop practice brief. Inspect its indexed text.',
      'Create a second note for the open diagram-review question and connect the two documents explicitly.',
      'In Index, add a reusable request: “List the project dates and open questions, quoting the source for each.” Link it to the practice document if you want a reusable reference.',
      'In a new chat, choose Knowledge → Selected and select the practice brief. Ask for the draft-review date and verify the answer against the stored text.',
    ],
    checkpoint: 'The brief says 6 November 2026 for draft review and 13 November 2026 for final handoff. The diagram reviewer remains an open question; the model should not invent a name.',
    exercise: 'Record one supported answer and one detail the source cannot answer. Explain why a graph connection is different from evidence that an excerpt was used.',
    question: 'What supplies the facts for a Knowledge-backed answer?',
    choices: ['The node’s color', 'The number of visible graph connections', 'The relevant indexed text supplied with the question'], answer: 2,
    explanation: 'Graph layout helps you organize sources. Retrieval uses their text, and the answer must be checked against that text.',
  },
  {
    id: 'documents-markdown', title: 'Write and review a document', module: 'Sources and documents', minutes: 10,
    workspaces: ['document-editor', 'markdown', 'chats'], sample: workshopMarkdown,
    concepts: [
      'Document Editor is for a formatted working document: headings, text, lists, basic tables and pictures, followed by Export DOCX. Its page-shaped view approximates layout; it is not proof of exact pagination in another editor.',
      'Markdown stores readable plain text with lightweight formatting such as # headings and list markers. Markdown Viewer switches between source and rendered text. Chat’s /docx flow can create a document, but you still review its words and formatting.',
    ],
    steps: [
      'Paste the practice Markdown into Markdown Viewer’s Plain Text view, then choose Show Markdown and identify the two dates and open question.',
      'In Document Editor, create a practice draft with a heading, a short summary and a basic table containing the two dates.',
      'Review the text, use Undo/Redo on a small edit, and export a DOCX copy when you want to keep it.',
      'Compare the exported document’s actual contents with the practice brief. Save viewer drafts before refreshing or closing the app.',
    ],
    checkpoint: 'Both formats retain the correct dates and distinguish the open question from an assigned task. Your exported DOCX is a separate file you can inspect.',
    exercise: 'Explain when you would choose Markdown, when you would choose DOCX, and what you would verify after an AI creates either one.',
    question: 'What is the best completion check for a generated project document?',
    choices: ['The model said “done”', 'Its text, dates and exported file match the requested result', 'The draft has many headings'], answer: 1,
    explanation: 'Inspecting the saved artifact establishes what was produced. A success sentence or attractive layout cannot establish factual correctness.',
  },
  {
    id: 'csv-sqlite', title: 'Read a table and verify its totals', module: 'Sources and documents', minutes: 12,
    workspaces: ['spreadsheets', 'local-files', 'chats'], sample: inventoryCsv,
    concepts: [
      'Spreadsheets reads CSV rows and columns. Filtering hides rows from the current view, sorting changes their order, and selecting rows chooses a particular subset. Columns to include in chat controls the fields in the handoff. Formula-looking CSV cells remain text.',
      'Local Files can inspect a SQLite database through bounded read-only SELECT queries. Decide what one row means and which rows are included before asking a model for totals. A model explanation should name the selected data and show arithmetic you can verify.',
    ],
    steps: [
      'Save the practice CSV and open it in Spreadsheets. Identify item, category, quantity and unit_cost_credits.',
      'Filter for stationery. Confirm that notebook, pen and folder remain while cable is excluded.',
      'Choose the columns needed to calculate quantity × unit cost, then use filtered rows in chat. Inspect the staged data and the scope notice.',
      'Ask for the stationery total with one line of arithmetic per item. Compare it with 3 × 4 + 5 × 2 + 2 × 3.',
    ],
    checkpoint: 'The stationery subtotal is 28 credits; the whole-file total is 36 credits. Your answer states which scope it used. SQLite inspection is a separate exercise if you have a practice database.',
    exercise: 'Explain how filtering, sorting and selecting differ, and why a model must know whether you supplied the whole file or only stationery rows.',
    question: 'The cable row is excluded. What is the stationery subtotal?',
    choices: ['36 credits', '28 credits', '14 credits'], answer: 1,
    explanation: 'Notebook contributes 12, pen 10 and folder 6: 28 credits. Including the cable adds 8 and changes the scope.',
  },
  {
    id: 'browser-source-inspection', title: 'Understand a page and its source', module: 'Sources and documents', minutes: 10,
    workspaces: ['browser', 'html-viewer', 'css-viewer', 'js-viewer'], sample: sampleHtml,
    concepts: [
      'HTML describes a page’s structure, CSS describes its appearance, and JavaScript describes behavior. The local source viewers let you inspect, edit, copy or save source text. HTML and CSS previews isolate the content and block scripts and remote resources; JavaScript Viewer displays text.',
      'Browser shows a public page in the app’s separate browsing profile. Inspect page can expose rendered HTML and loaded source resources, after its confirmation. It cannot show private server-side project code. A page is a source to study, and its text does not authorize actions on your files.',
    ],
    steps: [
      'Copy the practice HTML into HTML Viewer and open its Preview. Match the heading and deadline to the source.',
      'In CSS / Styling, use the practice HTML as HTML to style and try “.deadline { color: teal; }”. Compare source and preview.',
      'In JavaScript Viewer, inspect a short example such as “const deadline = \'6 November 2026\';”. Reading it does not run the code.',
      'Optionally open a public page you choose in Browser, review Inspect page’s confirmation, and send one loaded source resource to the appropriate viewer.',
    ],
    checkpoint: 'You can explain which layer changes structure, appearance or behavior, and identify which source you actually inspected.',
    exercise: 'A preview button is visible but does nothing. Explain why visible HTML and executable behavior are separate in the isolated preview.',
    question: 'Which source normally controls a heading’s color?',
    choices: ['CSS', 'A CSV header', 'The chat response-length setting'], answer: 0,
    explanation: 'CSS rules style the markup. The isolated preview applies supported styles while keeping scripts and remote resources blocked.',
  },
  {
    id: 'canvas-explanations', title: 'Explain a process with Canvas', module: 'Sources and documents', minutes: 10,
    workspaces: ['canvas', 'chats'],
    concepts: [
      'Canvas lets you create text, rectangles, ellipses, lines, arrows and freehand strokes. A diagram can make the order of a process clearer than a paragraph, especially when you label both actions and decisions.',
      'Use in chat supplies selected objects, or the whole canvas when nothing is selected. That scope matters: a request about one selected object should not imply that the model saw every part of the drawing. Undo/Redo helps compare edits.',
    ],
    steps: [
      'Create three labeled shapes: Source, Review and Saved result. Add arrows from left to right.',
      'Select Review and use the canvas in chat. Inspect the supplied scope before asking for a clearer label.',
      'Compare a request about the selected object with one about the whole process. Keep any proposed change explicit.',
      'Use Copy Canvas to inspect the artwork without the surrounding controls and check that every arrow has a clear meaning.',
    ],
    checkpoint: 'Your diagram shows a readable three-step process, and your notes record whether you supplied a selection or the whole canvas.',
    exercise: 'Draw a decision that branches between “evidence sufficient” and “need another source.” Label the evidence needed before taking either branch.',
    question: 'What does Use in chat supply when objects are selected?',
    choices: ['Every file on disk', 'Only the selected canvas objects', 'The model’s internal network'], answer: 1,
    explanation: 'Selected objects define the canvas handoff. Clearing selection lets the whole canvas be supplied instead.',
  },
  {
    id: 'generate-review-images', title: 'Generate an image and compare settings', module: 'Images and training', minutes: 12,
    workspaces: ['generate', 'images', 'review', 'queue'],
    concepts: [
      'Generate combines an image model, prompt, dimensions and supported generation settings. Steps control iterations for compatible models; guidance controls how strongly a compatible model follows the prompt. Use that model’s guide and defaults because models do not all support identical settings.',
      'A seed initializes generation randomness where supported. Keep the model, seed, prompt and dimensions fixed when studying one setting. Prompt Queue reports waiting and running work; completed batch previews remain available while later images run.',
    ],
    needs: 'An installed compatible image model for generation. Use the preparation steps alone if the runtime is not ready.',
    steps: [
      'Choose an installed image model, LoRA → None, and the model’s default settings. Use a neutral prompt such as “a blue ceramic mug on a wooden desk, soft window light”.',
      'Record the settings and generate one image. Inspect its completed preview and actual dimensions in Generate or Image Gallery.',
      'Change one supported setting, such as steps or guidance, while keeping the others fixed. Compare prompt adherence and visible artifacts.',
      'Inspect Image Review for the available prompt and generation metadata. Name the two cases in your notes so you can reproduce the comparison.',
    ],
    checkpoint: 'You have two clearly recorded settings and observations tied to actual images. A fixed seed helps control randomness but is not a promise of identical pixels across every runtime.',
    exercise: 'Write a comparison rubric with three criteria: requested objects, composition, and visible defects. Record a disappointing result as carefully as a successful one.',
    question: 'Which comparison best isolates the effect of guidance?',
    choices: ['Change guidance while holding supported model, seed, prompt and dimensions fixed', 'Change every setting and the subject', 'Keep only the most attractive result'], answer: 0,
    explanation: 'Changing one supported setting gives you a clearer basis for interpreting the difference.',
  },
  {
    id: 'edit-organize-convert', title: 'Edit and organize image copies', module: 'Images and training', minutes: 12,
    workspaces: ['image-editor', 'converter', 'image-manager', 'media-manager'],
    concepts: [
      'Image Editor changes a working image and exports a copy. Fit is a preview scale; 100% lets you judge actual pixels. Rotation, adjustments and edit history let you compare changes before export.',
      'File Converter makes format copies. PNG can retain transparency, while JPG flattens it. Image Manager and Media Manager catalog selected folders and prepare file-operation plans. A scan, a duplicate finding and an applied move are three different outcomes.',
    ],
    needs: 'One disposable practice image and, for catalog practice, a small practice folder.',
    steps: [
      'Open the practice image in Image Editor. Rotate it once, compare at Fit and 100%, then undo the rotation.',
      'Apply one small adjustment and Export PNG with a distinct name. Compare source and exported dimensions.',
      'Open File Converter and create a JPG copy. If the image has transparency, inspect the flattened background.',
      'Scan only the practice folder in Image Manager or Media Manager. Inspect a copy/organization plan and its exact destinations before choosing whether to apply it.',
    ],
    checkpoint: 'The original is still available, exported copies are identifiable, and your notes distinguish catalog observations from actual file transfers.',
    exercise: 'Explain which format you would use for a transparent icon and how you would prove an organization plan used the intended source and destination.',
    question: 'What is the expected effect of converting transparent PNG content to JPG?',
    choices: ['It creates real transparency in JPG', 'It flattens transparency onto a background', 'It trains an image model'], answer: 1,
    explanation: 'JPG does not preserve the PNG transparency channel. Inspect the converter’s background result in the saved copy.',
  },
  {
    id: 'characters-image-workflows', title: 'Use characters and image workflows', module: 'Images and training', minutes: 14,
    workspaces: ['characters', 'character-parts', 'faces', 'workflows', 'generate'],
    concepts: [
      'Character Creator stores a profile with biography, notes and linked resources. Character Parts helps curate reference regions; Faces extracts and curates detections in a dataset. Saving or linking a reference is separate from training and from sending it to a model.',
      'Image Workflows runs ordered stages with explicit inputs and installed adapters. Validate checks a configuration; Prepare snapshot records its inputs without generating. Describe, resize and image-generation stages do different jobs. Adapter support determines how references are actually used.',
    ],
    needs: 'A fictional practice character and images you may use. Runtime-dependent stages can be planned without running them.',
    steps: [
      'Create a fictional character with two defining traits and one reference you can inspect. Keep profile text separate from claims about guaranteed likeness.',
      'Inspect Character Parts and Faces to identify how regions and accepted detections become curated references. Review a crop before keeping it.',
      'Draft an Image Workflow with a clearly assigned source and one supported stage, such as Lanczos resize. Identify its output and requirements.',
      'Validate and prepare a snapshot if the configuration is complete. Inspect the recorded inputs before explicitly choosing Run.',
    ],
    checkpoint: 'You can trace each stage to an explicit source and say whether you prepared a snapshot or completed a run. A saved character is not evidence of a trained adapter or guaranteed identity.',
    exercise: 'Plan two separate experiments: a close whole-image variation and the same fictional subject in a new scene. State how you would judge each one.',
    question: 'What does Prepare snapshot do?',
    choices: ['Starts training automatically', 'Prints the character', 'Records the configured workflow inputs without running generation'], answer: 2,
    explanation: 'Preparation produces a reviewable input snapshot. Run is a separate action that uses the required installed adapter.',
  },
  {
    id: 'lora-preparation', title: 'Understand LoRA before training', module: 'Images and training', minutes: 12,
    workspaces: ['lora', 'generate', 'dashboard'],
    concepts: [
      'A LoRA is an adapter trained for a compatible base model. Dataset images and captions describe what it learns; steps, learning rate and other settings control training. The small Neural Network demo computes fixed examples, while LoRA training adjusts an adapter.',
      'LoRA → New project separates the base model, training goal and analysis model. Analyze current dataset lets you review suggested captions before a training action. Edited captions are kept. Good preparation removes contradictory, irrelevant or poor-quality examples before spending training resources.',
    ],
    steps: [
      'Open LoRA and its information guide. Identify the base model, dataset, captions, learning rate and training controls.',
      'Write a fictional dataset plan with five candidate images and a caption rule. List which examples you would reject and why.',
      'Check compatibility and memory readiness in Dashboard. Estimate what you still need before choosing a real training run.',
      'In Generate, distinguish LoRA → None from a compatible trained adapter. Describe a later base-versus-adapter comparison with the same prompt and seed.',
    ],
    checkpoint: 'You have a dataset and validation plan, named prerequisites, and a proposed comparison. Completing this lesson does not require starting training or downloading a model.',
    exercise: 'Explain how a saved character profile, reference image and trained LoRA differ, then define two signs that your adapter overfits its examples.',
    question: 'What should you verify before using a trained LoRA?',
    choices: ['Only that its filename is short', 'That it is compatible with the selected base model and tested on held-out requests', 'That every training image has the same filename'], answer: 1,
    explanation: 'Compatibility determines whether the adapter can load; held-out requests test whether it helps beyond memorizing the training examples.',
  },
  {
    id: 'audio-transcription-speech', title: 'Transcribe, correct and speak', module: 'Audio, video and 3D', minutes: 12,
    workspaces: ['audio', 'chats'], sample: recordingScript,
    concepts: [
      'Transcription turns recorded speech into editable text. Audio and the chat microphone panel let you record or load audio, transcribe it, then review the result. Insert into message stages the edited text; Send is a separate action.',
      'Text-to-speech turns text into playback. Read aloud and cloned voices depend on the selected available engine. Separate speakers labels voices across a recording, but similar voices, noise and overlap can cause mistakes. Review names, dates and speaker labels before reuse.',
    ],
    needs: 'A microphone or short practice recording, plus an available transcription engine for the optional run.',
    steps: [
      'Read the practice script into a short recording in Audio, or load a recording you may use. Stop recording before transcription.',
      'Choose the available transcription settings, run Transcribe audio, and compare every name and date with the script.',
      'Correct the transcript, then copy/save it or insert it into a practice chat draft. Inspect the draft before choosing Send.',
      'Try read aloud for a short corrected passage if a voice is available. Inspect Stop and voice settings; automatic chat speech is an explicit preference.',
    ],
    checkpoint: 'Your corrected text preserves Morgan and both November dates. You can identify what was recorded, transcribed, staged and actually sent.',
    exercise: 'List three transcription errors that would change the meaning of this script and explain how you would catch each one.',
    question: 'What happens when you choose Insert into message after reviewing a transcript?',
    choices: ['It sends the chat automatically', 'It changes the installed model’s weights', 'It adds the edited text to the message draft for review'], answer: 2,
    explanation: 'Insertion stages text in the composer. Sending remains a separate action.',
  },
  {
    id: 'video-analysis-gifs', title: 'Study a video and make a GIF', module: 'Audio, video and 3D', minutes: 12,
    workspaces: ['local-files', 'gif-maker', 'audio'],
    concepts: [
      'Local Files reads video metadata and can sample moments for a vision model to analyze. Quick, Balanced, Detailed and Custom change coverage. Sampled observations cover those moments; an event between them can be missed.',
      'Audio can extract a video’s audio track for transcription. GIF Maker creates a selected segment or image animation with explicit dimensions, timing and output controls. A preview, sampled analysis and saved GIF each need their own completion check.',
    ],
    needs: 'A short practice clip you may use. Vision and transcription require their respective installed models; GIF export has its own readiness requirements.',
    steps: [
      'Open the clip in Local Files and record duration, dimensions and frame rate from Inspect metadata.',
      'Choose a sampling workload and focus question. If a vision model is ready, compare its timestamped observations with the corresponding moments in the clip.',
      'Optionally extract the audio in Audio and review a transcript separately from visual observations.',
      'Open the clip or practice images in GIF Maker, choose a short output, preview it and save a copy. Play the actual saved GIF to inspect timing and order.',
    ],
    checkpoint: 'Your summary names its sampled coverage and timestamps. The saved GIF plays in the intended order, and the source clip remains available.',
    exercise: 'Describe an event a sparse sample could miss. Explain how you would increase coverage or inspect that interval directly.',
    question: 'A model analyzed six moments in a long clip. What can you conclude?',
    choices: ['It inspected every frame', 'Its observations concern sampled moments; unsampled events may be missing', 'The video’s audio has definitely been transcribed'], answer: 1,
    explanation: 'Sampling is bounded coverage. Visual sampling also does not establish what was said on the audio track.',
  },
  {
    id: 'three-d-and-slicing', title: 'Inspect a 3D model and slicing settings', module: 'Audio, video and 3D', minutes: 12,
    workspaces: ['3d-viewer', 'slicer'], sample: cubeStl,
    concepts: [
      'A mesh describes a 3D surface using vertices and faces. 3D Viewer & Editor lets you inspect a model, its geometry and offered editing controls. Save a project to retain editable work; an exported mesh is a different artifact.',
      '3D Slicer uses installed CuraEngine to turn an STL into G-code using a selected printer profile and material settings. Layer height, nozzle, infill and supports affect the toolpath. A downloaded G-code file still needs review for the actual printer; the workspace does not send it to a printer.',
    ],
    steps: [
      'Save the 20 mm practice cube STL and open it in 3D Viewer & Editor. Orbit the view and identify its six sides.',
      'Inspect geometry and the available transform controls. Record the source units rather than assuming every imported format carries physical units.',
      'Open 3D Slicer and Refresh Cura readiness. Identify printer profile, nozzle diameter, layer height, infill and support settings.',
      'Write a slicing plan for the cube. Use a real matching printer profile only if you know it; the lesson can be completed by inspecting settings without generating or printing.',
    ],
    checkpoint: 'You can distinguish mesh geometry, an editable project and a printer-specific toolpath. Readiness of CuraEngine does not establish that a generic printer profile matches your device.',
    exercise: 'Explain why the same cube could need different G-code on two printers, and list the settings you would check before any physical print.',
    question: 'What does the Slicer workspace produce after a successful slice?',
    choices: ['A G-code file for the chosen configuration', 'A physical object automatically', 'A trained chat model'], answer: 0,
    explanation: 'Slicing creates a file. Printer configuration review and physical printing are separate steps.',
  },
  {
    id: 'file-audits-packaging', title: 'Review files and package a result', module: 'Files and workflows', minutes: 12,
    workspaces: ['hash-auditor', 'folder-review', 'packager', 'dashboard'],
    concepts: [
      'Hash Auditor reads regular files to record SHA-256 and filesystem metadata. Matching names or sizes are candidates; matching content hashes are evidence about bytes read at the recorded time. Hardlinked paths can refer to one physical file.',
      'Folder Review summarizes supported file contents with a local text model and reports coverage. Its image inspection is metadata rather than vision analysis. Packager builds a ZIP from selected files and folders. A ZIP of chosen outputs differs from Dashboard’s full app backup or numeric SAVE METADATA report.',
    ],
    needs: 'A small practice folder containing a few sample text files and one copied file. A content review needs an available local text model.',
    steps: [
      'Write the exact practice-folder scope before starting Hash Auditor. Inspect recorded hashes, skips and completion status.',
      'If a text model is ready, review the same practice folder in Folder Review. Compare its content findings and coverage with the hash inventory.',
      'Save a short report that separates verified byte matches, naming candidates and files the tools skipped.',
      'In Packager, add only the report and intended practice outputs, review package paths and save a ZIP copy. Inspect the archive’s contents.',
    ],
    checkpoint: 'Your report states scope, observation time and limitations. The ZIP contains the intended outputs, and the original practice files remain available.',
    exercise: 'Explain why identical filenames, matching hashes and a successful model summary are three different kinds of evidence.',
    question: 'Which finding supports that two read files contain identical bytes?',
    choices: ['Their thumbnails look similar', 'Their names match', 'Their recorded SHA-256 hashes match'], answer: 2,
    explanation: 'Hash matching compares recorded content. Names, sizes and thumbnails alone do not establish byte identity.',
  },
  {
    id: 'functions-and-linked-apps', title: 'Make a supervised workflow', module: 'Files and workflows', minutes: 12,
    workspaces: ['tools', 'integrations', 'shortcuts', 'chats'],
    concepts: [
      'Functions saves ordered THEN steps such as opening an app, waiting for a window, auditing a selected folder, preparing request text and saving outputs. Saving is separate from Run. Stop prevents later steps but does not undo completed actions.',
      'Linked applications has distinct Discord, Spotify and Phone / scrcpy controls. Preparing an attachment or message preview is separate from Send to Discord. Playback recording and phone tools have their own readiness and explicit controls. Credentials belong in the designated connection fields, never in a practice prompt.',
    ],
    steps: [
      'In Functions, inspect Create Function and an existing template. Name each step’s input, visible result and effect.',
      'Draft a simple practice sequence using a selected folder audit, request text and saved outputs. Review the destinations and stop point before an optional run.',
      'Inspect Add result to chat: it stages removable attachments for review before Send.',
      'Open Linked applications and inspect a message preview or recording requirements. Write down the recipient or recording source you would need to verify before using its action control.',
    ],
    checkpoint: 'You can identify the actions that prepare, save, run, stage and send. A function is a fixed supervised sequence, and copying a tool catalog does not add an automatic executor to ordinary chat.',
    exercise: 'Draw your proposed sequence and mark the last reversible preparation step before any external message would be sent.',
    question: 'What happens when you save a Function?',
    choices: ['It runs immediately', 'Its steps are stored; Run is a separate explicit action', 'It gives every chat model unrestricted desktop control'], answer: 1,
    explanation: 'Saving stores the ordered configuration. Execution begins only through its Run control.',
  },
];
