import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const server=spawn('python',['-m','tests.ui_fixture_server','--catalog'],{stdio:['pipe','pipe','inherit'],windowsHide:true});
let browser;
try {
  const fixture=await new Promise((resolve,reject)=>{createInterface({input:server.stdout}).once('line',line=>resolve(JSON.parse(line)));server.once('exit',code=>reject(new Error(`Fixture exited ${code}`)));});
  browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(fixture.url);
  await page.waitForFunction(()=>document.querySelector('media-organizer').data?.aggregate);
  assert.equal(await page.locator('.mo-media-card').count(),25);
  assert.match(await page.locator('#mo-scope-description').innerText(),/5 scanned folders · 6 saved scans/);
  await page.locator('[data-year="2019"]').click();
  assert.equal(await page.locator('.mo-media-card').count(),5);
  await page.waitForFunction(()=>[...document.querySelectorAll('.mo-media-card .mo-thumbnail img')].every(img=>img.complete && img.naturalWidth>0));
  const rows=await page.evaluate(()=>document.querySelector('media-organizer').data.records.filter(r=>String(r.ResolvedYear)==='2019'));
  assert.equal(new Set(rows.map(r=>r.ScanSource)).size,5);
  await mkdir('test-work/ui-qa',{recursive:true});await page.screenshot({path:'test-work/ui-qa/all-scans-2019.png'});
  const row=rows[0],before=await readFile(row.CurrentPath);
  await page.locator(`[data-detail="${row.RecordId}"]`).click();
  await page.waitForFunction(()=>document.querySelector('#mo-detail video')?.readyState>=1);
  assert.match(await page.locator('#mo-detail').innerText(),/Open this saved scan/);
  await page.locator('#mo-open-origin-scan').click();
  await page.waitForFunction(()=>document.querySelector('media-organizer').data?.aggregate!==true);
  assert.equal(await page.locator('.mo-media-card').count(),5);
  await page.locator('[data-year="2019"]').click();assert.equal(await page.locator('.mo-media-card').count(),1);
  await page.locator('#mo-all-videos').click();await page.waitForFunction(()=>document.querySelector('media-organizer').data?.aggregate);
  assert.equal(await page.locator('.mo-media-card').count(),5);
  await page.reload();await page.waitForFunction(()=>document.querySelector('media-organizer').data?.aggregate);
  assert.equal(await page.locator('.mo-media-card').count(),5);assert.equal(await page.locator('[data-year="2019"]').getAttribute('aria-pressed'),'true');
  await page.locator(`[data-rotate-right="${row.RecordId}"]`).click();
  await page.waitForFunction(id=>document.querySelector('media-organizer').data.records.find(r=>r.RecordId===id).ViewRotation===90,row.RecordId);
  assert.equal(await page.evaluate(()=>document.querySelector('media-organizer').data.records.filter(r=>r.ViewRotation===90).length),1);
  await page.locator(`[data-detail="${row.RecordId}"]`).click();await page.locator('#mo-detail .mo-item-more summary').click();await page.locator('#mo-detail [data-tool="rename"]').click();
  await page.locator('#mo-rename').fill('Renamed in all scans');await page.getByRole('button',{name:'Rename file',exact:true}).click();
  await page.waitForFunction(id=>document.querySelector('media-organizer').data.records.find(r=>r.RecordId===id)?.OriginalFilename==='Renamed in all scans.mp4',row.RecordId);
  assert.equal(await page.locator('.mo-media-card').count(),5);assert.equal(await page.locator('[data-year="2019"]').getAttribute('aria-pressed'),'true');
  await page.locator('#mo-select-matching').click();await page.locator('#mo-new-with-selected').click();
  await page.locator('#mo-custom-name').fill('All 2019');await page.locator('#mo-custom-save').click();
  await page.locator('#mo-custom-preview').click();await page.getByRole('heading',{name:'Review 5 selected moves',exact:true}).waitFor();assert.equal(await page.locator('.mo-custom-preview-item').count(),5);
  await page.locator('#mo-custom-confirm').fill('MOVE');await page.locator('#mo-custom-execute').click();
  await page.waitForFunction(()=>document.querySelector('media-organizer').data?.records.filter(r=>r.CustomFolderId).length===5);
  const current=await page.evaluate(id=>document.querySelector('media-organizer').data.records.find(r=>r.RecordId===id),row.RecordId);
  assert.deepEqual(await readFile(current.CurrentPath),before);assert.equal(await page.locator('.mo-media-card').count(),5);
  await page.locator('[data-custom-filter=""]').click();await page.locator('[data-tab="duplicates"]').click();
  await page.locator('#mo-duplicate-year').selectOption('2019');assert.equal(await page.locator('[data-enlarge]').count(),5);
  await page.locator('[data-tab="library"]').click();await page.getByRole('button',{name:'Scan another folder',exact:true}).click();
  assert.equal(await page.locator('.mo-flow').isVisible(),true);assert.equal(await page.locator('#mo-source').inputValue(),'');
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.deepEqual(errors,[]);
  console.log('All-scans UI passed: five folders and a rescan, 2019 across all folders, real thumbnails/playback, original scan access, year/scope reload persistence, independent rotation, rename, cross-scan move, duplicates, and new-scan navigation.');
}finally{await browser?.close();const closed=new Promise(resolve=>server.once('exit',resolve));server.stdin.end('stop\n');await closed;}
