// Real filesystem outputs from disposable media; never opens Explorer or touches user media.
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';
import { access, readFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const server=spawn('python',['-m','tests.ui_fixture_server','--duplicates'],{stdio:['pipe','pipe','inherit'],windowsHide:true});
let browser;
try {
  const fixture=await new Promise((resolve,reject)=>{createInterface({input:server.stdout}).once('line',line=>resolve(JSON.parse(line)));server.once('exit',code=>reject(new Error(`Fixture exited ${code}`)));});
  browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[],revealed=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/api/open-folder',route=>{revealed.push(route.request().postDataJSON());return route.fulfill({json:{opened:true}});});
  await page.goto(fixture.url);
  await page.getByRole('button',{name:'Add custom folder',exact:true}).click();
  await page.getByLabel('Folder name',{exact:true}).fill('Favorites');
  assert.ok(await page.locator('#mo-custom-location').isHidden());
  await page.getByRole('button',{name:'Create folder',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#mo-custom-dialog').open);
  const managed=path.join(path.dirname(fixture.source),'runs','managed-media','Custom Folders','Favorites');
  await access(managed);
  await page.getByRole('button',{name:'Open Favorites folder',exact:true}).click();
  assert.equal(revealed.at(-1).path,managed);
  await page.getByRole('button',{name:'Add custom folder',exact:true}).click();
  await page.getByLabel('Folder location',{exact:true}).selectOption('external');
  await page.getByLabel('Folder name',{exact:true}).fill('Travel');
  await page.locator('#mo-custom-path').fill(path.dirname(fixture.source));
  await page.getByRole('button',{name:'Browse PC folders'}).click();
  const picker=page.getByRole('dialog',{name:'Choose a folder',exact:true});
  await picker.getByRole('button',{name:'Use this folder',exact:true}).waitFor();
  await page.waitForFunction(()=>!document.querySelector('.mo-folder-picker [data-select]').disabled);
  await picker.getByLabel('New subfolder name',{exact:true}).fill('Chosen parent');
  await picker.getByRole('button',{name:'Create subfolder',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.mo-folder-picker [aria-label="Folder address"]').value.endsWith('Chosen parent')&&!document.querySelector('.mo-folder-picker [data-select]').disabled);
  await picker.getByRole('button',{name:'Use this folder',exact:true}).click();
  await page.getByRole('button',{name:'Create folder',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#mo-custom-dialog').open);
  const external=path.join(path.dirname(fixture.source),'Chosen parent','Travel');await access(external);
  await page.getByRole('button',{name:'Open Travel folder',exact:true}).click();assert.equal(revealed.at(-1).path,external);
  await page.locator('#mo-source').fill(fixture.source);await page.locator('#mo-destination').fill(fixture.destination);await page.locator('#mo-scan').click();
  await page.waitForFunction(()=>document.querySelectorAll('.mo-media-card').length===5);
  await page.getByLabel('Group media by').selectOption('year');assert.equal(await page.locator('.mo-date-group h3').count(),2);
  assert.match(await page.locator('.mo-date-group h3').first().innerText(),/2024/);
  await page.getByRole('button',{name:'Large gallery view',exact:true}).click();assert.equal(await page.locator('.mo-media-gallery').count(),2);
  await page.getByLabel('Group media by').selectOption('none');assert.equal(await page.locator('.mo-date-group h3').count(),1);
  await page.getByLabel('Group media by').selectOption('month');
  await page.locator('[data-detail]').first().click();const dialog=page.locator('#mo-detail');
  await page.waitForFunction(()=>document.querySelector('#mo-detail video')?.readyState>=2);
  const sourceFile=await dialog.locator('video').evaluate(v=>document.querySelector('media-organizer').data.records.find(r=>v.src.includes(encodeURIComponent(r.RecordId))).CurrentPath);
  const sourceBytes=await readFile(sourceFile);
  await dialog.locator('[data-rotate-right]').click();
  await page.waitForFunction(()=>document.querySelector('#mo-detail video')?.dataset.rotation==='90');
  const timeline=dialog.getByLabel('Video timeline',{exact:true});assert.ok(await timeline.isVisible());
  assert.equal(await timeline.evaluate(e=>getComputedStyle(e.closest('.mo-playback-tools')).transform),'none');
  await timeline.fill('0.4');
  await page.waitForFunction(()=>{const v=document.querySelector('#mo-detail video');return !v.seeking&&Math.abs(v.currentTime-.4)<.002;});
  assert.match(await dialog.getByLabel('Video time',{exact:true}).innerText(),/0:00\.4 \/ 0:01/);
  await dialog.getByRole('button',{name:'Snapshot',exact:true}).click();
  await dialog.getByRole('button',{name:'View snapshots',exact:true}).waitFor();
  await dialog.getByRole('button',{name:'CLIP · mark a range',exact:true}).click();
  await dialog.getByLabel('Clip start',{exact:true}).fill('0.2');await dialog.getByLabel('Clip end',{exact:true}).fill('0.8');
  await dialog.getByRole('button',{name:'Save clip',exact:true}).click();
  await dialog.getByRole('button',{name:'View saved clips',exact:true}).waitFor({timeout:60000});
  await mkdir('test-work/ui-qa',{recursive:true});await page.screenshot({path:'test-work/ui-qa/rotated-video-captures.png'});
  const captureFile=path.join(path.dirname(fixture.source),'runs','captures.json');const saved=JSON.parse(await readFile(captureFile,'utf8'));
  assert.equal(saved.length,2);const snapshot=saved.find(r=>r.kind==='snapshot'),clip=saved.find(r=>r.kind==='clip');
  assert.equal(snapshot.width,720);assert.equal(snapshot.height,1280);assert.equal(snapshot.time,.4);assert.equal(clip.start,.2);assert.equal(clip.end,.8);assert.equal(clip.rotation,90);
  await access(snapshot.path);await access(clip.path);assert.deepEqual(await readFile(sourceFile),sourceBytes);
  await dialog.getByRole('button',{name:'Close file details',exact:true}).click();
  await page.locator('#mo-snapshots').click();
  await page.locator('.mo-capture-preview img').evaluate(img=>img.decode());
  await page.locator('.mo-capture-preview').click();
  const enlarged=page.locator('.mo-capture-lightbox');await enlarged.locator('img').evaluate(img=>img.decode());
  assert.equal(await enlarged.locator('img').evaluate(img=>img.naturalWidth),720);
  await enlarged.getByRole('button',{name:'Open PC file location',exact:true}).click();assert.equal(revealed.at(-1).captureId,snapshot.id);
  await enlarged.getByRole('button',{name:'Close preview',exact:true}).click();
  await page.getByRole('button',{name:'View saved clips',exact:true}).click();await page.locator('.mo-capture-preview').click();
  await page.waitForFunction(()=>document.querySelector('.mo-capture-lightbox video')?.readyState>=2);
  const info=await page.locator('.mo-capture-lightbox video').evaluate(v=>({width:v.videoWidth,height:v.videoHeight,duration:v.duration}));
  assert.equal(info.width,720);assert.equal(info.height,1280);assert.ok(Math.abs(info.duration-.6)<.05);
  await page.reload();await page.locator('#mo-snapshots').click();await page.locator('.mo-capture-preview img').evaluate(img=>img.decode());
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'test-work/ui-qa/snapshots-mobile.png'});
  assert.deepEqual(errors,[]);
  console.log('Folders/captures UI passed: managed and external creation, in-app browsing/subfolders, Explorer target wiring, date headers/layouts, rotated timeline seeking, real PNG and trimmed MP4 outputs, capture gallery enlargement/persistence, intact source, mobile layout.');
}finally{await browser?.close();const closed=new Promise(resolve=>server.once('exit',resolve));server.stdin.end('stop\n');await closed;}
