// Isolated end-to-end duplicate browsing with real, byte-identical generated clips.
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const server = spawn('python', ['-m', 'tests.ui_fixture_server', '--duplicates'], { stdio: ['pipe', 'pipe', 'inherit'], windowsHide: true });
let browser;
try {
  const fixture = await new Promise((resolve, reject) => {
    createInterface({ input: server.stdout }).once('line', line => resolve(JSON.parse(line)));
    server.once('exit', code => reject(new Error(`Fixture exited: ${code}`)));
  });
  browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(fixture.url);
  await page.getByRole('tab', { name: /Duplicates/ }).click();
  await page.getByText('Scan a folder to find duplicates').waitFor();
  await page.getByRole('button', { name: 'Back to media library' }).click();
  await page.getByLabel('Source folder', { exact: true }).fill(fixture.source);
  await page.getByLabel('Destination folder', { exact: true }).fill(fixture.destination);
  await page.getByRole('button', { name: 'Scan & preview' }).click();
  await page.waitForFunction(() => document.querySelectorAll('.mo-media-card').length === 5);
  await page.getByRole('searchbox', { name: 'Search media', exact: true }).fill('20240820_160000');
  assert.equal(await page.locator('.mo-media-card').count(), 1);
  await page.getByRole('tab', { name: /Duplicates/ }).click();
  assert.equal(await page.locator('.mo-flow').isVisible(), false);
  assert.equal(await page.locator('.mo-sidebar').isVisible(), false);
  assert.equal(await page.locator('.mo-duplicate-group').count(), 2);
  assert.equal(await page.locator('.mo-duplicate-card').count(), 4);
  for (const image of await page.locator('.mo-duplicate-card img').all()) {
    await image.scrollIntoViewIfNeeded(); await image.evaluate(img => img.decode());
    assert.equal(await image.evaluate(img => img.naturalWidth), 960);
  }
  await mkdir('test-work/ui-qa', { recursive: true });
  await page.screenshot({ path: 'test-work/ui-qa/duplicates-desktop.png', fullPage: true });
  const regular = await page.locator('.mo-duplicate-card').first().boundingBox();
  await page.getByRole('button', { name: 'Larger previews', exact: true }).click();
  assert.ok((await page.locator('.mo-duplicate-card').first().boundingBox()).width > regular.width * 1.8);
  await page.getByRole('button', { name: 'Standard previews', exact: true }).click();
  await page.getByLabel('Filter duplicates by year').selectOption('2020');
  assert.equal(await page.locator('.mo-duplicate-group').count(), 1);
  await page.getByLabel('Filter duplicates by year').selectOption('');
  await page.getByLabel('Sort duplicate groups by date').selectOption('oldest');
  assert.match(await page.locator('.mo-duplicate-date').first().innerText(), /2020/);
  await page.getByRole('searchbox', { name: 'Search duplicates' }).fill('Backup copy');
  assert.equal(await page.locator('.mo-duplicate-card').count(), 4, 'Search must keep the entire matched group');
  await page.getByRole('searchbox', { name: 'Search duplicates' }).fill('no-such-file');
  await page.getByText('No matching duplicate groups').waitFor();
  await page.getByRole('button', { name: 'Clear duplicate filters' }).click();
  await page.locator('[data-enlarge]').first().click();
  const viewer = page.locator('#mo-duplicate-viewer');
  await viewer.locator('img').evaluate(img => img.decode());
  assert.equal(await viewer.locator('img').evaluate(img => img.naturalWidth), 1280);
  assert.ok((await viewer.boundingBox()).width >= 1400);
  assert.ok((await viewer.locator('.mo-viewer-stage').boundingBox()).height > 700);
  await page.screenshot({ path: 'test-work/ui-qa/duplicates-enlarged.png' });
  const original = await viewer.locator('.mo-viewer-location').innerText();
  await page.getByRole('button', { name: 'Next copy' }).click();
  assert.notEqual(await viewer.locator('.mo-viewer-location').innerText(), original);
  await page.keyboard.press('ArrowLeft');
  assert.equal(await viewer.locator('.mo-viewer-location').innerText(), original);
  await page.getByRole('button', { name: 'Play video', exact: true }).click();
  await viewer.locator('video').waitFor();
  await page.getByRole('button', { name: 'Show thumbnail', exact: true }).click();
  await viewer.locator('img').evaluate(img => img.decode());
  await page.keyboard.press('Escape');
  assert.equal(await viewer.isVisible(), false);
  await page.getByRole('tab', { name: 'Media library', exact: true }).click();
  assert.equal(await page.getByRole('searchbox', { name: 'Search media', exact: true }).inputValue(), '20240820_160000');
  assert.equal(await page.locator('.mo-flow').isVisible(), true);
  await page.getByRole('tab', { name: 'Media library', exact: true }).focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('tab', { name: /Duplicates/ }).getAttribute('aria-selected'), 'true');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.locator('[data-enlarge]').first().click();
  await viewer.locator('img').evaluate(img => img.decode());
  assert.equal(await page.evaluate(() => document.querySelector('#mo-duplicate-viewer').scrollWidth <= innerWidth), true);
  await page.screenshot({ path: 'test-work/ui-qa/duplicates-mobile-enlarged.png' });
  await page.keyboard.press('Escape');
  assert.deepEqual(errors, []);
  console.log('Duplicate browser checks passed: exact groups, full-group search, dates, large/full-resolution previews, copy navigation, playback, keyboard tabs/Escape, independent library filters, and mobile layout.');
} finally {
  await browser?.close();
  const closed = new Promise(resolve => server.once('exit', resolve));
  server.stdin.end('stop\n'); await closed;
}
