// Full selection -> review -> custom-folder move workflow, using generated temporary clips.
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';
import { access, mkdir, readFile, readdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const server = spawn('python', ['-m', 'tests.ui_fixture_server', '--duplicates'], { stdio: ['pipe', 'pipe', 'inherit'], windowsHide: true });
let browser;
try {
  const fixture = await new Promise((resolve, reject) => {
    createInterface({ input: server.stdout }).once('line', line => resolve(JSON.parse(line)));
    server.once('exit', code => reject(new Error(`Fixture exited: ${code}`)));
  });
  browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(fixture.url);

  await page.getByLabel('Source folder', { exact: true }).fill(fixture.source);
  await page.getByLabel('Destination folder', { exact: true }).fill(fixture.destination);
  await page.getByRole('button', { name: 'Scan & preview' }).click();
  await page.waitForFunction(() => document.querySelectorAll('.mo-media-card').length === 5);

  const row = await page.evaluate(()=>document.querySelector('media-organizer').data.records.find(r=>r.DuplicatePrimary==='yes'));
  const id=row.RecordId;
  const original=await readFile(row.CurrentPath);
  await page.locator('[data-tab="duplicates"]').click();
  assert.equal(await page.locator('.mo-primary-card').count(),2);
  assert.equal(await page.locator('.mo-primary-card .mo-primary-copy').count(),2);
  await page.locator('[data-tab="library"]').click();
  await page.locator(`[data-select-media="${id}"]`).check();
  await page.locator('#mo-new-tag').click();
  await page.locator('#mo-tag-name').fill('Travel QA');
  await page.getByRole('button',{name:'Create tag and apply',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#mo-tag-list').textContent.includes('Travel QA'));
  await page.locator('[data-tool-close]').click();
  await page.locator('[data-tag-filter]').click();
  assert.equal(await page.locator('.mo-media-card').count(),2);
  await page.locator('[data-tag-filter]').click();
  await page.getByLabel('Group media by').selectOption('none');
  await page.locator('#mo-order').selectOption('size-desc');
  assert.equal(await page.locator('.mo-date-group').count(),1);
  await page.locator('#mo-order').selectOption('oldest');
  await page.locator(`[data-detail="${id}"]`).click();
  await page.locator('#mo-detail .mo-item-more summary').click();
  await page.locator('#mo-detail [data-tool="rename"]').click();
  await page.locator('#mo-rename').fill('Renamed QA video');
  await page.getByRole('button',{name:'Rename file',exact:true}).click();
  await page.waitForFunction(id=>document.querySelector('media-organizer').data.records.find(r=>r.RecordId===id).OriginalFilename==='Renamed QA video.mp4',id);
  const renamed=await page.evaluate(id=>document.querySelector('media-organizer').data.records.find(r=>r.RecordId===id),id);
  assert.deepEqual(await readFile(renamed.CurrentPath),original);
  await page.locator(`[data-detail="${id}"]`).click();
  await page.locator('#mo-detail .mo-item-more summary').click();
  await page.locator('#mo-detail [data-tool="delete"]').click();
  await page.locator('#mo-delete-word').fill('DELETE');
  await page.getByRole('button',{name:'Delete this copy',exact:true}).click();
  await page.waitForFunction(id=>document.querySelector('media-organizer').data.records.find(r=>r.RecordId===id).Trashed,id);
  await page.locator('.mo-advanced-filters summary').click();
  await page.locator('#mo-library-status').selectOption('trash');
  assert.equal(await page.locator('.mo-media-card').count(),1);
  await page.locator('.mo-media-card .mo-item-more summary').click();
  await page.locator('[data-tool="restore"]').click();
  await page.getByRole('button',{name:'Restore file',exact:true}).click();
  await page.waitForFunction(id=>!document.querySelector('media-organizer').data.records.find(r=>r.RecordId===id).Trashed,id);
  // A finished background count must not replace a different dialog opened meanwhile.
  await page.evaluate(id=>{
    const panel=document.querySelector('media-organizer'), operation=panel.adapter.operation.bind(panel.adapter);
    panel.adapter.operation=async(...args)=>{
      const job=await operation(...args);
      await new Promise(resolve=>{window.releaseFrameCount=resolve;});
      panel.adapter.operation=operation;
      return job;
    };
    window.pendingFrameCount=panel.openFrameParser(panel.data.records.find(r=>r.RecordId===id));
  },id);
  await page.waitForFunction(()=>!!window.releaseFrameCount);
  await page.locator('[data-tool-close]').click();
  await page.locator('#mo-new-tag').click();
  await page.evaluate(async()=>{window.releaseFrameCount();await window.pendingFrameCount;});
  assert.equal(await page.locator('#mo-tools-title').innerText(),'Custom media tags');
  await page.locator('[data-tool-close]').click();
  await page.locator(`[data-detail="${id}"]`).click();
  await page.locator('#mo-detail .mo-item-more summary').click();
  await page.locator('#mo-detail [data-tool="frames"]').click();
  await page.locator('#mo-frame-interval').waitFor();
  assert.equal(await page.locator('#mo-frame-interval option').count(),18);
  await page.locator('#mo-frame-interval').selectOption('3');
  await page.locator('#mo-frame-start').fill('2');
  await page.locator('#mo-frame-end').fill('8');
  await page.locator('#mo-frame-destination').fill(fixture.destination+'-parsed');
  assert.match(await page.locator('#mo-frame-estimate').innerText(),/3 output images/);
  await mkdir('test-work/ui-qa',{recursive:true});
  await page.screenshot({path:'test-work/ui-qa/frame-parser.png'});
  await page.locator('#mo-frame-run').click();
  await page.getByRole('heading',{name:'Frames ready',exact:true}).waitFor();
  const output=await page.locator('#mo-tools-dialog .mo-path').innerText();
  assert.equal((await readdir(output)).filter(n=>n.endsWith('.png')).length,3);
  assert.equal((await readdir(output)).some(name=>name.endsWith('.json')),false,'Exports contain only images');
  const exportRun = await page.evaluate(()=>document.querySelector('media-organizer').data.uiRunId);
  const manifest=JSON.parse(await readFile(path.join(fixture.reports,exportRun,'frame-exports',path.basename(output)+'.json'),'utf8'));
  assert.equal(manifest.settings.interval,3);assert.equal(manifest.settings.start,2);assert.equal(manifest.count,3);
  assert.deepEqual(await readFile(renamed.CurrentPath),original);
  await page.locator('[data-tool-close]').click();
  await page.locator(`[data-new-item="${id}"]`).click();
  await page.locator('#mo-custom-name').fill('Moved through Media Manager');
  await page.locator('#mo-custom-save').click();
  await page.locator('#mo-custom-preview').click();
  await page.locator('#mo-custom-confirm').fill('MOVE');
  await page.locator('#mo-custom-execute').click();
  await page.waitForFunction(id=>document.querySelector('media-organizer').data.records.find(r=>r.RecordId===id).CurrentPath.includes('Moved through Media Manager'),id);
  await page.reload(); await page.waitForFunction(()=>!!document.querySelector('media-organizer').data);
  const final=await page.evaluate(id=>document.querySelector('media-organizer').data.records.find(r=>r.RecordId===id),id);
  assert.ok(final.Tags.includes('Travel QA')); assert.deepEqual(await readFile(final.CurrentPath),original);
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,JSON.stringify(await page.evaluate(()=>[...document.querySelectorAll('media-organizer *')].filter(el=>el.getBoundingClientRect().right>innerWidth+1).slice(0,15).map(el=>({id:el.id,class:el.className,right:el.getBoundingClientRect().right,width:el.getBoundingClientRect().width})))));
  assert.deepEqual(errors,[]);
  console.log('Extended media UI passed: hash-primary badges, tag creation/application/filtering, numeric global sort, enlarged rename, recoverable delete/restore, decoded frame count and all 18 intervals, real PNG extraction to chosen folder, actual in-app video move, source bytes and reload persistence, mobile layout.');
} finally {
 await browser?.close(); const closed=new Promise(resolve=>server.once('exit',resolve));server.stdin.end('stop\n');await closed;
}
