import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const server=spawn('python',['-m','tests.ui_fixture_server','--images'],{stdio:['pipe','pipe','inherit'],windowsHide:true});
let browser;
try {
  const fixture=await new Promise((resolve,reject)=>{createInterface({input:server.stdout}).once('line',line=>resolve(JSON.parse(line)));server.once('exit',code=>reject(new Error(`Fixture exited ${code}`)));});
  browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(fixture.url);
  await page.getByRole('button',{name:'Image tools',exact:true}).click();
  await page.getByLabel('Image source folder',{exact:true}).fill(fixture.imageSource);
  await page.getByRole('button',{name:'Read image folder',exact:true}).click();
  await page.getByRole('heading',{name:'Convert, size & stitch',exact:true}).waitFor();
  assert.equal(await page.locator('.mo-image-file-list li').count(),4);
  await page.getByLabel('Standardize aspect ratio and size',{exact:true}).check();
  await page.locator('#mo-images-width').fill('64');
  assert.equal(await page.locator('#mo-images-height').inputValue(),'64');
  await page.locator('#mo-images-stitch summary').click();
  await page.locator('#mo-images-layout').selectOption('grid');
  assert.deepEqual(await page.locator('#mo-images-columns option').evaluateAll(nodes=>nodes.map(n=>n.value)),['1','2','4']);
  await page.locator('#mo-images-columns').selectOption('2');
  await page.locator('#mo-images-gap').fill('4');await page.locator('#mo-images-gap').dispatchEvent('change');
  await page.locator('#mo-images-destination').fill(fixture.destination);
  assert.match(await page.locator('#mo-images-estimate').innerText(),/132 × 132/);
  await mkdir('test-work/ui-qa',{recursive:true});await page.screenshot({path:'test-work/ui-qa/image-tools.png'});
  await page.getByRole('button',{name:'Create image copies',exact:true}).click();
  await page.getByRole('heading',{name:'Image copies ready',exact:true}).waitFor();
  const output=await page.locator('#mo-tools-dialog .mo-path').innerText();
  const report=JSON.parse(await readFile(output+'\\images.json','utf8'));
  assert.equal(report.status,'complete');assert.equal(report.images.length,4);
  const png=await readFile(report.stitched);assert.equal(png.readUInt32BE(16),132);assert.equal(png.readUInt32BE(20),132);
  for(const item of report.images){const image=await readFile(item.output);assert.equal(image.readUInt32BE(16),64);assert.equal(image.readUInt32BE(20),64);await readFile(item.source.path);}
  await page.getByRole('button',{name:'Use different options',exact:true}).click();
  await page.locator('#mo-images-stitch summary').click();
  await page.locator('#mo-images-layout').selectOption('gif');
  await page.locator('#mo-images-width').fill('64');
  await page.locator('#mo-images-delay').fill('200');await page.locator('#mo-images-delay').dispatchEvent('change');
  await page.locator('#mo-images-destination').fill(fixture.destination);
  assert.match(await page.locator('#mo-images-estimate').innerText(),/0.80 seconds per cycle/);
  await page.getByRole('button',{name:'Create image copies',exact:true}).click();
  await page.getByRole('heading',{name:'Image copies ready',exact:true}).waitFor();
  const gifOutput=await page.locator('#mo-tools-dialog .mo-path').innerText();
  const gifReport=JSON.parse(await readFile(gifOutput+'\\images.json','utf8'));
  assert.equal((await readFile(gifReport.animated)).subarray(0,6).toString(),'GIF89a');
  assert.equal(gifReport.settings.frameDelay,200);assert.equal(gifReport.status,'complete');
  await page.getByRole('button',{name:'Use different options',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.querySelector('#mo-tools-dialog').scrollWidth<=document.querySelector('#mo-tools-dialog').clientWidth),true);
  assert.deepEqual(errors,[]);
  console.log('Image tools UI passed: folder inspection without a video scan, exact sizing, divisible grids, real PNG outputs and stitch dimensions, destination selection, mobile layout.');
}finally{await browser?.close();const closed=new Promise(resolve=>server.once('exit',resolve));server.stdin.end('stop\n');await closed;}
