import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const server=spawn('python',['-m','tests.ui_fixture_server','--duplicates'],{stdio:['pipe','pipe','inherit'],windowsHide:true});
let browser;
try {
  const fixture=await new Promise((resolve,reject)=>{createInterface({input:server.stdout}).once('line',line=>resolve(JSON.parse(line)));server.once('exit',code=>reject(new Error(`Fixture exited ${code}`)));});
  browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(fixture.url);
  await page.locator('#mo-source').fill(fixture.source);await page.locator('#mo-destination').fill(fixture.destination);
  await page.locator('#mo-scan').click();
  await page.locator('.mo-media-card').first().waitFor({timeout:60000});
  await page.locator('[data-detail]').first().click();
  const dialog=page.locator('#mo-detail');
  await page.waitForFunction(()=>document.querySelector('#mo-detail video')?.readyState>=2);
  assert.equal(await dialog.getByLabel('Frame progression',{exact:true}).locator('option').count(),10);
  assert.equal(await dialog.getByLabel('Time progression',{exact:true}).locator('option').count(),20);
  await dialog.getByLabel('Frame progression',{exact:true}).selectOption('5');
  await dialog.getByRole('button',{name:'Next frames',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#mo-detail .mo-playback-tools > [role=status]')?.textContent.startsWith('Frame 6 of 25'));
  assert.ok(Math.abs(await dialog.locator('video').evaluate(v=>v.currentTime)-.2)<.001);
  await dialog.getByLabel('Frame progression',{exact:true}).selectOption('2');
  await dialog.getByRole('button',{name:'Previous frames',exact:true}).click();
  assert.ok(Math.abs(await dialog.locator('video').evaluate(v=>v.currentTime)-.12)<.001);
  await dialog.getByLabel('Time progression',{exact:true}).selectOption('60');
  await dialog.getByRole('button',{name:'Back in time',exact:true}).click();
  assert.equal(await dialog.locator('video').evaluate(v=>v.currentTime),0);
  await dialog.getByRole('button',{name:'Forward in time',exact:true}).click();
  assert.ok(await dialog.locator('video').evaluate(v=>v.currentTime<=v.duration&&v.paused));
  await dialog.getByRole('button',{name:'Close file details',exact:true}).click();
  await page.locator('[data-tab="duplicates"]').click();
  await page.locator('[data-enlarge]').first().click();
  await page.locator('[data-viewer-play]').click();
  const duplicate=page.locator('#mo-duplicate-viewer');
  await page.waitForFunction(()=>document.querySelector('#mo-duplicate-viewer video')?.readyState>=2);
  await duplicate.getByRole('button',{name:'Back in time',exact:true}).click();
  await duplicate.getByLabel('Frame progression',{exact:true}).selectOption('10');
  await duplicate.getByRole('button',{name:'Next frames',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#mo-duplicate-viewer .mo-playback-tools > [role=status]')?.textContent.startsWith('Frame 11 of 25'));
  assert.ok(Math.abs(await duplicate.locator('video').evaluate(v=>v.currentTime)-.4)<.001);
  await page.setViewportSize({width:390,height:844});
  assert.ok(await duplicate.evaluate(d=>d.scrollWidth<=d.clientWidth+1));
  assert.deepEqual(errors,[]);
  await mkdir('test-work/ui-qa',{recursive:true});await page.screenshot({path:'test-work/ui-qa/frame-stepping.png'});
  console.log('Playback UI passed: exact 5/2/10 frame seeks, 60-second clamping, pause, normal and duplicate viewers, mobile layout.');
}finally{await browser?.close();const closed=new Promise(resolve=>server.once('exit',resolve));server.stdin.end('stop\n');await closed;}
