import {useEffect,useRef,useState} from 'react';
import {reviewRequest,reviewImageUrl} from '../visualReview';
import ReviewFieldsEditor,{reviewStatuses} from './ReviewFieldsEditor';
import ReviewTags from './ReviewTags';
import ReviewRecordDetails from './ReviewRecordDetails';
import {apiUrl} from '../api';
import './ReviewWorkflow.css';
import {reviewStatusLabels,completeReview} from '../imageReview';

const request=(route,body)=>reviewRequest('/workflow'+route,body);
const manual=value=>Object.fromEntries(['rating','review_status','caption','category','project','favorite','tags'].map(key=>[key,value[key]]));
const edits=(before,after)=>Object.fromEntries(Object.entries(after).filter(([key,value])=>JSON.stringify(value)!==JSON.stringify(before[key])));

export default function ReviewWorkflow({source='library',ids=[],active=true,onChanged,embedded=false}) {
  const [open,setOpen]=useState(embedded),[scope,setScope]=useState(source),[filter,setFilter]=useState(''),[favorite,setFavorite]=useState(false),[query,setQuery]=useState(''),[offset,setOffset]=useState(0);
  const [catalog,setCatalog]=useState({items:[],total:0}),[selected,setSelected]=useState([]),[presets,setPresets]=useState([]),[preset,setPreset]=useState('0'),[path,setPath]=useState(''),[mode,setMode]=useState('copy'),[collision,setCollision]=useState('rename'),[plan,setPlan]=useState(null),[history,setHistory]=useState([]);
  const [current,setCurrent]=useState(null),[value,setValue]=useState(null),[suggestion,setSuggestion]=useState(null),[suggested,setSuggested]=useState(null),[model,setModel]=useState(''),[models,setModels]=useState([]),[job,setJob]=useState(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[batchCategory,setBatchCategory]=useState(''),[batchProject,setBatchProject]=useState(''),[batchTag,setBatchTag]=useState(''),[batchAction,setBatchAction]=useState('accepted');
  const dialog=useRef(null),organizer=useRef(null),acting=useRef(false),loadVersion=useRef(0),currentId=useRef(null),initialFilters=useRef(true),videoPlayer=useRef(null);
  currentId.current=current?.media_id;
  const [workspaceSelection,setWorkspaceSelection]=useState(true);
  const targets=workspaceSelection&&scope===source?ids.map(id=>source+':'+id):selected;
  useEffect(()=>{setSelected([]);if(initialFilters.current)initialFilters.current=false;else{setWorkspaceSelection(false);setPlan(null);}},[filter,favorite,query]);
  const changed=()=>{setRevision(n=>n+1);onChanged?.();};
  async function act(work){if(acting.current)return;acting.current=true;setBusy(true);setError('');try{await work();}catch(failure){setError(failure.message);}finally{acting.current=false;setBusy(false);}}
  useEffect(()=>{if(!open||!active)return;let live=true;request(`/list?${new URLSearchParams({source:scope,status:filter,query,offset,...(favorite?{favorite:true}:{})})}`).then(result=>{if(live)setCatalog(result);}).catch(failure=>{if(live)setError(failure.message);});return()=>{live=false;};},[open,active,scope,filter,favorite,query,offset,revision]);
  useEffect(()=>{if(!open||!active)return;let live=true;Promise.all([request('/presets'),request('/plans')]).then(([choices,plans])=>{if(live){setPresets(choices);setHistory(plans.reverse().slice(0,20));}}).catch(failure=>{if(live)setError(failure.message);});return()=>{live=false;};},[open,active,revision]);
  useEffect(()=>{if(current&&active)dialog.current?.showModal();else dialog.current?.close();},[!!current,active]);
  useEffect(()=>{if(!active)videoPlayer.current?.pause();},[active]);
  useEffect(()=>{if(!job||!['queued','running'].includes(job.status)||!active)return;let live=true,timer;const poll=async()=>{try{const result=await reviewRequest('/job?'+new URLSearchParams({id:job.id}));if(!live)return;setJob(result);if(result&&['queued','running'].includes(result.status))timer=setTimeout(poll,1200);else{changed();if(current)await loadSuggestion(current.media_id);}}catch(failure){if(live)setError(failure.message);}};timer=setTimeout(poll,800);return()=>{live=false;clearTimeout(timer);};},[job?.id,job?.status,active,current?.media_id]);
  async function loadSuggestion(id){const result=await request('/suggestions?'+new URLSearchParams({media_id:id}));if(id!==currentId.current)return;setSuggestion(result);setSuggested(result?.fields||null);}
  async function inspect(item){const version=++loadVersion.current;setSuggestion(null);setSuggested(null);const result=await request('/metadata?'+new URLSearchParams({media_id:item.media_id}));if(version!==loadVersion.current)return;setCurrent({...result,name:item.name});setValue(manual(result));const resultSuggestion=await request('/suggestions?'+new URLSearchParams({media_id:item.media_id}));if(version===loadVersion.current){setSuggestion(resultSuggestion);setSuggested(resultSuggestion?.fields||null);}}
  async function save(){if(!current||!value)return;const result=await request('/edit',{media_ids:[current.media_id],changes:edits(current,value)});if(result.items[0].error)throw Error(result.items[0].error);setCurrent(before=>({...before,...result.items[0].review}));changed();setNotice('Review saved.');}
  async function next(delta,mark=false){if(mark){const fields={...value,...completeReview(value)};const result=await request('/edit',{media_ids:[current.media_id],changes:edits(current,fields)});if(result.items[0].error)throw Error(result.items[0].error);changed();}else await save();const index=catalog.items.findIndex(item=>item.media_id===current.media_id),item=catalog.items[index+delta];if(item)await inspect(item);else{setCurrent(null);setValue(null);setNotice('Review page complete.');}}
  async function batchEdit(changes){const result=await request('/edit',{media_ids:targets,changes});const failed=result.items.filter(row=>row.error);changed();if(failed.length)throw Error(`${result.items.length-failed.length} saved; ${failed.length} failed: ${failed[0].error}`);setNotice(`Updated ${result.items.length} item(s).`);}
  const running=job&&['queued','running'].includes(job.status),currentIndex=catalog.items.findIndex(item=>item.media_id===current?.media_id);
  const Container=embedded?'section':'details';
  return <Container className="review-workflow" onToggle={embedded?undefined:e=>setOpen(e.currentTarget.open)}>{!embedded&&<summary>Organize files & advanced review</summary>}{open&&<>
    <div className="rw-controls"><label>Source<select aria-label="Review source" value={scope} onChange={e=>{setScope(e.target.value);setOffset(0);setSelected([]);setWorkspaceSelection(false);setPlan(null);}}><option value="">All media</option><option value="library">Image Library</option><option value="image-manager">Image Manager</option><option value="video-analyzer">Video Analyzer</option><option value="media-manager">Media Manager videos</option></select></label><label>Show<select aria-label="Review filter" value={filter} onChange={e=>{setFilter(e.target.value);setOffset(0);}}><option value="">All</option>{reviewStatuses.map(status=><option key={status} value={status}>{reviewStatusLabels[status]}</option>)}</select></label><label><input type="checkbox" checked={favorite} onChange={e=>{setFavorite(e.target.checked);setOffset(0);}}/>Favorites</label><input aria-label="Search review metadata" type="search" placeholder="Names, notes, tags, category or project" value={query} maxLength={200} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/><button disabled={busy} onClick={changed}>Refresh</button></div>
    <p role="status">{catalog.total} matching · {targets.length} selected{targets.length>0&&workspaceSelection&&scope===source?' from Images':''}{notice?` · ${notice}`:''}</p>
    <div className="rw-items">{catalog.items.map(item=><div key={item.media_id}><input type="checkbox" aria-label={`Select ${item.name}`} checked={targets.includes(item.media_id)} onChange={e=>{setWorkspaceSelection(false);setPlan(null);setSelected(e.target.checked?[...new Set([...targets,item.media_id])]:targets.filter(id=>id!==item.media_id));}}/><button disabled={busy} onClick={()=>act(()=>inspect(item))}>{item.name}</button><span>{reviewStatusLabels[item.review_status]||'To review'}{item.file_state!=='present'?` · ${item.file_state}`:''}</span></div>)}</div>
    {catalog.total>0&&<div className="rw-controls"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-48))}>Previous page</button><span>{catalog.total?offset+1:0}–{Math.min(offset+48,catalog.total)}</span><button disabled={offset+48>=catalog.total} onClick={()=>setOffset(offset+48)}>Next page</button><button onClick={()=>{setWorkspaceSelection(false);setSelected(catalog.items.map(item=>item.media_id));setPlan(null);}}>Select page</button><button onClick={()=>{setWorkspaceSelection(false);setSelected([]);setPlan(null);}}>Clear selection</button>{ids.length>0&&<button onClick={()=>{setScope(source);setWorkspaceSelection(true);setSelected([]);setPlan(null);}}>Use workspace selection</button>}</div>}
    {targets.length>0&&<div className="rw-batch-panel">
      <label>For {targets.length} selected<select aria-label="Batch review action" disabled={busy} value={batchAction} onChange={e=>setBatchAction(e.target.value)}>
        {reviewStatuses.map(status=><option key={status} value={status}>{reviewStatusLabels[status]}</option>)}
        <option value="favorite">Add to favorites</option><option value="unfavorite">Remove from favorites</option>
        <option value="category">Set category</option><option value="project">Set project</option><option value="tag">Add tag</option>
      </select></label>
      {batchAction==='category'&&<label>Category<input value={batchCategory} maxLength={120} onChange={e=>setBatchCategory(e.target.value)}/></label>}
      {batchAction==='project'&&<label>Project<input value={batchProject} maxLength={120} onChange={e=>setBatchProject(e.target.value)}/></label>}
      {batchAction==='tag'&&<label>Tag<input value={batchTag} maxLength={80} onChange={e=>setBatchTag(e.target.value)}/></label>}
      <button disabled={busy||(batchAction==='tag'&&!batchTag.trim())} onClick={()=>act(async()=>{
        if(batchAction==='tag'){for(const media_id of targets)await request('/coordinator/add_tag',{media_id,tag:batchTag});changed();setNotice(`Tagged ${targets.length} item(s).`);}
        else await batchEdit(reviewStatuses.includes(batchAction)?{review_status:batchAction}:batchAction==='category'?{category:batchCategory}:batchAction==='project'?{project:batchProject}:{favorite:batchAction==='favorite'});
      })}>Apply</button>
    </div>}
    <details ref={organizer}><summary>Copy or move files</summary><div className="rw-controls"><label>Action<select value={mode} onChange={e=>{setMode(e.target.value);setPlan(null);}}>{['copy','move','leave'].map(action=><option key={action}>{action}</option>)}</select></label><label>Destination preset<select aria-label="Destination preset" value={preset} onChange={e=>{setPreset(e.target.value);setPlan(null);setPath('');}}>{presets.map(choice=><option key={choice.id} value={choice.id}>{choice.name}</option>)}</select></label><span className="rw-path">{presets.find(choice=>choice.id===preset)?.path||'Choose a folder for this preset'}</span><label>If a name exists<select value={collision} onChange={e=>{setCollision(e.target.value);setPlan(null);}}><option value="rename">Rename new copy</option><option value="skip">Skip existing name</option></select></label><button disabled={busy||!targets.length||targets.length>100} onClick={()=>act(async()=>setPlan(await request('/plan',{media_ids:targets,mode,destination_preset_id:preset,collision})))}>Prepare plan</button></div>
      <details><summary>Configure destination folder</summary><label>Absolute folder path<input aria-label="Destination folder path" value={path} maxLength={1000} onChange={e=>setPath(e.target.value)}/></label><button disabled={busy||!path} onClick={()=>act(async()=>{await request('/presets',{destination_preset_id:preset,path});setPlan(null);changed();})}>Save destination preset</button><p>Missing folders are created when a reviewed plan runs. Existing files are preserved.</p></details>
      {plan&&<div className="rw-plan"><h4>{plan.mode} plan · {plan.status}</h4>{plan.entries.map(entry=><p key={entry.media_id}>{entry.media.name||entry.media_id}<br/><span className="rw-path">{entry.source} → {entry.target||entry.status}</span> · {entry.status}</p>)}{plan.error&&<p role="alert">{plan.error}</p>}{plan.status==='ready'&&<><button disabled={busy} onClick={()=>act(async()=>{setPlan(await request('/apply',{reviewed_plan_id:plan.id,confirmed:true}));changed();})}>Confirm {plan.mode} plan</button><button disabled={busy||plan.mode==='leave'} onClick={()=>act(async()=>{setPlan(await request('/approve',{reviewed_plan_id:plan.id,confirmed:true}));setNotice('This exact plan is approved for a bounded coordinator transfer.');})}>Approve this plan for coordinator</button></>}</div>}
      <p>Copies receive an independent review record in Image Manager, with the original media ID and source metadata retained. Moves preserve the registered ID and source references. Registered Video Analyzer clips use these plans; Media Manager transfers use its native plans.</p>
    </details>
    <details><summary>Transfer history & undo</summary>{history.map(receipt=><div key={receipt.id}><button onClick={()=>{setPlan(receipt);organizer.current.open=true;organizer.current.scrollIntoView({block:'nearest'});}}>{receipt.mode} · {receipt.status} · {receipt.created}</button>{receipt.mode==='move'&&['complete','interrupted'].includes(receipt.status)&&receipt.entries.some(entry=>entry.status==='moved')&&<button disabled={busy} onClick={()=>act(async()=>{if(!window.confirm('Return unchanged moved files to their original locations?'))return;setPlan(await request('/undo',{reviewed_plan_id:receipt.id,confirmed:true}));changed();})}>Undo move</button>}</div>)}</details>
    {error&&<p role="alert">{error}</p>}
    <dialog className="rw-dialog" ref={dialog} aria-label="Review media" onCancel={e=>{e.preventDefault();if(!busy)act(async()=>{await save();setCurrent(null);});}} onKeyDown={e=>{if(busy)return;if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();act(()=>next(1));return;}if(e.target.closest('input,textarea,select'))return;if(e.key.toLowerCase()==='r'){e.preventDefault();act(()=>next(1,true));}if(e.key==='ArrowRight'&&currentIndex<catalog.items.length-1){e.preventDefault();act(()=>next(1));}if(e.key==='ArrowLeft'&&currentIndex>0){e.preventDefault();act(()=>next(-1));}}}>
      {current&&value&&<><header><h2>{current.name} · {currentIndex+1} of {catalog.items.length}</h2><button disabled={busy} onClick={()=>act(async()=>{await save();setCurrent(null);})}>Save & close</button></header>{current.media_type==='image'&&current.file_state==='present'&&<img src={reviewImageUrl(current.media_id.split(':')[0],current.media_id.split(':').slice(1).join(':'))} alt={current.name}/>}
        {current.media_id.startsWith('video-analyzer:')&&current.file_state==='present'&&<video crossOrigin="anonymous" ref={videoPlayer} controls preload="metadata" aria-label="Reviewed video" src={apiUrl(`/visual-review/workflow/videos/${encodeURIComponent(current.media_id.split(':')[1])}/content`)}/>}
        <ReviewRecordDetails image={current}/><ReviewFieldsEditor value={value} onChange={setValue} disabled={busy}/><label>Caption / notes<textarea aria-label="Review caption" rows={3} maxLength={10000} disabled={busy} value={value.caption} onChange={e=>setValue({...value,caption:e.target.value})}/></label><ReviewTags value={value.tags} available={catalog.items.flatMap(item=>item.tags)} onChange={tags=>setValue({...value,tags})} disabled={busy}/>
        <div className="rw-controls"><button disabled={busy||currentIndex<=0} onClick={()=>act(()=>next(-1))}>Previous</button><button disabled={busy} onClick={()=>act(save)}>Save</button><button disabled={busy||currentIndex>=catalog.items.length-1} onClick={()=>act(()=>next(1))}>Save & next</button><button disabled={busy} onClick={()=>act(()=>next(1,true))}>Done & next</button></div>
        <p>← / → save and browse · R finishes review and advances · Ctrl+Enter saves and advances.</p>
        {['missing','unavailable'].includes(current.file_state)&&<details><summary>Recover missing file</summary><label>Matching file path<input aria-label="Locate file path" value={path} onChange={e=>setPath(e.target.value)}/></label><button disabled={busy||!path} onClick={()=>act(async()=>{await save();const result=await request('/locate',{media_id:current.media_id,path});setCurrent({...result,name:current.name});changed();})}>Locate file</button><button disabled={busy} onClick={()=>act(async()=>{if(!window.confirm('Remove this stale entry from REVIEW? Saved metadata and physical files are preserved.'))return;await save();await request('/forget',{media_id:current.media_id});setCurrent(null);changed();})}>Remove stale entry</button></details>}
        <details onToggle={e=>{if(e.currentTarget.open&&!models.length)reviewRequest('/capabilities').then(result=>setModels(result.vision_models)).catch(failure=>setError(failure.message));}}><summary>Optional AI suggestions</summary><p>Run explicitly, then edit, accept or ignore. Suggestions never change your review automatically.{current.media_type==='video'?' Video suggestions describe the registered preview frame.':''}</p><select aria-label="Review suggestion model" value={model} onChange={e=>setModel(e.target.value)}><option value="">Choose an installed vision model</option>{models.map(choice=><option key={choice.id} value={choice.id}>{choice.name}</option>)}</select><button disabled={busy||running||!model||current.media_id.startsWith('media-manager:')||current.file_state!=='present'} onClick={()=>act(async()=>{await save();setJob(await request('/suggest',{media_ids:[current.media_id],model}));})}>Suggest review metadata</button>{running&&<button onClick={()=>act(()=>reviewRequest('/stop',{}))}>Stop suggestions</button>}{job&&<p role="status">{job.message} {job.processed}/{job.total}{job.errors?.map(failure=><span key={failure.id}>{failure.error}</span>)}</p>}
          {suggestion?.status==='suggested'&&suggested&&<><p>{suggestion.analysis.confidence} · {suggestion.orientation}</p><dl>{Object.entries(suggestion.analysis).filter(([key])=>key!=='confidence').map(([key,description])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{description||'Uncertain'}</dd></div>)}</dl><label>Suggested caption<textarea value={suggested.caption} maxLength={10000} onChange={e=>setSuggested({...suggested,caption:e.target.value})}/></label><label>Suggested category<input value={suggested.category} maxLength={120} onChange={e=>setSuggested({...suggested,category:e.target.value})}/></label><ReviewTags value={suggested.tags} available={value.tags} onChange={tags=>setSuggested({...suggested,tags})}/><button disabled={busy} onClick={()=>act(async()=>{await save();await request('/suggestions',{media_id:current.media_id,action:'accept',changes:{...suggested,tags:[...new Set([...value.tags,...suggested.tags])]}});await inspect(current);changed();})}>Accept edited suggestions</button><button disabled={busy} onClick={()=>act(async()=>{await request('/suggestions',{media_id:current.media_id,action:'ignore'});setSuggestion(null);})}>Ignore suggestions</button></>}
        </details>{error&&<p role="alert">{error}</p>}</>}
    </dialog>
  </>}</Container>;
}
