// Small, local illustrations: no external images, user files, or model calls.
// [input picture, result picture, input label, action, result label, motion]
export const featureVisuals = {
  dashboard: ['status', 'check', 'Services', 'Check', 'Ready to work', 'pulse'],
  queue: ['stack', 'check', 'Waiting requests', 'Run', 'Completed result', 'flow'],
  tools: ['nodes', 'chat', 'Function steps', 'Review', 'Send to chat', 'flow'],
  chats: ['document', 'chat', 'Your report', 'Ask', 'Key takeaways'],
  library: ['stack', 'chat', 'Saved prompts', 'Reuse', 'New conversation'],
  knowledge: ['document', 'nodes', 'Project sources', 'Connect', 'Linked knowledge'],
  canvas: ['pen', 'landscape', 'A rough idea', 'Draw', 'Layered artwork'],
  converter: ['landscape', 'landscape', 'Original JPG', 'Convert', 'PNG copy'],
  'local-files': ['document', 'document', 'Original DOCX', 'Edit', 'Revised copy'],
  'document-editor': ['text', 'document', 'Draft notes', 'Format', 'Structured report'],
  packager: ['stack', 'package', 'Project files', 'Bundle', 'One ZIP archive'],
  'hash-auditor': ['stack', 'check', 'File copies', 'Compare', 'Matching hashes'],
  'folder-review': ['stack', 'document', 'Source folder', 'Review', 'Findings report'],
  audio: ['wave', 'text', 'Meeting audio', 'Transcribe', 'Editable transcript', 'wave'],
  'sound-mixer': ['wave', 'sliders', 'Audio channels', 'Balance', 'Recorded mix', 'wave'],
  slicer: ['cube', 'layers', 'STL model', 'Slice', 'Print layers', 'scan'],
  integrations: ['link', 'wave', 'Supported playback', 'Record', 'Local recording', 'wave'],
  images: ['gallery', 'landscape', 'Saved images', 'Choose', 'Open an image'],
  'image-manager': ['gallery', 'grid', 'Photo folder', 'Lay out', 'Contact sheet'],
  generate: ['text', 'landscape', '“Alpine sunrise”', 'Generate', 'Concept illustration'],
  review: ['landscape', 'tag', 'Unsorted image', 'Classify', 'Caption + tags'],
  'image-editor': ['landscape', 'warm', 'Original image', 'Adjust', 'Warmer edited copy'],
  'gif-maker': ['frames', 'landscape', 'Image sequence', 'Animate', 'Looping GIF', 'frames'],
  workflows: ['landscape', 'nodes', 'Reference image', 'Process', 'Review each stage', 'flow'],
  'media-manager': ['gallery', 'grid', 'Media collection', 'Organize', 'Reviewed file plan'],
  characters: ['portrait', 'document', 'Character reference', 'Describe', 'Biography + notes'],
  faces: ['gallery', 'portrait', 'Reference photos', 'Curate', 'Face dataset'],
  'character-parts': ['portrait', 'eye', 'Character image', 'Crop', 'Labeled eye detail'],
  lora: ['gallery', 'layers', 'Images + captions', 'Train', 'Style adapter'],
  university: ['book', 'check', 'Guided lesson', 'Practice', 'Knowledge check'],
  'agent-university': ['nodes', 'check', 'Workflow plan', 'Supervise', 'Reviewed result'],
  'neural-network': ['sliders', 'nodes', 'Inputs + weights', 'Explore', 'Network output', 'flow'],
  'break-room': ['keys', 'wave', 'Mini Piano', 'Play', 'Notes + chords', 'wave'],
  browser: ['browser', 'code', 'Public webpage', 'Inspect', 'Page source'],
  'web-system': ['browser', 'document', 'Public sources', 'Research', 'Cited evidence'],
  'reels-analyzer': ['frames', 'text', 'Verified reel', 'Analyze', 'Brief summary'],
  '3d-viewer': ['cube', 'cube', 'Local 3D model', 'Edit', 'Saved 3D project'],
  markdown: ['code', 'document', 'Markdown source', 'Preview', 'Formatted report'],
  'html-viewer': ['code', 'browser', 'HTML snippet', 'Preview', 'Rendered page'],
  'css-viewer': ['code', 'palette', 'Stylesheet rules', 'Style', 'Layout + color'],
  'styling-library': ['palette', 'browser', 'Offline example', 'Adapt', 'Your interface', 'pulse'],
  'js-viewer': ['browser', 'code', 'Captured script', 'Inspect', 'Editable source'],
  spreadsheets: ['grid', 'chat', 'CSV records', 'Select', 'Focused question'],
  shortcuts: ['keys', 'book', 'Keyboard commands', 'Save', 'Personal reference'],
};

export const categorySymbols = { utilities: 'sliders', workspace: 'chat', images: 'landscape', characters: 'portrait', learning: 'book', viewers: 'browser' };
